#+STARTUP: showeverything
* Almond Horns
This macaroon type dough is rolled in sliced almonds for a double tasty treat!
- Time:
- 25 minutes to assemble 
- 20 minutes to chill
- 12-14 minutes to bake

** Ingredients:
- 1 box (7 oz) Odense Almond Paste, grated 
- ¾ cup confectionary sugar 
- 1 large egg (room temperature), separated 
- 1 Tbsp & 2 tsp all purpose flour 
- 1 cup thinly sliced almonds, slightly crushed 
- 4 oz bittersweet chocolate 
- 1 Line cookie sheet with parchment or foil. 

** Method:
1) In a food processor or with a mixer combine Almond Paste and sugar. Mix until the texture of fine crumbs. Add egg white and flour, reserving yolk. Mix until dough becomes a smooth paste, it will be slightly sticky.
2) Turn dough out onto a lightly floured surface. With floured hands roll dough into a 12 inch log. Divide into 12 equal pieces and roll into balls. Roll balls between palms into 3 inch logs, slightly tapered at ends.
3) Spread almonds on a plate. Beat reserved egg yolk with 2 tablespoons of water. Dampen log with beaten yolk. Roll each log in almonds until coated, bending into crescents. Place crescents 2 inches apart on cookie sheet and refrigerate for 20 minutes. Preheat oven to 350 F.
4) Bake 12 to 14 minutes or until light golden in color. Cool sheet on wire rack for 5 minutes, and loosen crescents with a spatula. Slide parchment off of sheet and back onto wire rack to finish cooling cookies.
5) Melt chocolate in a double boiler or microwave. Dip cookie ends into melted chocolate. Place back on parchment until chocolate is dry. Layer "Almond Horns" between sheets of wax paper in an airtight container.

** Yield:
- 12 cookies

** Credits:
- From Cathy Petrakis, 31Dec08
- date created: [2009-01-01 Thu]
