#+STARTUP: showeverything
* Apple Fritters 

** Ingredients:
- Points: 4
- Servings: 4
- Preparation Time :12 minutes
- Cooking Time: 6 minutes
- Level of Difficulty: Easy

** Method:
1. ½ cup all-purpose flour 
2. 2 Tbsp sugar 
3. ⅛ tsp table salt 
4. ½ cup fat-free egg substitute 
5. ¼ cup fat-free skim milk 
6. ½ tsp vanilla extract
7. 2 pinches Apple Pie spice
8. 2 large apple(s), peeled, cored and coarsely grated (McIntosh or Granny Smith recommended) 
9. 1 Tbsp reduced-calorie margarine 
10. 1 Tbsp powdered sugar 
11. Instructions: 
12.  In a large bowl, combine flour, granulated sugar and salt; mix well. Whisk in egg substitute, milk and extract; stir in apples. 
13.  Melt margarine in a large nonstick skillet over medium-high heat. Drop apple mixture into pan, making 8 even fritters. Cook until golden brown, about 2 to 3 minutes per side. 
14.  Sift powdered sugar over top of fritters just before serving. 

** Yields 2 fritters per serving 

** Credits:
- date created: [2008-02-10 Sun]
