#+STARTUP: showeverything
* Apple Twist Bread
** Ingredients:
*** Dough
- 390g King Arthur Unbleached All-Purpose Flour
- 43g potato flour OR dry instant mashed potatoes, unflavored*
- 35g granulated sugar
- 1½ teaspoons instant yeast
- 1¼ teaspoons salt
- 43g soft butter
- 1 teaspoon vanilla extract
- 1 large egg
- 255g room-temperature or lukewarm milk
- *For an alternative, see tips, below.

*** Filling
- 170g to 227g peeled, grated apple (283g to 340g whole apples)
- 14g lemon juice
- 99g granulated sugar
- 21g cornstarch or Instant ClearJel
- ⅛ teaspoon salt
- 1 teaspoon cinnamon
- 113g chopped walnuts or pecans, optional

*** Glaze
- 113g confectioners' sugar
- 1 teaspoon vanilla extract
- ⅛ teaspoon salt
- 14g to 28g water OR 28g to 57g heavy cream

** Method:
1. To make the dough: Whisk together all of the dry ingredients, then add the butter, vanilla, egg, and milk, mixing until a shaggy dough forms. If your schedule permits, let the dough rest for 30 minutes; this resting period allows the flour to absorb the liquid fully, making it easier to knead.

2. Knead the dough - by hand, using a mixer, or in a bread machine set on the dough cycle - until it's smooth and soft, though still slightly sticky. Place the dough in a greased bowl, turning to coat. Cover the bowl, and let the dough rise until it's almost doubled in bulk, about 1½ to 2 hours. The amount of time this takes will depend on the temperature of your kitchen; yeast works the fastest at about 85 degreesF, but we prefer the flavor the bread gets from a longer, cooler (about 70 degreesF) rise. If you're using a bread machine set on the dough cycle, simply allow it to complete its cycle.

3. While the dough is rising, make the filling.

4. To make the filling using cornstarch: Toss the grated apple with the lemon juice in a saucepan. Whisk together the sugar, cornstarch, salt, and cinnamon, and add to the pan, stirring to combine. Cook over low heat, stirring frequently, until the apple starts to release its juice. Increase the heat to medium, and bring to a simmer. Simmer, stirring, until the mixture thickens, 1 to 2 minutes; drawing a spatula across the bottom of the pan should leave a track that doesn't readily fill in. Remove from the heat, and set aside to cool to room temperature; if you want to hasten the process, place in the refrigerator.

5. To make the filling using Instant ClearJel: Whisk together the sugar, ClearJel, salt, and cinnamon. Toss the grated apple with the lemon juice, then add that to the sugar mixture. Mix well, and set aside.

6. To assemble the loaf: Gently deflate the risen dough and turn it out onto a lightly floured or greased work surface. Divide the dough in half. Roll the first half into a 10" x 12" rectangle. Spread half the filling over the rolled-out dough, leaving a ½" margin clear of filling along all sides. If adding chopped nuts, sprinkle them evenly over the filling.

7. Starting with a long side, roll the dough into a log, sealing the edge. Use a bench knife, pizza cutter, or sharp knife to cut the log in half lengthwise. Place the half-logs, filled side up, side by side on a well-greased or parchment-lined baking sheet. Keeping the filling side up, twist or "braid" the two logs together, working from the center to each end. Pinch the ends together. Repeat with the second piece of dough. Cover the twists lightly, and set them aside to rise for 1 to 2 hours; they should be puffy but not doubled in bulk. Want to make the bread ahead, then refrigerate overnight and bake the next morning? See "tips," below.

8. To bake the bread: Bake the loaves in a preheated 350 degreesF oven for 30 to 40 minutes, until they're lightly browned. Check the loaves after 20 minutes and tent with aluminum foil if they're browning too quickly. When the loaves are fully baked, a digital thermometer inserted into a loaf (be sure to position the thermometer in the bread, not the filling) should register about 190 degreesF. Remove the bread from the oven and allow it to cool for about 1 hour before glazing and serving.

9. To make the glaze: Mix together all of the glaze ingredients. Drizzle over the loaves once they're cool.

10. Store leftover bread, loosely covered, at room temperature for several days; freeze for longer storage. If you know ahead of time you're going to freeze one or both of the loaves, don't glaze; wrap completely cooled, unglazed bread tightly in plastic, and freeze for up to a month. When ready to serve, remove from the freezer, unwrap, cover loosely with plastic, and let thaw at room temperature. Glaze and serve.

** Credits:
https://www.kingarthurflour.com/recipes/cinnamon-apple-twist-bread-recipe
