#+STARTUP: showeverything
* Blueberry Crumb Bars
** Ingredients:
*** For the crust and topping:
- Cooking spray
- 1 cup all-purpose flour
- ¾ cup old-fashioned rolled oats
- ½ cup finely chopped almonds
- ½ cup packed light brown sugar
- 1 teaspoon ground cinnamon
- ¼  teaspoon kosher salt
- ½ cup (1 stick) cold unsalted butter, cut into 8 pieces
*** For the filling:
- 2 cups fresh blueberries, washed and dried
- ¼ cup granulated sugar
- 1 tablespoon cornstarch
- Finely grated zest of 1 medium lemon
- Juice of 1 lemon (about 2 tablespoons)
** Method:
1. Arrange a rack in the middle of the oven and heat to 350°F.
2. Line an 8-inch square baking dish with aluminum foil, leaving overhang on all sides.
3. Grease the foil lightly with cooking spray; set aside.
4. Make the crust and topping: Place the flour, oats, almonds, brown sugar, cinnamon, and salt in a large bowl and stir to combine.
5. Add the butter and, using a pastry cutter or your fingertips, incorporate until no large pieces of butter remain. (The mixture should be crumbly and hold together when squeezed.)
6. Set aside 1 cup of the mixture.
7. Transfer the remaining mixture to the prepared baking dish and press it firmly and evenly into the pan to form the crust.
8. Make the filling: Place the blueberries in a medium bowl.
9. Add the sugar, cornstarch, and lemon zest and lemon juice and toss gently to combine.
10. Transfer the mixture to the baking dish and spread into an even layer over the crust.
11. Sprinkle the reserved 1 cup crumb mixture over the blueberries.
12. Bake until the filling is bubbling and the top is golden-brown, about 40 minutes.
13. Let cool at least 2 hours before cutting into bars.

** Credits:
- From https://www.thekitchn.com/blueberry-crumb-bars-258364#post-recipe-12714
- date created: [2022-03-12 Sat]
