#+STARTUP: showeverything
* Blueberry Zucchini Snack Cake with Lemon Buttercream
- Prep Time: 20 minutes
- Cook Time: 50 minutes
- Total Time: 1 hour, 10 minutes
** Ingredients:
*** Cake
- 3 large eggs
- 1 cup vegetable oil
- 1 Tbsp vanilla extract
- 2¼ cups sugar
- 2 cups shredded zucchini
- 3 cups all purpose flour
- 1 tsp salt
- 1 tsp baking powder
- ¼ tsp baking soda
- 1 pint blueberries (tossed in 1 tsp flour)
*** Lemon Buttercream
- 1 cup butter, (2 sticks, 8 ounces) at room temperature
- 4 cups confectioners' sugar
- juice of one lemon
** Method:
1. Set oven to 350F.
2. Lightly grease and flour a 9x13 baking pan.
3. Beat the eggs, oil, vanilla and sugar until well blended. Fold in the zucchini.
4. Whisk the flour, salt, baking powder, and baking soda to combine. Slowly add it to the wet mixture, mixing just enough to blend.
5. Fold in the blueberries, and pour the batter into the prepared pan.
6. Bake for about 50 minutes, just until the top is turning golden and a toothpick inserted in the center comes out without wet batter clinging to it.
7. Cool on a rack.
8. To make the frosting, put the softened butter into the bowl of a food processor and process until creamy. Add the sifted powdered sugar, one cup at a time, processing till smooth after each addition. After the second cup of sugar add in the lemon juice. Scrape down the sides of the machine as necessary. Adjust the texture by adding a little more lemon or a little more sugar.
9. Frost the cooled cake and store in the refrigerator.
** Yield:
Serves 12
** Credits:
- Author: Sue Moran
- https://theviewfromgreatisland.com/blueberry-zucchini-snack-cake-with-lemon-buttercream/
- [2019-08-22 Thu]
