#+STARTUP: showeverything
* Cheddar Cheese Coins
** Ingredients:
- ¾ cup (104 grams) all-purpose flour, plus more for surfaces
- 1 cup (85 grams) finely shredded extra-sharp Cheddar
- ⅓ cup (33 grams) freshly grated Parmesan
- ¾ teaspoon freshly ground black pepper
- ½ teaspoon kosher salt (Diamond Crystal)
- ¼ teaspoon paprika
- 5 tablespoons (71 grams) cold unsalted butter, cubed
- ⅓ cup (44 grams) finely chopped scallions
- 2 to 3 tablespoons toasted sesame seeds, for coating (/optional/)
** Method:
1. In the bowl of a food processor, combine flour, both cheeses, black pepper, salt and paprika, and pulse until well combined and sandy, about 30 seconds.
2. Add butter and scallions, and pulse just until well blended, about 30 seconds.
3. Continue pulsing and drizzle in 2 tablespoons of ice-cold water just until the dough comes together.
4. Transfer dough to a lightly floured work surface and divide in half.
5. Roll each half into a log that is 1 inch in diameter and about 12 inches long.
6. If using sesame seeds, spread them onto the work surface and roll the log over the seeds until lightly coated.
7. Wrap each piece of dough in plastic wrap and chill until firm, about 2 hours or overnight.
8. Place racks in upper and lower thirds of the oven and heat oven to 350°.
9. Line 2 baking sheets with parchment paper or aluminum foil.
10. Using a sharp knife, slice chilled logs into ¼-inch-thick slices.
11. Arrange them on the prepared sheets about ½ inch apart.
12. Bake, switching the sheets from top to bottom and rotating halfway through, until golden and just firm (they will continue to crisp up as they cool), 23 to 25 minutes.
13. Let cookies cool on the baking sheets for 2 minutes, then transfer them onto wire racks to cool completely.
14. Store cookies in an airtight container at room temperature overnight, then refrigerate for up to 1 week.
15. To recrisp after refrigerating and serve warm, heat in a 350° oven for 5 minutes.
** Yield:
About 5 dozen cookies
** Credits:
- From https://cooking.nytimes.com/recipes/1022673-cheddar-cheese-coins
- date created: [2023-12-18 Mon]
