#+STARTUP: showeverything
* Chocolate Aquafaba Mousse
** Ingredients:
- 5 ounces chocolate chips (heaping ¾ cup measurement; see notes)
- ¾ cup aquafaba (liquid from a can of chickpeas)
- ¼ teaspoon cream of tartar
** Method:
1. Melt the chocolate chips, stirring until smooth. I do this by arranging a heat-safe bowl over a saucepan filled with an inch of water, to make a double-boiler. Bring the water to a boil, and let the steam gently melt the chocolate in the bowl above it.
2. Once the chocolate is smooth, set it aside to cool and set a timer for 20 minutes. (Do this if you're using a stand mixer; if you are going to whip the aquafaba with a hand held electric mixer or you're using another variety of bean liquid, you may want to start the next step right away, in case it takes closer to 15 minutes.)
3. When the timer goes off, pour the aquafaba and cream of tartar into the bowl of your stand mixer. Mix the two together, starting on low and then moving up to the highest speed possible, until the mixture creates a thick white foam that forms "stiff peaks." You should be able to turn the bowl completely upside down with nothing falling out. If you can't do that, keep whipping until it happens. This typically takes my stand mixer about 3 minutes when I used canned chickpea liquid. If you use home-cooked chickpea liquid, or the liquid from another type of bean, it can take up to 15 minutes of whipping.
4. Once you have achieved a fluffy white foam, keep the mixer running on a medium-low speed and pour the melted chocolate into the foam. It's normal for the foam to sink a little bit when you add the chocolate, but it should not be liquid-y. Stop and scrape down the sides of the bowl to make sure the melted chocolate gets evenly incorporated.
5. Depending on the type of chocolate you use, you'll either be able to pour the chocolate mousse into 6 small glass dishes, or you'll need to use a spoon to scoop it into the serving dishes. (I usually have to use a spoon to scoop it, because it's already fluffy.)
6. Let the mousse chill for at least an hour before serving. I like to top it with fresh berries and a dollop of coconut whipped cream. Leftover mousse can be stored in the fridge, tightly covered, for up to a week.
** Credits:
- From https://detoxinista.com/aquafaba-mousse/
- date created: [2020-06-02 Tue]
