#+STARTUP: showeverything
* Chocolate Chip Cookies

** Ingredients:
- 1 cup (120g) unbleached flour (I use King Arthur - organic if I can find it)
- 1 cup (113g) King Arthur white or regular whole wheat flour
- ½ cup (45g) quick cooking oatmeal (uncooked) I use what I have on hand, not necessarily quick cooking.
- 1 tsp. baking soda
- 1 tsp. coarse salt
- 1 cup unsalted butter, softened
- ¾ cup (150g) white sugar
- ¾ cup (150g) brown sugar
- 2 tsp. vanilla extract
- 1 egg
- 1 lb (454g) premium quality bittersweet chocolate (see note below) cut into medium-sized chunks.
- 2 cups (250g) walnuts, coarsely chopped (/the Supreme Cookie Dude aka Pat, likes big chunks of nuts and lots of!/)

** Method:

#+begin_note
*About the chocolate*: I do not use chocolate chips because IMHO the better the chocolate, the better the cookie. If I can't afford the really good stuff I don't make these. I like to use Valhrona bittersweet chocolate that comes in thin bars (not sure of the weight but the bars are around 6" by 3" and maybe  ½" deep -- I use several) so that the chocolate is sort of in layers in the cookie. Scharffen Berger, Green and Black's dark baking, and Callebaut all work well. The best buy is from Trader Joe's though (sorry, Jen!!!) and it's their 1 lb. Plus bars which are actually made by Callebaut. I use either the 72% (especially if making these cookies for adults) or the Dark Chocolate (which is closer to semi-sweet and better for kids). But they also have the best price around on Valhrona too.
#+end_note
1. In a medium bowl, whisk together flour, oats, baking soda, and salt.
2. In a large mixing bowl, cream together butter and sugars.
3. Blend in vanilla and egg.
4. Slowly add in the flour mixture until nearly combined.
5. Add in chocolate chips and nuts and stir by in by hand (/this is normally Pat's job/).
6. It may seem like the dough won't handle all the chocolate and nuts but it does.
7. Drop by rounded tablespoonfuls onto baking sheets
#+begin_tip
(I use one of those cool cookie scoops that has the releasing mechanism) - you can put them very close together.
#+end_tip
9. Refrigerate for 24 hours or longer (or freeze) then I take out only what I need for one pan at a time and bake on sheets.
10. These are great to have in the freezer to bake at a moment's notice - do not thaw or allow to come to room temp before baking.
11. Line baking sheets with parchment paper or use silpat sheets and preheat over to 350o.
12. Bake one sheet at a time for 7 minutes, then turn sheets around 180o and bake for another 6 minutes until lightly browned.
#+begin_note
Your oven may run hotter or colder than mine but this it what works in mine.
#+end_note
14. Remove pan from the oven but leave cookies on the paper and slip the paper onto a wire rack to cool.
15. Since there's so much chocolate in these and it's in big pieces, if you take the cookies off the paper the chocolate will drip while it's still hot.

** Yield:
Makes 48 cookies.

** Credits:
- The Obsessive Compulsive Version (that I should be embarrassed about except for the fact that they are so darned good!)
- Nancy Burnett, November 2010
- Shared 26-April-2012. *NOT FOR REDISTRIBUTION!*
- date created: [2012-04-26 Thu]

# Local Variables:
# jinx-local-words: "Jen"
# End:
