#+STARTUP: showeverything
* Chocolate Truffle Cookies

** Ingredients:
- 4 squares (1 oz. each) unsweetened chocolate
- 2 cups (12 oz.) semi-sweet chocolate chips, divided
- ⅓ cup butter
- 1 cup sugar
- 3 eggs
- 1½ teaspoons vanilla extract
- ½ cup all-purpose flour
- 2 tablespoons baking cocoa
- ¼ teaspoon baking powder
- ¼teaspoon salt
- Confectioners Sugar

** Method:
1. In a microwave or double boiler, melt unsweetened chocolate, 1 cup of chocolate chips and butter. Cool for 10 minutes.
2. In a mixing bowl, beat sugar and eggs for 2 minutes until well blended. Beat in vanilla and the chocolate mixture. Mix in flour, cocoa and baking powder. Stir in remaining chocolate chips.
3. Cover and chll for at least 3 hours.
4. Prehat oven to 350 degrees. With lightly floured hands, roll into 1-inch balls. Place on ungreased cookie sheets. Bake at 350 degrees for 10-12 minutes or until lightly puffed and set. Cool on pan 3-4 minutes before removing to wire rack to cool completely. Dust with confectioners sugar.

** Yield:
About 4 dozen.

** Credits:
- date created: [2007-06-27 Wed]
