#+STARTUP: showeverything
* Chocolate Cream Pie
** Ingredients
*** Crust
- 181g King Arthur Unbleached All-Purpose Flour
- ½ teaspoon salt
- 46g vegetable shortening
- 57g (½ stick) cold unsalted butter
- 28 to 57g ice water
*** Filling
- 28g unsalted butter
- 227g semisweet chocolate, chopped
- 1 teaspoon vanilla extract
- 131g granulated sugar
- 3 tablespoons cornstarch
- 11g unsweetened cocoa powder
- 1 teaspoon espresso powder, optional; for richer chocolate flavor
- ⅛ teaspoon salt
- 3 large egg yolks
- 227g heavy cream, divided
- 454g milk
*** Topping
- 227g heavy cream
- 28g confectioners' sugar
- ½ teaspoon vanilla extract
** Method
*** Crust
1. In a medium bowl, whisk together the flour, and salt.
2. Cut in the shortening until it's in lumps the size of small peas.
3. Dice the butter into ½" pieces, and cut into the mixture until you have flakes of butter the size of your fingernail.
4. Add the water, two tablespoons at a time, mixing with a fork as you sprinkle the water into the dough.
5. When the dough is moist enough to hold together when you squeeze it, transfer it to a piece of wax or parchment paper. It's ok if there are dry spots in the pile. Use a spray bottle of water to lightly spritz these places; that way you'll add just enough water to bring the dough together without adding too much or creating a wet spot.
6. Fold it over on itself three or four times to bring it together, then pat it into a disk ¾" thick
7. Roll the disk on its edge, like a wheel, to smooth out the edges. This step will ensure your dough will roll out evenly, without a lot of cracks and splits at the edges later. Wrap in plastic and refrigerate for 30 minutes before rolling.
8. To blind bake the crust: Preheat the oven to 400 degreesF. Lightly grease a 9" pie pan that's at least 2" deep. This will make serving the pie easier after it's finished.
9. Roll out the pastry for the pie to a 13" circle. Transfer it to the prepared pan, and trim the edges so they overlap the edge by an inch all the way around. Tuck the edges up and under, and flute them. Put the lined pie pan in the refrigerator to chill for 10 minutes.
10. Line the crust with foil or parchment paper, and fill it with pie weights or dried beans. Bake the crust for 20 minutes. Remove it from the oven, and gently remove foil or parchment with the weights or beans. Return the crust to the oven for 10 to 20 more minutes, until it's golden brown all over. If the edges of the crust start becoming too brown, cover them with a pie shield, or strips of aluminum foil. Remove the crust from the oven and cool completely.
*** Filling
1. Place the chopped chocolate, butter, and vanilla extract in a 2-quart mixing bowl; set aside.
2. In a medium saucepan away from heat, whisk together the sugar, cornstarch, cocoa, espresso powder, and salt. Whisk in ¼ cup of cold heavy cream until the mixture is smooth, with no lumps. Repeat with another ¼ cup of the cream. Whisk in the egg yolks.
3. Place the saucepan over medium heat, and gradually whisk in the remaining cream and milk.
4. Bring to a boil, whisking constantly as the mixture thickens; boil for 1 minute.
5. Remove the pan from the heat and pour the mixture over the reserved chocolate and butter.
6. Whisk until the chocolate is melted and the mixture is smooth.
7. (optionally) Pass the filling through a strainer into a bowl to remove any lumps.
8. Place plastic wrap or buttered parchment paper on the surface to prevent a skin from forming, and chill thoroughly.
*** Topping
1. Place the heavy cream in a chilled mixing bowl.
2. Whip until the whisk begins to leave tracks in the bowl.
3. Add the sugar and vanilla and whip until the cream holds a medium peak.
4. Assembly
5. Transfer the cooled filling to the cooled, baked pie crust. Level the top with the back of a spoon or an offset spatula.
6. Spoon or pipe the whipped cream on top.
7. Chill the pie until ready to serve. Note: If you're not planning on serving the entire pie at once, top individual slices with a dollop of whipped cream just before serving.
**** Variation: Meringue topping
***** Ingredients
- 3 large egg whites (reserved from filling)
- pinch of salt
- ½ cup (3½ ounces) sugar
- 3 tablespoons (1½ ounces) water
***** Method
1. Place the egg whites in a clean bowl with clean beaters. Add the pinch of salt.
2. In a small saucepan, bring the sugar and water to a boil, stirring occasionally, until the sugar dissolves. Boil for 2 minutes, then remove from the heat.
3. Whip the egg whites until they turn white and the whisk begins to leave tracks in the bowl. Slowly add the hot sugar syrup, and continue beating until the whites make stiff peaks.
4. Preheat the oven to 400 degreesF.
5. Pipe or spoon the meringue over the top of the filled, chilled pie, making sure you cover the filling completely.
6. Place the pie in the oven for 5 to 7 minutes, until the top of the meringue is golden brown. Remove from the oven and refrigerate until ready to serve
** Credits
http://www.kingarthurflour.com/recipes/chocolate-cream-pie-recipe
** Notes
*** <2016-02-28 Sun> 
Made at T's request. Good pie, but the crust was a bit hard/tough. Overworked and over cooked? 
Pudding was good. I used well-ground coffee beans and didn't strain it.
