#+STARTUP: showeverything
* Chocolate Chip Cookies

** Ingredients:
- 1 cup unbleached flour (I use King Arthur - organic if I can find it)
- 1 cup King Arthur white or regular whole wheat flour
- ½ cup quick cooking oatmeal (uncooked) I use what I have on hand, not necessarily quick cooking.
- 1 tsp. baking soda
- 1 tsp. coarse salt
- 1 cup unsalted butter, softened
- ¾ cup white sugar
- ¾ cup brown sugar
- 2 tsp. vanilla extract
- 1 egg
- 1 lb premium quality bittersweet chocolate (see note below) cut into medium-sized chunks.
- 2 cups walnuts, coarsely chopped (the Supreme Cookie Dude aka Pat, likes big chunks of nuts and lots of!)

** Method:
1. About the chocolate: I do not use chocolate chips because IMHO the better the chocolate, the better the cookie.
2. If I can't afford the really good stuff I don't make these. I like to use Valhrona bittersweet chocolate that comes
3. in thin bars (not sure of the weight but the bars are around 6" by 3" and maybe  ½" deep -- I use several) so that
4. the chocolate is sort of in layers in the cookie. Scharffen Berger, Green and Black's dark baking, and Callebaut
5. all work well. The best buy is from Trader Joe's though (sorry, Jen!!!) and it's their 1 lb. Plus bars which are
6. actually made by Callebaut. I use either the 72% (especially if making these cookies for adults) or the Dark
7. Chocolate (which is closer to semi-sweet and better for kids). But they also have the best price around on
8. Valhrona too.
9. In a medium bowl, whisk together flour, oats, baking soda, and salt. In a large mixing bowl, cream together
10. butter and sugars. Blend in vanilla and egg. Slowly add in the flour mixture until nearly combined. Add in
11. chocolate chips and nuts and stir by in by hand (this is normally Pat's job). It may seem like the dough won't
12. handle all the chocolate and nuts but it does. Drop by rounded tablespoonfuls onto baking sheets (I use one of
13. those cool cookie scoops that has the releasing mechanism) - you can put them very close together. Refrigerate
14. for 24 hours or longer (or freeze) then I take out only what I need for one pan at a time and bake on sheets.
15. These are great to have in the freezer to bake at a moment's notice - do not thaw or allow to come to room temp
16. before baking.
17. Line baking sheets with parchment paper or use silpat sheets and preheat over to 350o. Bake one sheet at a
18. time for 7 minutes, then turn sheets around 180o and bake for another 6 minutes until lightly browned. (Your
19. oven may run hotter or colder than mine but this it what works in mine). Remove pan from the oven but leave
20. cookies on the paper and slip the paper onto a wire rack to cool. Since there's so much chocolate in these and
21. it's in big pieces, if you take the cookies off the paper the chocolate will drip while it's still hot.

** Yield:
Makes 48 cookies.

** Credits:
- The Obsessive Compulsive Version
- (that I should be embarrassed about except for the fact that they are so darned good!)
- Nancy Burnett, November 2010
- Shared 26-April-2012. NOT FOR REDISTRIBUTION!
- date created: [2012-04-26 Thu]
