#+STARTUP: showeverything
* Classic Kouign-Amann (Breton Butter Cake)
** Ingredients:
*** Dough
- 2¼ cups (270g) King Arthur Unbleached All-Purpose Flour
- ¾ teaspoon (4g) salt
- ½ teaspoon (2g) instant yeast
- ¾ cup + 1 tablespoon (184g) water, at warm room temperature (75°F)
*** Butter block
- 12 tablespoons (170g) salted butter, cold
- 1 cup (198g) granulated sugar
*** Egg wash
- 1 large egg, lightly beaten with a pinch of salt
** Method:
1. *To make the dough*: Weigh your flour; or measure it by gently spooning it into a cup, then sweeping off any excess.
2. In a medium bowl, combine the flour, salt, and yeast. Add the water and, using your hands, mix and knead until you no longer see any dry flour and the dough is somewhat uniform, but still shaggy; it’s important not to overwork the dough (develop too much gluten) at this point.
3. Cover the bowl loosely and let the dough sit at warm room temperature (75°F) until puffy and about 1 1/2 times its original volume, 90 to 120 minutes.
4. To prepare the parchment packet for the butter block: Fold one short end of a 16" x 12" sheet of parchment toward the center to form a 12" square. Next, fold 5” of the opposite short side down to form a 7” x 12” rectangle. Finally, fold 2 1/2" of both 7” sides toward the center. This should result in a 7” square with folds (or flaps) on all four sides. Crease the folds crisply, then unfold. Set aside.
5. *To prepare the butter block*: Place the butter in the center of a clean work surface and gently tap it with a rolling pin until it’s just pliable; 8 to 10 taps should do it.
6. Using a dough scraper or dull knife, divide the butter into rough 1/2" pieces and place the pieces in a medium bowl with the sugar.
7. Using your hands and a pastry blender or fork, cut and knead the butter and sugar until it forms a uniform dough-like mixture.
8. Transfer the butter-sugar mixture to the center of the parchment square.
9. Refold the parchment to enclose the butter-sugar mixture then invert the packet so the flaps are face down. Roll gently until the butter block is evenly thick and fills the packet completely. Refrigerate until needed.
10. Toward the end of the dough’s rising time (about 15 minutes before it’s ready), remove the butter block from the refrigerator.
11. Place an oven rack in the upper-middle position and preheat the oven to 375°F.
12. *To laminate the dough*: Transfer the dough to a well-floured work surface. Flour the top of the dough liberally and roll it into a 16" x 8" oval with the short ends facing you; use a dry brush to remove any excess flour from the surface of the dough. Note: It's very important to flour the countertop and the exterior of the dough generously (more than you think!), to keep the dough from sticking or smearing. Just be sure to brush off any excess flour from the top of the dough before performing each of the three folding steps.
13. Unwrap the butter block (reserving the parchment) and place it on top of the dough, in the middle of the oval. Fold the two short ends over the butter square so that they meet in the middle. They should overlap slightly and also overhang the long edges so that the butter block is completely covered by dough.
14. Using the rolling pin, press down along the sides of the dough packet to seal the edges. Generously flour the top of the dough and your work surface again and rotate the dough 90°.
15. Holding the rolling pin parallel to the edge of the countertop, press straight down along the length of the dough from the back edge to the front edge to elongate the packet and seal the flaps fully, 15 to 20 presses.
16. Roll the dough away from and toward yourself to form an 18" x 8" rectangle, adding flour to both sides of the dough as needed to prevent sticking. If any large bubbles form in the dough, pop them gently with the tip of a paring knife.
17. With a dry brush, sweep off any excess flour and fold the dough into thirds like a business letter; you should have an 8” x 6" rectangle. Generously flour the top of the dough and your work surface again. Rotate the dough 90° in the same direction you rotated the dough the first time.
18. Repeat steps 15 through 17.
19. To shape the kouign-amann: Generously flour the top of the dough and your work surface, and roll the dough into a 14" square – if the dough is elastic and springs back as you roll it, just get it as close to a square as possible.
20. Brush off any excess flour then fold and join the corners of the square at the center to form a smaller 7” to 8” square. Gently push the new corners of the square into the center and gather the dough into a 7" disk.
21. Invert the dough disk onto the center of the reserved parchment. Flour the top of the dough lightly and roll it gently into a 9" round. Brush off any excess flour from the surface of the dough.
22. With a sharp paring knife or a straight-bladed lame, make a series of 1/4"-deep parallel cuts across the top of the dough, spacing them about 1" apart. Rotate the dough (or yourself) 30° and repeat the cuts to create an oblique diamond crosshatch pattern.
23. At evenly spaced intersections of the crosshatched pattern, use a toothpick or wooden skewer to poke 6 to 8 holes that go all the way down to the bottom of the kouign-amann.
24. Using the parchment as a sling, transfer the dough to a 9" round cake pan and gently press it into the corners of the pan.
25. Brush the top of the kouign-amann with the egg wash.
26. To bake the kouign-amann: Bake the kouign-amann until deep golden brown on top, 50 to 60 minutes.
27. Remove the kouign-amann from the oven and allow it to cool for about 1 hour before slicing and serving; it should still be a bit warm.
28. Storage information: Store leftovers, well wrapped, at room temperature for up to 24 hours.
** Credits:
- From https://www.kingarthurbaking.com/recipes/classic-kouign-amann-breton-butter-cake-recipe
- date created: [2022-01-30 Sun]
- [2022-01-30 Sun] Delicious!
