#+STARTUP: showeverything
* Classic Single Pie Dough
** Ingredients:
- 1¼ cups (150g | 6.25 ounces) all-purpose flour
- 1 Tbsp. sugar
- ½ tsp. salt
- 4 Tbsp. (23g) vegetable shortening, cut into ½-inch pieces and chilled
- 6 Tbsp. unsalted butter, cut into ¼-inch pieces and chilled
- About 3-4 tablespoons ice water, plus more as needed

** Method:
1. Process flour, sugar and salt in food processor until combined, about 5 seconds. Scatter shortening over top and process until mixture resembles coarse cornmeal, about 10 seconds. Scatter butter over top and pulse until mixture resembles coarse crumbs, about 10 pulses.

2. Transfer mixture to a large bowl. Sprinkle 3 tablespoons of ice water over mixture. Stir and press dough together, using stiff rubber spatula, until dough sticks together. If dough does not come together, stir in remaining ice water, ½ tablespoon at a time, until it does.

3. Divide dough into 2 even pieces. Turn each piece of dough onto a sheet of plastic wrap and flatten each into 4-inch disk. Wrap each piece tightly in plastic and refrigerate for 1 hour. Before rolling out dough, let it sit on counter to soften slightly, about 10 minutes. (Dough can be wrapped tightly in plastic and refrigerated for up to 2 days or frozen for up to 1 month. If frozen, let dough thaw completely on counter before rolling it out.)

** Yield
1 pie crust

** Credits:
From Cook's Illustrated Baking Book (page 372)
