#+STARTUP: showeverything
* Coconut Layer Cake
A Fantastic, Moist and Fluffy Coconut Cake Recipe
Fluffy layers of coconut cake, sweet, sticky 7-minute frosting and flakes of unsweetened coconut are piled high to create a dramatic, delicious Coconut Layer Cake that looks beautiful and tastes spectacular.
Prep time: 10 min.
Total time: 1 hr., plus cooling time
** Ingredients
*** Cake
- 1 cup (2 sticks) unsalted butter, softened, plus more for coating pans
- 3 cups cake flour, plus more for coating pans
- 1 tsp. baking powder
- ½ tsp. baking soda
- ½ tsp. salt
- 1¾ cups sugar
- 1 cup Coco GOYA® Cream of Coconut
- 4 large eggs, separated
- 1 tsp. GOYA® Vanilla Extract
- 1 cup GOYA® Coconut Milk
*** Frosting:
- 4 egg whites
- 1 cup sugar
- ⅛ tsp. salt
- 1 tsp. GOYA® Vanilla Extract
- 3 cups unsweetened flaked coconut
** Method:
*** Cake
1. Adjust oven racks to upper and lower thirds; heat oven to 350 degreesF. Butter three 9-inch-diameter cake pans. Line bottom of pans with parchment paper rounds; butter parchment paper. Dust bottom and sides of pans with flour, knocking out excess. Set pans in refrigerator.
2. In medium bowl, using whisk, whisk together flour, baking powder, baking soda and salt; set aside.
3. In large mixing bowl, using electric mixer, beat together sugar, butter and cream of coconut on medium-high speed until fluffy, about 2 minutes.
4. Beat in egg yolks, one at a time, and vanilla extract until well combined.
5. On low speed, beat in reserved flour mixture, scraping sides of bowl with spatula, until incorporated.
6. Beat in 1 cup coconut milk until just blended; set aside.
7. In separate medium mixing bowl, using clean dry beaters, beat egg whites until stiff but not dry. Using spatula, stir ⅓ beaten egg whites into cake batter until well blended. Gently fold in remaining beaten egg whites until well combined.
8. Divide cake batter evenly among prepared pans. Bake cakes, rotating after about 15 minutes, until tops are golden brown and cake tester inserted into center comes out clean, 30-32 minutes.
9. Cool cakes in pans on cooling racks about 15 minutes. Loosen cakes from sides of pans with thin knife, invert cakes onto racks. Cool cakes to room temperature; remove and discard parchment rounds.
*** Frosting:
1. Meanwhile, in heatproof bowl, whisk together egg whites, sugar and salt. Set bowl over saucepan containing about 1" simmering water (making sure bottom of bowl does not touch water). Whisk constantly until mixture is opaque and warm to the touch (about 120°F on quick-read thermometer), about 3 minutes. Remove bowl from heat.
2. Using electric mixer, beat egg whites on high speed until glossy white and sticky and mixture cools to about 80°F on quick-read thermometer, about 4 minutes. Reduce speed to medium and beat in vanilla; set aside.
*** Assemble the Cake:
1. Place one cooled cake round (top side-up) on cake plate.
2. Using off-set metal spatula, evenly spread with ½ cup frosting; sprinkle with ¾ cup flaked coconut.
3. Stack second cake layer (top side-up) on frosted cake.
4. Evenly spread cake with another ½ cup frosting; sprinkle with ¾ cup flaked coconut.
5. Stack last cake layer (top side-up) on frosted cake.
6. Evenly spread remaining frosting on top and sides of cake.
7. Sprinkle top of cake with about ¾ cup flaked coconut.
8. Using hands, press remaining coconut on sides of cake.
** Yield
8 servings
** Credits:
http://www.goya.com/english/recipes/print_recipe.html?recipeID=579&langID=0
[2016-09-01 Thu] Collected this recipe, but I haven't made it yet.
