#+STARTUP: showeverything
* Congo Bars
** Ingredients:
- 1½ cups unsweetened shredded coconut
- 1½ cups (7½ ounces) all-purpose flour
- 1 teaspoon baking powder
- ½ teaspoon salt
- 1½ cups packed (10½ ounces) light brown sugar
- 12 tablespoons unsalted butter, melted and cooled
- 2 large eggs
- 1½ teaspoons vanilla extract
- 1 cup pecans, toasted and coarsely chopped
- 1 cup (6 ounces) semisweet chocolate chips
** Method:
1. Adjust an oven rack to the middle position and heat oven to 350°
2. Make a foil sling for a 13 by 9-inch baking pan by folding 2 long sheets of aluminum foil; the first sheet should be 13 inches wide and the second sheet should be 9 inches wide. Lay sheets of foil in pan perpendicular to one another, with extra foil hanging over the edges of the pan. Push foil into corners and up the sides of the pan, smoothing foil flush to the pan. Grease foil and set pan aside.
3. Toast coconut on rimmed baking sheet, stirring two or three times, until lightly golden, 4 to 5 minutes. Let cool.
4. Whisk flour, baking powder and salt together in  medium bowl; set aside.
5. Whisk brown sugar and melted butter together in a medium bowl until combined.
6. Add eggs and vanilla and mix well.
7. Using rubber spatula, fold dry ingredients into egg mixture until just combined. Do not overmix.
8. Fold in nuts, chocolate chips and coconut.
9. Transfer batter to prepared pan, smoothing top with rubber spatula.
10. Bake until top is shiny and cracked and feels firm to the touch, 22 to 25 minutes.
11. Transfer pan to wire rack and let cool completely.
12. Remove from pan, using foil.
13. Cut into 2 by 1½ inch bars and serve.
** Credits:
- From Cook’s Illustrated Baking Book, page 240
- date created: [2021-05-27 Thu]
- [2021-05-25 Tue] Made for T’s 60^{th} birthday and they were well received!
