#+STARTUP: showeverything
* Double Lemon-Poppy Seed Bundt Cake
Serves: 16

** Ingredients:
- ¼ cup poppy seeds
- 1½ cups whole-wheat pastry flour
- 1 cup all-purpose flour
- 1½ teaspoons baking powder
- ½ teaspoon baking soda
- ¼ teaspoon salt
- 1 cup buttermilk or equivalent buttermilk powder
- ¼ cup canola oil
- 1 teaspoon vanilla extract
- 2 tablespoons freshly grated lemon zest
- 2 tablespoons lemon juice
- 2 large eggs, at room temperature
- 2 large egg whites, at room temperature
- 1¼ cups sugar
- ¾ cup confectioners' sugar, plus more for dusting
- 3 tablespoons lemon juice
- 1 tablespoon water

** Method:
1. Preheat oven to 350 degrees F. Coat a 10-inch (12-cup) Bundt pan, preferably nonstick, with cooking spray and dust with flour (or use cooking spray with flour).
2. Toast poppy seeds in a small dry skillet over medium heat, stirring constantly, until fragrant, 3 to 4 minutes. Transfer to a plate to cool.
3. Whisk whole-wheat flour, all-purpose flour, baking powder, baking soda, salt and the poppy seeds in a medium bowl. Combine buttermilk, oil, vanilla, lemon zest and lemon juice in a glass measuring cup.
4. Beat eggs, egg whites and sugar in a large bowl with an electric mixer on high speed until thickened and pale, about 5 minutes.
5. Fold the dry ingredients into the egg mixture with a rubber spatula, a third at a time, alternating with 2 additions of the buttermilk mixture. Scrape the batter into the prepared pan, spreading evenly.
6. Bake the cake until the top springs back when touched lightly and a toothpick inserted in the center comes out clean, 35 to 40 minutes. Let cool in the pan on a wire rack for 5 minutes. Loosen the edges and turn the cake out onto the rack.
7. Meanwhile, prepare glaze: Sift ¾ cup confectioners' sugar into a small bowl; mix with lemon juice and water to create a thin glaze. Poke 1-inch-deep holes all over the cake with a skewer. Coat the warm cake with the glaze using a pastry brush. Let cool completely. To serve, set the cake on a serving plate and dust with confectioners' sugar.

** Yield: 16 servings

** Credits:
- Per Serving
    - Calories: 201 kcal
    - Carbohydrates: 35 g
    - Dietary Fiber: 1 g
    - Fat: 5 g
    - Protein: 4 g
    - Sugars: 22 g
- http://food.yahoo.com/recipes/eatingwell/285/double-lemon-poppy-seed-bundt-cake/print
- 23 May 2009
- date created: [2009-05-26 Tue]
