#+STARTUP: showeverything
* Fresh Pineapple Upside Down Cake
** Ingredients:
- 12 tablespoons (170 grams) unsalted butter, softened (1½  sticks)
- ½ cup (100 grams) lightly packed brown sugar
- ½ teaspoon ground cinnamon
- 8 ounces (225 grams) fresh pineapple, cut into ½-inch-thick wedges (about ¼ pineapple)
- 1 cup (200 grams) granulated sugar
- 2 teaspoons lime or lemon zest
- 2 large eggs, separated
- 1 teaspoon vanilla extract
- 2 teaspoons baking powder
- ¼ teaspoon fine sea salt
- 1½  cups (195 grams) all-purpose flour
- ½ cup (125 grams) sour cream or plain yogurt
** Method:
1. Position an oven rack in the lower third of the oven and heat oven to 350° Fahrenheit.
2. Using the back of a spoon, spread 4 tablespoons of the butter over the bottom of a 9-inch cake pan. Scatter the brown sugar and cinnamon evenly over butter. Arrange the pineapple wedges in one even layer over the butter and sugar.
3. In a large bowl, beat the remaining 8 tablespoons of butter, granulated sugar and zest with an electric mixer on high speed until light and fluffy, 2 to 3 minutes. Add the egg yolks and vanilla and beat until smooth.
4. In a medium bowl, whisk or sift the flour with the baking powder and salt. Mix in a third of the flour mixture until only a few streaks of flour remain then mix in the remaining flour. Add the egg whites and sour cream and mix just until smooth.
5. Spoon cake batter on top of the pineapple and spread into an even layer. Bake for 35 to 40 minutes or until a toothpick inserted in the center of the cake comes out clean.
6. Cool cake in the pan for 5 minutes then run a knife around the edges and invert it onto a plate to cool. If some pineapple slices stick to the pan, use a spatula to transfer them back on top of the cake and spread a little of the gooey brown sugar sauce over them to cover it up.
7. Serve warm or at room temperature. Refrigerate leftover cake up to 3 days. You can also rewarm slices in the microwave for about 10 seconds.
** Credits:
- From https://www.inspiredtaste.net/23363/fresh-pineapple-upside-down-cake-recipe/#itr-recipe-23363
- date created: [2021-06-14 Mon]
- [2021-06-13 Sun] Made for TC, Greg, MaryAnn, Josh and Jeff. Very light and tasty.
