#+STARTUP: showeverything
* Lemon Cornmeal Cake with Lemon Glaze and Crushed-Blueberry Sauce

** Ingredients:
- 1½ cups (packed) powdered sugar, sifted
- 2 tablespoons (or more) fresh lemon Juice
- 1½ cups all purpose flour
- ⅓ cup yellow cornmeal
- ¾ cup sugar
- 3½ teaspoons baking powder
- ½ teaspoon salt
- 1 cup buttermilk
- 2 large eggs
- 1 tablespoon finely grated lemon peel
- ¾ teaspoon vanilla extract
- ½ cup (1 stick) unsalted butter, melted, cooled
- Crushed-Blueberry Sauce

** Method:

1) For glaze: Combine powdered sugar and 2 tablespoons lemon juice in small bowl. Stir with spoon until smooth and paste-like, adding more lemon juice by ½ teaspoonfuls if glaze is too thick to spread. Set aside.

2) For cake: Position rack in center of oven and preheat to 350 degrees F. Butter 9-inch-diameter cake pan with 2-inch-high sides; line bottom with parchment. Combine flour, cornmeal, sugar, baking powder, and salt in large bowl; whisk to blend. Whisk buttermilk, eggs, lemon peel, and vanilla in small bowl. Pour buttermilk mixture and melted butter into flour mixture. Using rubber spatula, gently fold liquids into flour mixture until just blended (do not stir). Scrape batter into pan; spread evenly.
3) Bake cake until tester inserted into center comes out clean and cake pulls away from sides of pan, about 30 minutes.
4) Immediately run knife around sides of cake. Place rack atop cake in pan. Using oven mitts, hold pan and rack firmly together and invert cake onto rack. Remove pan from cake. Place another rack on bottom of cake; invert 1 more time so that cake is top side up. Stir glaze until blended. While cake is still very hot, drop glaze by tablespoonfuls onto cake; spread to within ½ inch of edge (some glaze may drip down sides of cake). Cool completely. Serve with Crushed-Blueberry Sauce.

** Credits:
- Bon Appetit
- April 2009
- by Abigail Johnson Dodge
- [TC made on 29-June-12. Yum! (Don't forget the baking powder!)]
- You can view the complete recipe online at: http://www.epicurious.com/recipes/food/views/Lemon-Cornmeal-Cake-with-Lemon-Glaze-and-Crushed-Blueberry-Sauce-352048?mbid=ipapp
- date created: [2012-07-02 Mon]
