#+STARTUP: showeverything
* Lemon Poppyseed Cake
** Ingredients:
- 2 Tbsp plus 1 ¼ cups sugar
- 2 cups all purpose flour
- 3 Tbsp poppy seeds
- 2 tsp baking powder
- 1 tsp baking soda
- ½ tsp salt
- 1 large egg
- 1 cup buttermilk
- 3 Tbsp veg oil
- 2 tsp freshly grated lemon zest
- 1 tsp vanilla extract
** Method:
1. Preheat oven to 350°.
2. Lightly oil a tube or bundt pan.
3. Sprinkle pan with 2 Tbsp sugar, tapping out excess.
4. In a large bowl, mix flour, poppy seeds, baking powder, baking soda, and salt,
5. In another bowl, whisk egg until frothy.
6. Add in remaining 1 and ¼ cups sugar, buttermilk, oil, lemon zest, and vanilla.
7. Gradually add wet ingredients to dry ingredients, mixing until just moistened.
8. Pour batter into prepared pan.
9. Bake cake 30-40 minutes, or until top springs back when touched lightly and a skewer inserted in the center comes out clean.
10. Immediately loosen edges and invert onto a wire rack.
11. Let cool completely.
12. Once cooled, put about a cup of confectioner’s sugar into a bowl and mix in enough of some kind of liquid to make a pourable frosting; drizzle over cake.

** Substitutions:
- One cup soy milk with a healthy dollop of apple cider vinegar (to make buttermilk; do this first so the milk has time to curdle; also, soy works better than oat milk).
- One prune puree in place of the egg.
** Tags:
IsVegan
** Credits:
- From Diana Norcross
- date created: [2022-08-27 Sat]
