#+STARTUP: showeverything
* Mexican Chocolate Pots de Creme
** Ingredients:
- 10 ounces unsweetened chocolate (100% cacao)
- one 15-ounce can coconut cream
- ¼ cup maple syrup
- ½ teaspoon vanilla extract
- ¼ teaspoon sea salt
- ¼ teaspoon ground chipotle
- ½ teaspoon ground cinnamon
- 2 tablespoons pistachios very finely chopped
- ¼ cup coconut whipped cream (optional)

** Method:
1. Melt the chocolate over a double boiler or in 30 second increments in the microwave.
2. In a high speed blender, combine all remaining ingredients except pistachios and blend until smooth.
3. With the motor running on low speed, gradually pour in the melted chocolate.
4. Cover and increase speed to medium-high, continuing to blend until ingredients are fully combined and mixture is smooth.
5. Pour into jars or ramekins and refrigerate until chilled, about 4 hours.
#+begin_note
The chocolate pots will be rich and thick if consumed cold straight from the refrigerator. If a lighter texture is desired, allow pots to sit at room temperature for about an hour before enjoying. Just before serving, top with chopped pistachio and coconut whipped cream, if using.
#+end_note

** Credits:
- From https://lepetiteats.com/mexican-chocolate-pots-de-creme-vegan/#wprm-recipe-container-5765
- date created: [2024-09-12 Thu]
- [2024-09-12 Thu] Made for Vegan supper club. Very tasty, but using the NutriBullet blender, I think I may have over whipped the mixture: it got extremely stiff, even when it sat out of the refrigerator for a while. Suggestion: use a conventional blender.
