#+STARTUP: showeverything
* Peach Cobbler Coffee Cake
** Ingredients:
*** Coffee Cake
- 2 c. all purpose flour
- 2½ tsp. baking powder
- 1 tsp. cinnamon
- ¼ c. milk
- ¾ c. brown sugar
- ½ c. sour cream
- ¼ c. butter softened
- 1 egg
- 1 tsp. vanilla
- 2 c. sliced peaches
*** Crumb Topping
- 1 c. brown sugar
- ⅔ c. flour
- 6 Tbsp. softened butter
*** Glaze
- ½ c. powdered sugar
- 2½ tsp. milk
- ⅛ tsp. cinnamon
** Method:
1. In a medium bowl, combine 2 c. flour, baking powder and cinnamon. Set aside.
2. Beat ¼ c. milk, ¾ c. brown sugar, ½ c. sour cream, ¼ c. butter, egg, and vanilla until creamy. Add dry ingredients and mix just until blended.
3. Fold in peaches.
4. Make Crumble Topping: Combine 1 c. brown sugar, ⅔ c. flour in a bowl. Cut in 6 Tbsp. softened butter until mixture is crumbly.
5. Spoon batter into a 10 inch springform pan and sprinkle with crumble topping.
6. Bake at 350 degrees for 50-55 minutes or until center is set and top is golden brown.
7. Combine ingredients for glaze and drizzle over baked coffee cake.
** Credits:
- From https://www.lemontreedwelling.com/peach-cobbler-coffee-cake/
- date created: [2020-06-20 Sat]
- [2020-06-20 Sat] Made for Penny and Gary. Moist and tasty. I might want to hold back a bit on the sugar.
