#+STARTUP: showeverything
* Peach Melba Cream Cake

** Ingredients:
*** For the cake:
- ¾ cup softened, unsalted butter plus more for greasing the pans
- 1 cup sugar
- ½ cup brown sugar
- 3 eggs
- 1½ teaspoons pure vanilla extract
- finely grated zest of 1 lemon
- ¼ cup fresh lemon juice
- 2½ cups all purpose flour
- 1½ teaspoons baking soda
- ½ teaspoon salt
- 1½ cups buttermilk
- 4 pounds ripe peaches
- 2 tablespoons fresh lemon juice
- 2½ tablespoons sugar
- 2 cups heavy cream
- 1½ teaspoons pure vanilla extract
*** Raspberry Melba Sauce
- 2 cups raspberries
- ½ cup confectioners' sugar
- 1 tablespoon fresh lemon juice
- ¼ cup apple juice

** Method:
1. Raspberry Melba Sauce (see recipe)
2. Preheat the oven to 350 degrees F. Butter and flour two 9-inch cake pans (line with buttered and floured wax paper for easier removal, optional).
3. Cream the ¾ cup butter and sugars in a mixing bowl. Addd the eggs, one at a time, beating well after each adition. Beat in the vanilla, lemon zest and juice.
4. Sift together the flour, baking soda and salt; add to mixture in the bowl, alternating with buttermilk, to make batter.
5. Scrape batter into the pans. Bake until a toothpick inserted in the center comes out clean, about 35 to 40 minutes. Cool the cakes in their pans on a rack for 15 minutes, then turn them out onto the rack, peel off wax paper and cool completely.
6. Shortly before serving, peel, pit and slice the peaches. Toss with lemon juice and 1 tablespoon sugar; set aside for 15 minutes.
7. Whip the cream with the vanilla and the remaining 1½ tablespoons of sugar until it holds soft peaks.
8. Place on cake on a serving platter. Spread with half the cream, then half the peaches. Cover with second cake and top with remaining peaches. Top with a dollop of cream and, if desired, a mint sprig. Serve immediately, with the Raspberry Melba Sauce on the side or drizzled over the cake.
10. Per serving: 651 calories, 82g carbs, 9g protein, 34 g fat, 167 mg cholesterol.
*** Raspberry Melba Sauce
1. Puree all ingredients, the pass through a strainer to remove the seeds.
2. Makes 2 cups.
3. Per 2 tablespoons: 61 calories, 15g carbohydrates, 0g protein, 0g fat, 0mg cholesterol.
** Yield
10 servings
** Credits:
- date created: [2007-06-27 Wed]
