#+STARTUP: showeverything
* Peanut Butter Oat Energy Cups
** Ingredients:
- 1⅔ cups old-fashioned rolled oats
- ¾ cup crunchy natural peanut butter
- ½ cup unsweetened almond milk
- 3 tablespoons chia seeds
- 2 teaspoons honey
- 1½ teaspoons vanilla extract
- ¼ teaspoon salt
- ½ cup dark chocolate chips (53% cacao)
- 1 tablespoon unrefined coconut oil
- ¾ teaspoon flaky sea salt
** Method:
1. Line the cups of a 24-cup mini muffin tin with silicone or paper liners.
2. Combine 1⅔ cups oats, ¾ cup peanut butter, ½ cup almond milk, 3 tablespoons chia seeds, 2 teaspoons honey, 1½ teaspoons vanilla and ¼ teaspoon salt in a large bowl; stir to mix well.
3. Divide the mixture among the prepared cups, about 1 heaping tablespoon each; firmly press the mixture into the cup bottoms.
4. Combine ½ cup chocolate chips and 1 tablespoon coconut oil in a small microwave-safe bowl.
5. Microwave on High until the oil is melted and the chocolate chips have softened, 45 to 60 seconds.
6. Stir until the chocolate chips are completely melted and incorporated into the oil.
7. Spoon a scant teaspoon of the melted chocolate mixture over the oat mixture in each cup, spreading to cover the entire surface.
8. Refrigerate, uncovered, until the chocolate layer is beginning to set (the surface will begin to lose its shine and become dull), 10 to 15 minutes.
9. Sprinkle with ¾ teaspoon flaky salt; refrigerate, uncovered, until chilled and the layers are fully set, about 1 hour.
** Tags:
IsVegan
** Credits:
- From https://www.eatingwell.com/peanut-butter-oat-energy-cups-8741694
- date created: [2024-12-13 Fri]
- [2024-12-13 Fri] I used a typically sized cupcake tin and doubled the filling in each one. They were good, although T wasn't thrilled.
