#+STARTUP: showeverything
* Ricotta Cookies
Italian Ricotta Cookies recipe are incredibly soft with a tender texture, delicious, and absolutely perfect for any holiday, not just for Christmas.
** Ingredients:
*** Cookies
- 1 cup unsalted butter (2 sticks), softened to room temperature
- 2 cups (380g) sugar
- 2 eggs
- 15 ounces full-fat Ricotta cheese
- 1 teaspoon vanilla extract
- 2 tablespoons orange or lemon zest
- 4½ cups (540 g) all purpose flour
- 1 teaspoon baking powder
- 1 teaspoon baking soda
- ½ teaspoon salt
*** Glaze
- ¼ cup butter, melted
- 2 cups powdered sugar
- 3 tablespoons heavy cream
- 1 teaspoon vanilla extract
** Method:
*** Cookies
1. Preheat oven to 350°.
2. In the bowl of an electric mixer, cream together butter and sugar at medium speed.
3. Add eggs and beat those in as well.
4. Add ricotta cheese and mix until smooth and fully incorporated.
5. Add vanilla extract and citrus zest and blend.
6. In a separate medium bowl, whisk together flour with baking powder, baking soda and salt.
7. Gradually add the flour mixture to the wet ingredients (one cup at a time) on low speed until a dough is formed.
8. Drop the dough by heaping tablespoons onto an ungreased baking sheet (they will puff up while baking).
9. Bake for 10-12 minutes (this will depend on size of cookies and your oven so keep an eye on them). Cookies will just start to get lightly golden around the bottom edges. You want them to remain soft and not get too over-baked.
10. Remove from baking sheet and place on a cooling rack to cool completely before putting on the glaze.
11. Spoon glaze onto cookies, add sprinkles of your choosing before glaze dries, and allow it to fully set before storing.
*** Glaze
1. Mix together melted butter, powdered sugar, heavy cream and vanilla extract in a bowl until smooth and no lumps remain.
2. Add additional splashes of milk or cream to get the desired consistency.
   #+begin_note
   You don't want it to be so thick that it's not spreadable, but also not too runny.
   #+end_note
** Tags
Favorite
** Yield:
Serves: about 4 dozen
** Credits:
- https://wishesndishes.com/italian-ricotta-cookies/
- Prep time:  20 minutes
- Cook time:  10 minutes
- Total time: 30 minutes
- date created: [2019-12-07 Sat]
