#+STARTUP: showeverything
* Ricotta Cookies
Italian Ricotta Cookies recipe are incredibly soft with a tender texture, delicious, and absolutely perfect for any holiday, not just for Christmas.
** Ingredients:
*** Cookies
- 1 cup unsalted butter (2 sticks), softened to room temperature
- 2 cups sugar
- 2 eggs
- 15 ounces full-fat Ricotta cheese
- 1 teaspoon vanilla extract
- 2 tablespoons orange or lemon zest
- 4½ cups all purpose flour
- 1 teaspoon baking powder
- 1 teaspoon baking soda
- ½ teaspoon salt
*** Glaze
- ¼ cup butter, melted
- 2 cups powdered sugar
- 3 tablespoons heavy cream
- 1 teaspoon vanilla extract
** Method:
*** Cookies
1. Preheat oven to 350 degrees.
2. In the bowl of an electric mixer, cream together butter, sugar medium speed.
3. Add eggs and beat those in, as well.
4. Add Ricotta cheese and mix until smooth and fully incorporated. Add vanilla extract and orange zest and blend.
5. In a separate medium bowl, whisk together flour with baking powder, baking soda and salt.
6. Gradually add the flour mixture to the wet ingredients (one cup at a time) on low speed until a dough is formed.
7. Drop the dough by heaping tablespoons onto an ungreased baking sheet (they will puff up while baking).
8. Bake for 10-12 minutes (this will depend on size of cookies and your oven so keep an eye on them). Cookies will just be started to get lightly golden around the bottom edges. You want them to remain soft and not get too over-baked.
9. Remove from baking sheet and place on a cooling rack to cool completely before putting on the glaze.
10. Spoon glaze onto cookies, add sprinkles of your choosing before glaze dries, and allow it to fully set before storing.
*** Glaze
1. Mix together melted butter, powdered sugar, heavy cream, vanilla extract in a bowl until smooth and no lumps remain.
2. Add additional splashes of milk or cream to get the desired consistency.
3. You don't want it to be so thick that it's not spreadable, but also not too runny.
** Tags
Favorite
** Yield: 
Serves: about 4 dozen
** Credits:
- https://wishesndishes.com/italian-ricotta-cookies/
- Prep time:  20 mins
- Cook time:  10 mins
- Total time: 30 mins
- date created: [2019-12-07 Sat]
