#+STARTUP: showeverything
* Spoon Cookies
From Gourmet, Dec. 2005
Makes 25-30 sandwich cookies

** Ingredients:
- 2 sticks (1 cup) cold unsalted butter, cut into pieces
- ¾ cup (148.5 grams) sugar
- 2 tsp vanilla
- 2 cups (240 grams) flour
- 1 tsp baking soda
- ⅛ tsp salt, slightly rounded
- ½ cup fruit preserves (your choice: cherry and strawberry are good)

** Method:
1. Fill kitchen sink with about 2 inches of cold water. Melt butter in a 2- to 3-quart heavy saucepan over moderate heat and cook, stirring occasionally, until butter turns golden with a nutlike fragrance and flecks on bottom of pan turn a rich caramel brown, 10 to 12 minutes. (Butter will initially foam, then dissipate. A thicker foam will appear and cover the surface just before butter begins to brown; stir more frequently toward end of cooking.) Place pan in sink to stop cooking, then cool, stirring frequently, until butter starts to look opaque, about 4 minutes. Remove pan from sink and stir in sugar and vanilla.

2. Whisk together flour, salt, and baking soda and stir into butter mixture until a dough forms. Shape into a ball, wrap with plastic wrap, and let stand at cool room temperature 1 to 2 hours (to allow flavors to develop).

3. Put oven rack in middle position and preheat oven to 325 degrees F.

4. Press a piece of dough into bowl of teaspoon (table type teaspoon, not one for measuring), flattening top, then slide out and place, flat side down, on an ungreased baking sheet. (Dough will feel crumbly, but will become cohesive when pressed.) Continue forming cookies and arranging on sheet. Bake cookies until just pale golden, 8 to 15 minutes. Cool cookies on sheet on a rack 5 minutes, then transfer cookies to rack and cool completely, about 30 minutes. Cookies are very delicate when hot.

5. While cookies cool, heat preserves in a small saucepan over low heat until just runny, then pour through a sieve into a small bowl, pressing hard on solids, and cool completely. Spread the flat side of a cookie with a thin layer of preserves. Sandwich with flat side of another cookie. Continue with remaining cookies and preserves, then let stand until set, about 45 minutes. Transfer cookies to an airtight contain and (this is the hard part) WAIT 2 DAYS BEFORE EATING.

6. Dough can be made 12 hours before baking and chilled, covered. Bring to room temperature to soften slightly before forming cookies, about 30 minutes. Cookies keep in an airtight container at room temperature 2 weeks.

** Credits:
- courtesy of Nancy Burnett 3-Feb-06
- See http://www.epicurious.com/recipes/food/views/spoon-cookies-233297
- I made these [2016-12-15 Thu] and cooked them for 14 minutes. I had a bit of trouble forming the cookies, but even some of the well-formed ones wound up spreading out in the oven. Filled variously with strawberry, fig and mixed berries preserves.
- date created: [2007-06-27 Wed]
