#+STARTUP: showeverything
* Super Moist Chocolate Cake
** Ingredients:
- 2 cups (500 mL) all-purpose flour
- ⅔ cup (150 mL) unsweetened cocoa powder
- 1 ¼ tsp. (6 mL) baking soda
- ¼ tsp. (1 mL) baking powder
- 3 eggs
- 1 ⅔ cups (400 mL) sugar
- 1 tsp. (5 mL) vanilla extract
- 1 cup (250 mL) Hellmann's® Real Mayonnaise
- 1 ⅓ cups (325 mL) water
** Method:
1. Preheat oven to 350°F (180°C).
2. Grease and lightly flour two 9-inch/ 23 cm/ 1.5 L, round cake pans*; set aside.
3. Combine flour, cocoa, baking soda and baking powder in medium bowl; set aside.
4. Beat eggs, sugar and vanilla in large bowl with electric mixer at high speed until light and fluffy, about 3 minutes.
5. Beat in Hellmann's® Real Mayonnaise at low speed until blended.
6. Alternately beat in flour mixture with water, beginning and ending with flour mixture.
7. Pour into prepared pans.
8. Bake 30 minutes or until toothpick inserted in centers comes out clean.
9. Cool 10 minutes on wire racks; remove from pans and cool completely.
10. Frost with your favorite frosting or generously sprinkle with confectioners sugar.

\star{} Or, prepare cake mix as above in 13 x 9-inch (33 x 23-cm / 3.5 L) baking pan and bake 40 minutes or until toothpick inserted in center comes out clean.

For chocolate frosting: icing sugar and a softened stick of Earth Balance, cocoa powder or melted dark baking chocolate, oat milk, vanilla and butter
essence, mix and taste :).

** Substitutions
- Substitute “Follow Your Heart Vegan Eggs” for the eggs
- Substitute Hellman’s vegan mayo/salad dressing, which is on the shelf with all the other mayos, not refrigerated.
** Tags
IsVegan
** Credits:
- From https://www.hellmanns.com/ca/en/recipes/super-moist-chocolate-cake.html via Alastair Norcross
- date created: [2022-08-27 Sat]
