#+STARTUP: showeverything
* Vegan Peanut Butter Cookies
** Ingredients:
- 1 cup natural peanut butter (270g), creamy or crunchy (or almond butter)
- 1 cup coconut sugar or pure cane sugar (192g)
- 6 tablespoons almond milk, room temp
- 2 teaspoons vanilla extract
- 1 cup flour (120g), spelt, unbleached all-purpose, almond flour, or 1-1 gluten-free blend
- 1 teaspoon baking soda
- generous pinch of mineral salt (only use if nut butter is unsalted)
  #+begin_note
  Reduce the sugar to ¾ cup for a less sweet cookie. It’s just as delicious!
  #+end_note
** Method:
1. Preheat the oven to 350°F.
2. Line a cookie sheet with silicone mat, parchment paper or leave ungreased.
3. In a large bowl, add the peanut butter and sugar and mix until creamy.
4. Stir in the almond milk and vanilla.
5. Next, add the flour, baking soda, and salt, mix to combine. The dough will be tough to stir, using your hands to mix it together will be easier.
6. Using a 1½ tablespoon scooper, scoop out the dough and roll into balls, about 1¼ inch.
7. Place the balls of dough about 2½ inches apart on a baking sheet.
8. Using the back of a fork, flatten in a crisscross pattern.
9. Optionally, sprinkle with sugar or coarse salt.
10. Place in the oven and bake for 10 – 13 minutes (13 minutes will yield a crispier cookie that’s tender inside).
11. Let cool a few minutes, transfer cookies to wire rack and repeat with remaining dough.
** Yield
Makes 20 – 24 cookies.
** Tags
IsVegan
** Credits:
- From https://simple-veganista.com/vegan-peanut-butter-cookies/print/25652/
- date created: [2022-08-01 Mon]
- [2022-08-01 Mon] Made for Pickleball picnic. T says these are a keeper! They are good, but perhaps a tad too much vanilla.
