#+STARTUP: showeverything
* Vegan Apple Pie Bars
** Ingredients:
*** For the crust and the crumb
- ¾ cup (93.75 g) all purpose flour
- ¼ teaspoon salt
- 3-4 tablespoons brown sugar
- ¼ teaspoon baking powder
- 1 teaspoon cinnamon
- ½ teaspoon vanilla extract optional
- ⅓ cup (85 g) plus 1-2 tablespoons smooth almond butter
- 1 tbsp maple syrup
*** For the apple layer
- 1 large honey crisp apple thinly sliced or about 2 cups of thinly sliced apples or you can chop them into small pieces instead
- 2 tablespoons maple syrup
- 1 tablespoon brown sugar
- zest of ½ lemon
- 1 teaspoon cornstarch
- ½ teaspoon cinnamon
** Method:
*** For the crust
1. In a bowl, add the flour, salt, baking powder, and sugar and mix really well.
2. Then warm up ⅓ cup of the almond butter and add it along with maple syrup, vanilla extract. Then mix using fork or your hands until the mixture is somewhere crumbly and when you press the mixture in your hand, it kind of stays together a little bit.
3. If it is too floury, then add in 1-2 tablespoons more almond butter. You can also use 1-2 teaspoons of non-dairy milk in this crust mixture if it's too crumbly.
4. Transfer half of this mixture to a parchment-lined 9 x 5 inch baking dish or loaf pan.
5. Press it down until even. Once pressed, set this loaf pan aside.
*** Make the filling
1. In a bowl, add the apple, maple syrup, sugar, zest of a lemon, cornstarch, and cinnamon and toss well to coat.
2. Transfer these apples to the crust and even it out so that there are no pockets of space between apples.
3. To the rest of the crust mixture, add in 2-4 teaspoons of maple syrup and then add more as needed. Mix until the mixture becomes like a muffin crumb topping kind of mixture.
4. Then top the apples with this mixture and spread evenly. Bake at 365°  Fahrenheit (185° C) for a total of 40 to 45 minutes. Top the loaf pan with parchment after the first 25 minutes so that the crumb does not brown too much.
5. Then remove from the oven. Let it cool in the pan for 10 minutes then remove from the pan. Slice and serve.
#+begin_note
For the optional icing, take a ¼ cup of powdered sugar. Add in a teaspoon or more water or non-dairy milk and mix in until icing consistency then drizzle all over.
#+end_note
#+begin_note
Nutfree: use 3 tablespoons softened butter, 2 teaspoons flax meal mixed in 1.5 tablespoons water and mix in. Of the mix is not sticking together, add maple syrup 1 teaspoon at a time.
#+end_note
#+begin_note
Gluten-free: Use a mix of ⅓ cup almond flour, ⅓ cup oat flour(or a gf blend), 3 tablespoons potato starch (or other starch) instead of all purpose flour
#+end_note
** Credits:
- From https://www.veganricha.com/vegan-apple-pie-bars/#recipe
- date created: [2023-09-15 Fri]
- [2023-08-24 Thu] Made for Wine Tasting party. Really tasty.
