#+STARTUP: showeverything
* Vegan Pumpkin Bread
** Ingredients:
*** Wet Ingredients
- 1 tablespoon ground flax seeds
- 2.5 tablespoons water
- 15 ounces canned pumpkin puree
- 1 ¼ cups brown sugar
- ½ cup canola oil
- ¼ cup soy milk
*** Dry Ingredients
- 1 ¾ cups (210g) all purpose flour
- 1 teaspoon baking soda
- ½ teaspoon baking powder
- ½ teaspoon salt
- 2 teaspoons ground cinnamon
- ¼ teaspoon ground nutmeg
- ¼ teaspoon ground cloves
*** Topping
- ½ cup pepitas
** Method:
1. Preheat the oven to 350 degrees F and grease a loaf pan.
2. In a small bowl, combine the ground flax seed and water. Set aside to thicken; this is your flax egg.
3. In a large bowl, whisk together the pumpkin, brown sugar, canola oil, flax egg and soy milk until smooth.
4. Add the flour, then sprinkle the baking soda, baking powder, salt, cinnamon, nutmeg and cloves on top of the flour. Stir with a large spoon or spatula, gently, until just combined. Do not over mix.
5. Pour into the prepared pan and sprinkle the pepitas on top. Bake for about 1 hour and 15 minutes, until a toothpick inserted in the center comes out clean.
6. Let it cool in the pan for 10-15 minutes, then transfer the loaf to a cooling rack. Slice carefully right away, or let cool completely for easier slicing and serving.
** Notes
- For oil free, you can substitute applesauce for the oil, but the loaf will not be as moist or fluffy. It tends to make a denser, gummier loaf. You can also use coconut oil or another oil if you'd like.
- Feel free to sub any non-dairy milk for soy milk.
- For whole grain, you may sub whole wheat flour for the white flour, it just won't be as light and fluffy. I haven't tried this gluten free, but it may work with a gluten free mix. Do not sub with almond or coconut flour, it will not work!
- Other optional add ins: I like the loaf as is, but feel free to mix in chocolate chips, walnuts, pecans, raisins, currants, cranberries or even shredded coconut.
** Tags:
IsVegan
** Credits:
- From https://www.noracooks.com/wprm_print/5674
- date created: [2023-01-21 Sat]
