#+STARTUP: showeverything
* Yogurt Cake
** Ingredients:
- Butter, for greasing the pan
- 4 large eggs, separated, at room temperature
- ½ cup (100 grams) granulated sugar
- 3 tablespoons all-purpose flour
- 1 ⅔ cups (400 grams) whole-milk Greek yogurt
- 1 lemon, zested and juiced
- Pinch of salt (optional)
** Method:
1. Heat oven to 350 degrees and butter an 8- or 9-inch springform pan.
2. Using an electric hand mixer or a standing electric mixer fitted with the whisk attachment, beat egg whites on medium-low until the mixture looks frothy, 1 to 2 minutes.
3. Slowly start to increase the speed to medium-high.
4. Continue to beat the egg whites until soft peaks form, about 3 minutes.
5. Set aside.
6. In a separate bowl but using the same mixer, combine yolks and sugar (no need to wash beaters after the egg white).
7. Beat yolks on medium-high until the mixture is very pale and fluffy, about 3 minutes.
8. Reduce speed to medium and gradually beat in flour, yogurt, lemon zest and juice, and salt until fully incorporated.
9. Gently fold half of the egg whites into the yolk-yogurt mixture until only a few streaks remain.
10. Fold in the remaining whites, scraping the bottom and sides of the bowl, until the batter is evenly mixed, light and smooth.
11. Scrape the batter into prepared pan and smooth into an even layer.
12. Bake until the top is speckled with golden brown and puffed, 40 to 55 minutes. (The 8-inch pan will take longer to bake through.)
13. Transfer the pan to a wire rack and let cake cool before cutting.
14. Serve warm or cold.
** Yield:
8 servings
** Credits:
- From the [[https://cooking.nytimes.com/recipes/1022688-yogurt-cake?algo=identity&fellback=true&imp_id=8624192869338109&req_id=2342135125455672&surface=cooking-search-web&variant=0_relevance_reranking][New York Times]]
- date created: [2025-03-03 Mon]
