#+STARTUP: showeverything
* Cauliflower Popcorn
** Ingredients:
- 2 pounds cauliflower, cut into ½- to 1-inch pieces and florets
- ⅓ cup plus 1 tablespoon extra-virgin olive oil (or melted ghee)
- ¼ cup nutritional yeast, divided
- ¼ teaspoon red-pepper flakes or pinch of ground cayenne
- Kosher salt and black pepper
- ½ cup panko bread crumbs
** Method:
1. Heat the oven to 450°.
2. On a sheet pan, toss the cauliflower with ⅓ cup olive oil, 1 tablespoon nutritional yeast and the red-pepper flakes.
3. Season generously with salt and pepper, then toss well to evenly distribute.
4. Spread in an even layer and roast for 20 minutes, until the cauliflower is crisp-tender and starting to brown at the edges.
5. Meanwhile, in a small bowl, stir together the panko, remaining 3 tablespoons nutritional yeast and remaining tablespoon olive oil.
6. Season with salt and pepper, and stir with a fork until evenly combined.
7. When the 20 minutes are up, stir the cauliflower, spread it into an even layer and sprinkle with the panko mixture.
8. Roast until the panko is toasted, 10 to 12 minutes.
** Yield
4 servings
** Credits:
- From https://cooking.nytimes.com/recipes/1022966-cauliflower-popcorn
- date created: [2023-02-20 Mon]
- [2023-02-18 Sat] Made for T, Greg and Mary Ann. They said they liked it a lot.
