#+STARTUP: showeverything
* Gougères
** Ingredients:
- ½ cup whole milk
- ½ cup water
- 8 tablespoons (1 stick) unsalted butter, cut into 4 pieces
- ½ teaspoon salt
- 1 cup all-purpose flour
- 5 large eggs, at room temperature
- 1 ½ cups coarsely grated cheese, such as Gruyère or cheddar (about 6 ounces; see above)

** Method:
1. Position the racks to divide the oven into thirds and preheat the oven to 425 degrees F.
2. Line two baking sheets with silicone baking mats or parchment paper.
3. Bring the milk, water, butter, and salt to a rapid boil in a heavy-bottomed medium saucepan over high heat.
4. Add the flour all at once, lower the heat to medium-low, and immediately start stirring energetically with a wooden spoon or heavy whisk.
5. The dough will come together and a light crust will form on the bottom of the pan.
6. Keep stirring—with vigor—for another minute or two to dry the dough.
7. The dough should now be very smooth.
8. Turn the dough into the bowl of a mixer fitted with the paddle attachment or into a bowl that you can use for mixing with a hand mixer or a wooden spoon and elbow grease.
9. Let the dough sit for a minute, then add the eggs one by one and beat, beat, beat until the dough is thick and shiny.
10. Make sure that each egg is completely incorporated before you add the next, and don't be concerned if the dough separates—by the time the last egg goes in, the dough will come together again.
11. Beat in the grated cheese.
12. Once the dough is made, it should be spooned out immediately.
13. Using about 1 tablespoon of dough for each gougère , drop the dough from a spoon onto the lined baking sheets, leaving about 2 inches of puff space between the mounds.
14. Using about 1 tablespoon of dough for each gougère, drop the dough from a spoon onto the lined baking sheets, leaving about 2 inches of puff space between the mounds.
15. Slide the baking sheets into the oven and immediately turn the oven temperature down to 375 degrees F.
16. Bake for 12 minutes, then rotate the pans from front to back and top to bottom.
17. Continue baking until the gougères are golden, firm, and, yes, puffed, another 12 to 15 minutes or so.
18. Serve warm, or transfer the pans to racks to cool.

#+begin_note
Gougères are good straight from the oven and at room temperature. I like them both ways, but I think you can appreciate them best when they're still warm. Serve with kir, white wine, or Champagne.
#+end_note

#+begin_note
The best way to store gougères is to shape the dough, freeze the mounds on a baking sheet, and then, when they're solid, lift them off the sheet and pack them airtight in plastic bags. Bake them straight from the freezer—no need to defrost—just give them a minute or two more in the oven. Leftover puffs can be kept at room temperature over night and reheated in a 350-degree-F oven, or they can be frozen and reheated before serving.
#+end_note


** Credits:
- https://www.epicurious.com/recipes/food/views/gougeres-361149
- date created: [2022-12-03 Sat]
