#+STARTUP: showeverything
* Lentil Stuffed Mini Peppers
** Ingredients:
- 1 cup dry lentils
- 3 cups water
- 1 lb. mini sweet peppers
- 1 Tablespoon olive oil
- 1 medium yellow onion small dice
- 12 oz. package frozen (cauli)rice, approx. 3 cups fresh
- 3 cloves garlic pressed
- 1 cup frozen corn
- 2 teaspoons cumin
- 1 teaspoon paprika
- 1 teaspoon chili powder
- 1 teaspoon oregano
- 1 teaspoon coarse ground sea salt
- A pinch of cayenne pepper (if you like a bit of heat)
- 16 oz. jar prepared salsa
*** Optional Garnish:
- ¼ cup fresh cilantro
- 2 Tablespoons hemp seeds
** Method:
*** How to cook dried lentils
1. Before cooking lentils, rinse in cold water, pick over to remove debris and drain.
2. It is not necessary to soak lentils before cooking, but you can to reduce cooking time by about half if you do.
3. Combine lentils and 3x their volume in water in a small saucepan over medium high heat.
4. Bring to a boil and adjust heat to maintain a low simmer.
5. Cook until lentils are tender, approx. 15 minutes.
6. Drain any liquid that wasn’t absorbed during cooking.
*** To make stuffed peppers
1. Preheat oven to 400°.
2. Line baking tray with unbleached parchment paper.
3. Make the lentils. (See above for directions. This can be done up to several days in advance.)
**** Prepare peppers
1. Cut peppers in half, through the stem.
2. Remove seeds and ribs.
   #+begin_tip
   Removing stems is optional: I like to leave the stems on for presentation. Brush with olive oil, sprinkle with S+P and place cut side up on prepared pan and cook for 20 minutes until beginning to soften.
   #+end_tip
4. Meanwhile, prepare the stuffing: heat heavy bottom skillet over medium heat.
5. Swirl in oil and then add onion.
6. Cook until it starts to soften, approx. 3 minutes.
7. Add the spices, garlic and cook, stirring for 30 seconds, so garlic is fragrant but doesn’t burn.
8. Then stir in the lentils, (cauli-)rice and corn. (If you're using frozen cauliflower rice, it's ok to add that straight from the freezer.)
9. Add the salsa and reduce heat to low.
10. Simmer for 2-3 minutes as flavors begin to marinate.
11. Scoop stuffing into each pepper, fill to heaping.
    #+begin_tip
    The easiest way to do this with the mini peppers is to use two teaspoons (the way you would for dropping chocolate chip cookies) and scoop with one and use the back of the other to push what's in the first spoon into the mini pepper.
    #+end_tip
13. Sprinkle with cilantro and hemp seeds if desired.
14. Turn heat down to 350° and bake for 20 minutes until lightly browned and filling is hot.
** Credits:
- From https://debraklein.com/stuffed-mini-peppers/#recipe
- date created: [2025-06-24 Tue]
- <2025-06-22 Sun> Made for New Resident Welcome social and they were very popular. This did, however, make at least 2x the needed amount of filling!
