#+STARTUP: showeverything
* Pistachio Bomb
** Ingredients:
- 1 clove garlic, through a press or minced fine
- 1½ TBS lemon juice
- ½ tsp Kosher salt (or table salt)
- ¼ cup plus 2 Tbsp shelled pistachios
   #+begin_note
   I used /Wonderful Brand/ shelled and lightly salted. If using unsalted nuts, you may want to up the salt. The recipe, because of the yogurt needs a decent bit of salt to drive the savory bus home.
   #+end_note
- 6 ounces roasted red peppers
- 16 ounces /Fage Total/ 5% Yogurt
   #+begin_note
   I am recommending only /Fage/ brand yogurt, because it’s the best. Subs might include /Cabot Whole Milk Greek/ or /Stonyfield Whole Milk Greek/. These brands, because I’ve had very good results with them in the past.
   #+end_note

- 3 Tbsp really good Extra Virgin Olive Oil
- ⅛ tsp (to taste) cayenne pepper, ground or a few shots of Tabasco
- pinch of white sugar
** Method:
1. Place the lemon juice in a small bowl.
2. Press the garlic into the bowl.
3. Add the salt.
4. Let that sit while you do the rest.
   #+begin_tip
   This is a great tip for this and hummus where you don’t want that bite but you do want the garlic “hit”.
   #+end_tip
5. Place all of the pistachios in a food processor (or other nut abusive machine) and pulse a few times for a coarse chop. This is the garnish; remove 2 Tbsp and set aside.
6. Continue to process the remaining ¼ cup pistachios into a coarse meal (it’s better than OK if you have some dusty bits and some chunks).
7. Cut the red peppers (½ of the peppers in the jar) into strips and those strips into ¼” bits. Get fancy and save some for a garnish.
8. Now strain the lemon juice, salt, and garlic into a large bowl.
9. Add the yogurt, the ¼ cup of finer pistachios, roasted red peppers, EvOo, cayenne, and white sugar.
10. Mix very well.
11. Place into a serving bowl, garnish with the 2 Tbsp of coarse pistachios and serve with warm pita wedges.
** Credits:
- From Todd McCagg
- date created: [2022-02-06 Sun]
