#+STARTUP: showeverything
* Apple Fritters
** Ingredients:
*** Fritters
- 1½ cups all purpose flour
- ¼ cup sugar
- 2 teaspoons baking powder
- ½ teaspoon salt
- 1½ teaspoons cinnamon
- ⅔ cup milk
- 2 eggs
- 3 tablespoons applesauce
- 2 large Granny Smith or Honey Crisp apples peeled, cored and diced
- canola oil for frying
*** Glaze
- 2 cups powdered sugar
- ¼ cup milk
- ½ teaspoon vanilla

** Method:
1. Whisk together flour, sugar, baking powder, salt, and cinnamon in medium bowl.
2. Make a well in the center and add ⅔ cup milk, eggs and applesauce. (Consider mixing liquids together first.)
3. Stir just to combine.
4. Fold in apples.  (Consider sauteing the apples in butter first. Add some sugar and cinnamon toward the end of the saute.)
5. Heat 1½ inches of oil in heavy skillet, dutch oven or deep fryer to 375 degrees.
6. Drop about ¼ cup of batter per fritter into hot oil; spreading it out as you drop.
7. Cook each side until golden brown; approximately 2 minutes per side.
8. Remove to paper towels to drain.
9. Whisk together ¼ cup milk, powdered sugar and vanilla.
10. Dunk each fritters in the glaze turning over to make sure both sides coated.
11. Place on wire racks to air dry and drip.

** Credits:
- From https://www.smalltownwoman.com/apple-fritter/
- date created: [2020-04-26 Sun]
- [2020-04-26 Sun] I had a problem getting the oil to 375. I heated the Dutch oven, then poured in the oil with a candy thermometer in it. But, as it turns out, the thermometer was not deep in the oil, so when it read 375ish, the oil was probably 500+ so I incinerated the first two batches. When I plunged the thermometer into the oil (and used the "laser thermometer") I got better readings. The fritters were good, but could have been a bit crispier. The recipe probably feeds three for breakfast.
