#+STARTUP: showeverything
* Baked French Toast
** Ingredients:
*** French Toast
- 1 large day old bread loaf like brioche, challah, crusty sourdough or French bread, see notes
- 6 whole eggs
- 1 cup whole milk
- ½ cup heavy whipping cream
- 2 tablespoons real maple syrup
- 1 tablespoon vanilla extract
- ¾ teaspoon ground cinnamon
- ⅛ teaspoon ground cardamom
- ⅛ teaspoon fresh grated nutmeg
- ¼ teaspoon fine sea salt
- 2 tablespoons butter plus more for greasing pan
- Optional toppings: Maple syrup, honey, powdered sugar and fresh berries
*** Cinnamon Sugar Topping
- 1 tablespoon granulated sugar
- ½ teaspoon ground cinnamon
** Method:
*** Prepare French Toast
1. Grease a 9-inch by 13-inch baking dish with butter and set aside.
2. Slice the bread into thick slices (½-inch to 1-inch thick). Cut each bread slice in half, making two triangles.
3. In a large bowl, whisk the eggs, milk, cream, maple syrup, vanilla, cinnamon, cardamom, nutmeg, and salt until combined.
4. Quickly dip each slice of bread into the milk mixture and place into the baking dish, arranging each slice so that they are angled and overlap slightly (like roof shingles).
5. When all the bread slices are arranged in the baking dish, pour the remaining milk mixture over the top of the bread. Cover the dish with aluminum foil and refrigerate at least 30 minutes and up to overnight.
*** Bake French Toast
1. Heat the oven to 350° Fahrenheit (175°C).
2. Bake the French toast, still covered, for 30 minutes.
3. After 30 minutes, make the cinnamon/sugar topping by stirring 1 tablespoon of sugar and ½ teaspoon cinnamon together.
4. Melt 2 tablespoons of butter, uncover the French toast and then slowly pour the melted butter over the top, trying to cover most of the bread slices.
5. Scatter the cinnamon sugar over the bread, and then bake, uncovered, until the tips of the bread are golden brown and the bread looks puffed, about 10 minutes.
6. Cool for 5 minutes
7. Cut into 8 squares, and serve with your favorite toppings.
** Credits:
- From https://www.inspiredtaste.net/44190/baked-french-toast/#itr-recipe-44190
- date created: [2021-09-27 Mon]
- [2021-09-26 Sun] Made for the Heimburgs. It didn't even need maple syrup!
