#+STARTUP: showeverything
* Baron Bagels

** Ingredients
- 1 teaspoon active dry yeast
- 1⅔ cups lukewarm water
- 5 cups (600 grams) bread flour
- 2 teaspoons salt, plus more for boiling
- 1 tablespoon diastatic malt powder
- ¼ cup poppy seeds, optional
- ¼ cup sesame seeds, optional

** Method
1. Put the yeast in the bowl of a standing mixer. Add 1⅔ cups lukewarm water and allow the yeast to activate, about 5 minutes. Add flour, salt and malt powder and mix at low speed for 5 minutes using the paddle attachment. Cover the dough and allow to rise at room temperature for about 2 hours.
2. Punch the dough down and shape into a rough rectangle about 1 to 1½ inches thick, and about 2 times longer than it is wide. If you are having trouble forming the dough, stretch it, wait for the gluten to relax and reform.
3. Cut the dough into 10 pieces of about 3 ounces each. Roll each into an 8-inch-long snakelike shape, tapering the dough at each end. Circle the dough around your hand, pinching the ends together and rolling under your palm once or twice to seal. Put the bagels on a Silpat or other nonstick baking sheet on top of a jellyroll pan. Cover well with plastic wrap and refrigerate for about 10 hours, or up to 24 hours.
4. Heat the oven to 425 degrees. If you have a baking stone or brick you use for baking, put it on a rack near the bottom of the oven; it will retain heat and produce a crisper bagel. Bring a large pot of water to boil, throw a handful of salt into the boiling water and remove the bagels from the refrigerator.
5. Using your hands, carefully place just enough bagels into the pot to cover the surface of the water, making sure that there are no bagels resting on top of one another. Let them float on one side for about 30 seconds before flipping them to the other side for another 30 seconds or so. Remove the bagels and drain well on a cooling rack.
6. Pour poppy or sesame seeds into a bowl wider than the bagels. Working very quickly, remove the bagels one by one and dip them into the topping. Place them back on the Silpat-covered baking sheet, topping side down.
7. Bake on the second to highest shelf of the oven for about 7 minutes. Then flip the bagels and continue baking for about 8 minutes, or until they are golden brown.
** Credits:
http://cooking.nytimes.com/recipes/1014445-baron-bagels
*** [2016-07-03 Sun] Made for Tracey and Doris who liked the flavor. They were rather flat. I made a dozen; perhaps try for 10 next time?
*** [2016-08-27 Sat] 
1. Replaced about 40g of flour with high gluten flour.
2. I diced a small jalapeño into two of the bagels and sprinkled locatelli on them too. They tasted good
3. Baking: stone on the bottom shelf, cooked on the top. I baked for 7 minutes on one side and then about 10 on the other, the last 3 with speed bake (since they weren't browning). But they were underdone in the middle.
4. Next time should be 7 minutes on one side, 7 minutes on the other, then speed bake for 2 minutes then flip for 2 minutes.
5. These were not good bagels: tasted ok, but were quite gummy, even after toasting. I think I used /way/ too much gluten; perhaps a tablespoon or two next time?
