#+STARTUP: showeverything
* Blueberry Cheesecake Baked Oats
** Ingredients:
- 1¼ cups whole milk, plus 1 tablespoon, divided
- ¼ cup sugar plus 1 tablespoon, divided
- 1 large egg
- 2 tablespoons unsalted butter, melted
- 2 teaspoons vanilla extract, divided
- 2 cups old-fashioned rolled oats
- 1 teaspoon baking powder
- ¼ teaspoon salt
- 1 cup fresh or frozen blueberries
- 4 ounces cream cheese (½ cup), softened
- 3 tablespoons fruit juice–sweetened blueberry preserves
** Method:
1. Preheat oven to 350°F.
2. Coat an 8-inch square (2-quart) baking dish with cooking spray.
3. Whisk 1¼ cups milk, ¼ cup sugar, 1 egg, the melted butter and 1 teaspoon vanilla together in a large bowl until smooth and the sugar is dissolved.
4. Add 2 cups oats, 1 teaspoon baking powder and ¼ teaspoon salt; stir until fully incorporated.
5. Fold in 1 cup blueberries.
6. Transfer the oat mixture to the prepared baking dish; let stand for 15 minutes to let the oats thicken slightly.
7. Meanwhile, combine softened cream cheese, the remaining 1 tablespoon each milk and sugar, and the remaining 1 teaspoon vanilla in a large bowl; beat with an electric mixer on medium-high speed until smooth and creamy, about 1 minute.
8. Spoon the cream cheese mixture by tablespoonfuls evenly onto the oat mixture.
9. Next to each spoonful of cream cheese mixture, place a spoonful of blueberry preserves.
10. Cut through the mixture several times with a knife to create a marbled design.
11. Bake until very lightly browned and set, 30 to 35 minutes.
12. Let cool for at least 10 minutes (or up to 30 minutes).
13. Serve warm or at room temperature.
** Yield
- 8 servings
** Credits:
- From https://www.eatingwell.com/blueberry-cheesecake-baked-oats-11765447
- date created: [2025-08-20 Wed]
- [2025-08-19 Tue] A rich, decadent breakfast suitable for guests.
