#+STARTUP: showeverything
* Buttermilk Scones with Raisins
By Donna Pilato, About.com
- It's difficult to picture a tea party that doesn't have at least one scone on the menu. Here is a simple recipe for buttermilk scones that turn out fluffy and buttery in absolutely no time. They're best served warm from the oven, but are still pretty tasty the following day.
- Prep Time: 15 minutes
- Cook Time: 15 minutes

** Ingredients:
- 1¾ cups all-purpose flour
- 1 teaspoon sugar
- 1 teaspoon salt
- 2 teaspoons baking powder
- ½ teaspoon baking soda
- 5 tablespoons unsalted butter, room temperature
- ½ cup raisins
- ¾ cup buttermilk, or slightly more as needed

** Method:
1. Preparation:
2. Preheat the oven to 450 degrees.
3. Mix thoroughly the flour, sugar, salt, baking powder and baking soda in a large bowl with a whisk or spoon.
4. Cut in the butter until the mixture resembles coarse meal. Stir in the raisins. Using a large spoon, blend in buttermilk until a soft dough forms.
5. Place dough on a floured board and roll out to ½ inch thickness. Using a sharp knife, cut dough into six squares, then cut each square again on the diagonal. Place triangles on ungreased baking sheet. Bake for 10 to 12 minutes until golden brown.

** Yield: 
Makes 12 scones.

** Credits:
7. http://entertaining.about.com/od/recipesandmenus/r/buttermilkscone.htm
8. date created: [2009-05-02 Sat]
