#+STARTUP: showeverything
* Cast-Iron Sourdough Pancakes
** Ingredients:
- ½ to 1 cup sourdough starter
- 2 cups all-purpose flour
- 2 cups whole milk
- 3 eggs
- 1 teaspoon baking soda
- 1 teaspoon salt
- 1 tablespoon sugar
- 1 tablespoon butter, plus more for serving
- 3 to 4 peeled and sliced pears (you could also use sliced apples, peaches or strawberries, or whole blueberries)
- Maple syrup, for serving
** Method:
1. Mix sourdough starter with flour and milk, then let it sit out at room temperature, covered with a cloth, overnight and up to 24 hours.
2. Stir well, and transfer a scant cup of this mixture into a plastic container with lid or glass jar to store in the fridge, for another batch of pancakes.
3. Whisk the eggs, baking soda, salt and sugar into the rest of the fermented flour and milk. The batter will loosen and take on the thick, airy liquid texture of a milkshake. If the batter seems a little too stiff, add a splash of milk.
4. Preheat the oven to 450°, with a cast-iron skillet inside the oven. (You can use a 4-inch pan for individual pancakes or an 8-inch pan for a larger pancake, which can be cut to share.)
5. When the pan is hot, remove it, and swirl in 1 tablespoon butter until melted, then add a thin layer of fruit, so that you can still see some parts of the bottom of the pan.
6. If using firm fruits like apples or pears, place the pan on medium heat on the stove top, and let the fruit sizzle for a minute or two until it has softened on its edges, then add batter. If using softer fruits or berries, add the batter right away. Add enough batter to totally cover the fruit and make a substantial pancake about a half-inch in thickness.
7. Return pan to oven for 15 minutes, or until the top of the pancake is evenly browned and the edges are crisp.
8. Flip pancake onto a plate fruit-side up, and serve hot with another knob of butter on top and a generous glug of maple syrup.
9. Repeat with remaining batter.
** Credits:
- From https://cooking.nytimes.com/recipes/1018663-cast-iron-sourdough-pancakes
- date created: [2023-02-15 Wed]
