#+STARTUP: showeverything
* Citrus Marmalade
** Ingredients:
- 2 pounds (907 grams oranges, grapefruit or lemons), washed
- 4 cups (800 grams) granulated sugar
- ¼ cup (60 milliliters) fresh lemon juice (from about 2 lemons)
- Add-ins (optional, see note)
** Method:
*** Cut the citrus
1. Using a sharp knife, slice off the top and bottom of the citrus so it sits sturdily on the cutting board.
2. Slice off the peel and white pith in sections, starting at the top and following the curve of the fruit. (You should have a pile of peels and a few naked fruit.)
3. Thinly slice the peels (with the pith) no thinner than ⅛ inch and no thicker than ¼ inch, place them in a large bowl and set aside.
4. Halve the fruit and remove any visible seeds.
5. Thinly slice about ¼-inch thick (white membrane and all), removing any seeds you might have missed.
6. Add the fruit to the peels, and cover with 3 to 5 cups of water, taking note of how much water you used.
7. Let this sit for at least 8 hours and up to 24 hours in the refrigerator. (This will help extract the pectin slowly as well as soften the peels.)
*** Make the marmalade
1. Place a small plate in the refrigerator to chill. (You’ll use this later.)
2. Place the peels, fruit and water in a large pot.
3. Add enough water to bring the total to 6 cups and bring to a strong simmer over medium–high heat.
4. Cook the citrus until the peels have begun to soften and turn translucent, and the liquid has reduced by about three-fourths, 40 to 50 minutes.
5. Add sugar and any add-ins and continue to cook, stirring occasionally at first, then more frequently as the marmalade cooks and the juices thicken.
6. Continue until most of the liquid has evaporated and the peels are totally softened and almost completely translucent, another 40 to 50 minutes.
7. As the marmalade cooks, the liquid reduces, the sugars thicken and the natural pectins activate.
   #+begin_tip
   You’ll notice the liquid go from a rapid, rolling boil with smaller bubbles to a slow, thick, tarlike boil with larger bubbles: This is the stage at which it’s most important to stir constantly along the bottom of the pot to prevent scorching and sticking. (Sugar is heavier than water and will concentrate at the bottom of the pot, making the fruit more likely to burn.) It’s also the stage at which splattering may occur, so take care in stirring.
   #+end_tip
8. When the marmalade reaches this point, add lemon juice and continue to cook, stirring constantly until the jam has returned to its previously thickened state, about another 5 minutes.
   #+begin_note
   At this stage, the mixture should look thick and viscous with bits of the peel floating around. The peels will never break into the liquid as with a jam: This is O.K.
   #+end_note
9. To test the jam's thickness, spoon a bit onto the chilled plate, return it to the refrigerator and chill for 2 minutes. Drag your finger through it: It should hold its shape on either side without appearing watery or runny. If it’s not there yet, cook it for a few more minutes.
10. Remove from heat and discard the vanilla bean, if used.
11. Divide among jars, leaving ¼ inch of space at the top, and seal immediately.
12. Can the marmalade (our How to Make Jam guide has detailed instruction), or store in the refrigerator.

#+begin_tip
To elevate your jam, add in any of these ingredients in "Make the marmalade" step 5:
- *Orange*: Add 1 tablespoon freshly grated turmeric; or add 2 tablespoons freshly grated ginger.
- *Lemon*: Add 1 vanilla bean, split and seeds scraped; or 1 tablespoon earl grey or rooibos tea leaves.
- *Grapefruit*: Add 2 tablespoons freshly grated ginger; 2 teaspoons rose water; or 2 tablespoons dried jamaica (a.k.a. hibiscus).
#+end_tip
** Yield:
About 4 cups (four 8-ounce jars)
** Credits:
- From https://cooking.nytimes.com/recipes/1018848-citrus-marmalade
- date created: [2024-01-31 Wed]
