#+STARTUP: showeverything
* First Watch A.M. Superfoods Bowl
** Ingredients:
- 1 cup unsweetened coconut or oat milk
- ¼ cup chia seeds
- 1 tablespoon pure maple syrup
- 1 tablespoon sugar
- ½ teaspoon vanilla
- ¼ cup blackberry jelly or preserves (preferably 100% pure fruit)
- 1 cup fruit (blueberries, sliced strawberries and sliced bananas)
- ¼ cup granola
** Method:
1. Mix milk, chia seeds, maple syrup, sugar, and vanilla in a medium bowl with a spoon or whisk, stirring thoroughly to combine.
2. Set aside briefly and stir or whisk again after about 10-15 minutes to break up any clumps of chia seeds.
3. Cover with plastic wrap and refrigerate at least an hour or two, or overnight.
4. At this point, you can divide it into 4 single-serve containers, or leave your pudding in a large serving bowl to portion out later.
   #+begin_tip
   The pudding will be soft-set after about 1 hour.
   But, if possible, we recommend waiting at least 2 hours before eating, until the pudding is creamier and more fully set.
   #+end_tip
7. When ready to serve the pudding, if it's not already divided into single-serve containers, portion out 4 equal servings.
8. Top each serving with 1 tablespoon jelly, ¼ cup fruit (or a little more, if desired) and 1 tablespoon granola.
9. Serve immediately.

** Credits:
- From https://twohealthykitchens.com/chia-pudding-coconut-milk/#mv-creation-101-jtr
- date created: [2024-12-21 Sat]
- [2024-12-20 Fri] It comes pretty close to that tasty First Watch dish! I used canned coconut milk but feel I could probably have used oat milk.
