#+STARTUP: showeverything
* Lauren Groveman's Bagels

** Ingredients:
- 3 to 4 tablespoons unsalted butter, melted, for brushing
- 2 cups tepid water or any combination of slightly warmed milk and water to equal 2 cups, plus ¼ cup tepid water, for yeast
- 3 rounded tablespoons (40.9 grams) solid vegetable shortening
- 1 package (7 grams) active dry yeast
- 2 tablespoons sugar or 1 tablespoon sugar and 1 tablespoon liquid (not dry) barley malt extract, plus ¼ cup sugar for when boiling the bagels
- 1 tablespoon fine table-salt
- 1 to 2 teaspoons freshly ground black pepper, optional
- Up to 6 cups (720 grams) high-gluten flour, including flour for dusting.
    + I prefer to use "super-gluten" flour, which I purchase at my neighborhood pizza place.
    + If unavailable, use a supermarket brand of bread flour.
- For the boiling water bath: Boiling water, as needed, ¼ cup granulated sugar and 1 teaspoon baking soda
- Glaze: 2 egg whites, at room temperature, lightly beaten with 1 teaspoon water

** Method:
1. Brush the interior of a 5-quart mixing bowl with melted butter and set aside for rising the dough.

2. To assemble liquid mixture: If using milk, heat in a medium-sized saucepan over medium-low heat until just warm throughout. Pour the milk into a large mixing bowl and add shortening and ½ cup lukewarm water. (If the milk became too hot, let it cool until just warm.) If not using milk, pour the 2 cups lukewarm water into a mixing bowl and add the shortening (no need to melt). Dissolve the yeast in ¼ cup lukewarm water with a pinch of the sugar. When yeast is creamy and starts to bubble, add to mixing bowl with 2 tablespoons of the sugar or the barley malt extract, salt and black pepper, if using.

3. To complete and knead the dough: Briskly stir in enough flour, a cup or so at a time, to make dough that is not easily stirred in the bowl. Turn out the dough onto a floured wooden board and knead in a brisk push, fold and turning motion, until smooth and elastic, about 5 minutes. Add only as much additional flour as necessary to keep dough from sticking to your hands and work surface. As always, use a pastry scraper while kneading to scrape dough off the board cleanly as you continue to knead in a sufficient amount of flour.

4. To rise the dough: Place the dough in the buttered bowl. Brush top of the dough with more melted butter, and then cover with buttered plastic wrap and a clean kitchen towel. Let rise in a warm, draft-free spot for 1 hour (or up to 2½ hours for an extremely light and flavorful bagel). Uncover bowl and punch down dough with several swift swats with the back of your hand. Recover bowl and refrigerate dough for 4 hours or, preferably, overnight (and up to two days!!).

5. To set up for shaping bagels: Position the rack to the lower third of the oven.
     a. If using a large pizza stone, place it on the oven rack and sprinkle a baker's peel generously with cornmeal and, if desired, a combination of seeds (poppy, sesame and caraway).
     b. Otherwise, brush or spray a large dark steel shallow baking sheet with vegetable oil and sprinkle the interior as described above. Place an (empty) heat proof pan on the rack underneath the tiles or stone.
     c. Preheat oven to 500 degrees F at least 30 minutes before you plan to shape, boil and bake bagels. (If working with a double oven, preheat the second oven as well). Pour the prepared egg-white glaze through a small medium-mesh sieve into another bowl to remove excess coagulation. Set the glaze next to your work surface. While the oven preheats, bring one or two large pots of water to a rapid boil. Lay a clean kitchen towel on each of 2 shallow trays or baking sheets (for 10 bagels) and sprinkle the towels lightly with flour.

6. To shape bagels: Remove the dough from the refrigerator. Punch the chilled dough down, with several swift blows, until totally deflated. Turn dough out onto a lightly floured board. Using the blade of a pastry scraper, divide the dough in half. I recommend baking only 5 bagels at a time (per oven) so each has enough space around it to bake properly. If not working with a double oven, place half of dough back in bowl, cover and refrigerate. Divide each half of dough into 5 equal pieces (for 10 in all). You'll work with 1 piece at a time, keeping the remaining pieces covered with a towel. Shape one piece of dough into a very tight, round ball by drawing dough up and pinching it at the top. Keep pinching and pulling upward, always keeping ball on a lightly floured board to prevent sticking. The ball should be perfectly round with the exception of a little knot of pinched dough on top. Turn ball (knot side down) and flatten gently. Push your index finger through the center of dough (right where the knot was). Gently stretch the hole, while being careful not to tear the rim, until hole measures about 2 to 2½ inches in diameter (the hole will shrink after rising and baking). As each bagel is shaped, place it on the prepared towel-lined trays spaced 2 inches apart. Cover bagels with another clean towel.

7. To boil the bagels: Add ¼ cup sugar and the baking soda to the pot of boiling water. Bring 1 tray of risen bagels over to the stove and carefully lower 2 to 4 bagels into the water (one at a time). Bagels should be able to sit freely in the water without touching and will expand in the water. Once the bagels rise to the top of the pot, continue to boil for 1½ to 2 minutes on each side, turning with a large round slotted skimmer or a large slotted spoon. After bagels have cooked on the second side, remove them with spatula (draining water) and drain on a kitchen towel (smoothest side up). Repeat with the remaining bagels

8. To glaze and top the bagels:  Place bagels (again, smoothest side up) on the prepared baker's peel or baking sheet. Using a pastry brush, paint boiled bagels with egg-white glaze. Don't worry if the glazed bagels seem wrinkled; this will smooth in the oven. When all of the bagels have been boiled and positioned on the peel or baking sheet, brush tops and sides of bagels once more with glaze. Sprinkle the desired toppings on each bagel or just glaze and leave plain. (Try not to let the glaze fall into puddles around bagels or into hole as this makes bagel dough stick to the peel. (Having the egg whites at room temperature and straining, helps remove their clumsy gelatinous quality.)

9. To bake the bagels: Just before baking, place the ice cubes and a few tablespoons water into a cup and pour this into the pan that sits below the baker's stone. If using tiles, place baker's peel all the way to the back of the hot oven and with a swift jerk; remove the peel, leaving the bagels on the hot tiles (or place baking sheet on hot oven rack). Reduce oven temperature to 450 degrees F and bake for ~25 minutes (If working with a convection oven, bake the bagels at 450 for 20 minutes. Keep the rest of the instructions the same.); turn oven off and allow bagels to sit there for 5 minutes. Open oven and allow bagels to sit in oven for 5 minutes more. Remove bagels to wire racks when uniformly golden and crisp. Cool thoroughly before storing.

10. To prepare the oven for the remaining batch of bagels (if not using a double oven): Before reheating the oven to 500 degrees F, sweep away any excess cornmeal and seeds from the tiles and onto a baking sheet to discard, using a cornmeal sweeper. (This is to prevent burning and smoking.) Preheat the oven, boil, and glaze, top and bake remaining bagels as described above.)

11. To store: Store cooled bagels to be served on the day of baking in a paper bag. Store the remaining bagels in a jumbo-sized, heavy-duty plastic bag, at room temperature. Bagels also freeze well in well-sealed freezer bags. To thaw, remove from the freezer the night before and allow bagels to thaw, overnight, in the sealed bag.

** Credits:
- https://www.laurengroveman.com/recipe/homemade-bagels/
- Recommended by Sarah's friend Kristen
- [2019-01-27 Sun] Made for brunch at Jan and Dan's with Nancy and Pat. Overall, pleased with the results.

- I added about 1 Tbsp of gluten to the flour.
- I let the dough rise for about 2.5 hours and then put it in the refrigerator for the rest of the day.
- I formed the bagels just before going to bed.
- In the morning, I took the bagels from the refrigerator; they had puffed a bit and closed the hole somewhat. I used two chopsticks to open the hole and kept them covered and out for 2 hours.
- At bath time, I boiled water and added 4 Tbsps of non-diastatic malt. Big mistake! It boiled over all over the stove. I should take it down to a simmer.
- After the bath, instead of drying the bagels on towels, I used racks for the first few. Mistake: they are highly impressionable. Towels on top of racks is fine.
- I baked them on the pizza stone, using convection for 20 minutes with a pan of boiling water. Then 5 minutes with the oven off and the door closed, then 5 minutes with the door open before letting them cool on the rack.
    + They were good, but I'd like them to be a bit crispier.
    + Perhaps I ought to remove the pan half-way through?
[2016-09-23 Fri]: Modifications:
- I used 1 cup water + 1 cup milk
    - Should try 1.5 cup water + .5 cup milk
- I added 1.5 tablespoons gluten flour.
    - Should cut back to 1 tablespoon.
- I added (slightly more than) 1 tablespoon diastatic malt powder.
    - Should try molasses or, better yet, malt syrup.
- Some say each bagel ought to weigh between 2.5 - 3 oz (70 - 85 grams), but others liked them in the 120-140 gram range.
    - I used ~130g and this was the right size! I got 10 good-sized bagels out of this recipe.
- In the morning, let dough warm for about an hour(!). Then after forming the bagels, let them rise for another 1 hour.
    - This seems crucial!
- https://cookingupastory.com/authentic-east-coast-bagels
- I'm not sure how long I baked them (T did a Google Hangout from Chicago in the middle and I never set the timer). It was probably a bit shy of 20 minutes, but the exteriors were as brown as I'd want them. They were a bit doughy in the middle, but the exterior was great: crisp and just a tad chewy.
- I had pre-heated the oven to 500 degrees for an hour (made some granola in it, which worked fine) then turned down to 450 degrees before I baked.
    - I should probably have turned it down sooner.
- I attempted to use a SilPat: a mistake. I couldn't easily get the SilPat off the peel onto the stone. I wound up putting the bagels directly on the stone (sans corn meal) and they stuck and oozed.
    - Next time: use parchment!
