#+STARTUP: showeverything
* Lemon Blueberry Scones
** Ingredients:
*** Single Recipe
- 1 cup (125g) all-purpose flour (spooned and leveled), plus more for hands and work surface
- 3 Tablespoons (37.5g) granulated sugar
- ½ Tablespoon fresh lemon zest (about ½ lemon)
- 1¼ teaspoons baking powder
- ¼ teaspoon salt
- ¼ cup (½ stick; 57.5g) unsalted butter, frozen
- ¼ cup (60ml) heavy cream (plus 1 Tbsp for brushing)
- ½ large egg
- ¾ teaspoons pure vanilla extract
- ½ heaping cup (90g) fresh or frozen blueberries (do not thaw)
- for topping: coarse sugar
*** Double Recipe
- 2 cups (250g) all-purpose flour (spooned and leveled), plus more for hands and work surface
- 6 Tablespoons (75g) granulated sugar
- 1 Tablespoon fresh lemon zest (about 1 lemon)
- 2½ teaspoons baking powder
- ½ teaspoon salt
- ½ cup (1 stick; 115g) unsalted butter, frozen
- ½ cup (120ml) heavy cream (plus 2 Tbsp for brushing)
- 1 large egg
- 1½ teaspoons pure vanilla extract
- 1 heaping cup (180g) fresh or frozen blueberries (do not thaw)
- for topping: coarse sugar
** Method:
*** Mix dry ingredients
1. Whisk flour, sugar, lemon zest, baking powder and salt together in a large bowl.
2. Grate the frozen butter using a box grater.
   #+begin_tip
   Grating two sticks halfway each avoids bruising your fingers!
   #+end_tip
3. Add it to the flour mixture and combine with a pastry cutter, two forks, or your fingers until the mixture comes together in pea-sized crumbs.
*** Mix wet ingredients
1. Whisk ½ cup heavy cream, the egg and vanilla extract together in a small bowl.
2. Drizzle over the flour mixture, add the blueberries, then mix together until everything appears moistened.
*** Form scones
1. Pour onto the counter and, with floured hands, work dough into a ball as best you can.
2. Dough will be sticky. If it’s too sticky, add a little more flour. If it seems too dry, add 1-2 more Tablespoons heavy cream.
3. Press into an 8-inch disc and, with a sharp knife or bench scraper, cut into 8 wedges (or 4 if making a Single Recipe).
4. Brush scones with remaining heavy cream and for extra crunch, sprinkle with coarse sugar. (You can do this before or after refrigerating in the next step.)
5. Place scones on a plate or lined baking sheet (if your fridge has space!) and refrigerate for at least 15 minutes.
*** Bake scones
1. Meanwhile, preheat oven to 400°F (204°C).
2. Line a large baking sheet with parchment paper or silicone baking mat.
3. After refrigerating, arrange scones 2-3 inches apart on the prepared baking sheet(s).
4. Bake for 22-25 minutes or until golden brown around the edges and lightly browned on top.
5. Remove from the oven and cool for a few minutes before topping with lemon icing.
*** Make the icing (optional)
1. Whisk 1 cup (120g) confectioners’ sugar and 3 Tablespoons fresh lemon juice (about 1 large lemon) together.
2. Drizzle over warm scones.
#+begin_tip
Leftover iced or un-iced scones keep well at room temperature for 2 days or in the refrigerator for 5 days.
#+end_tip
** Tags
Favorite
** Credits:
- From https://sallysbakingaddiction.com/glazed-lemon-blueberry-scones/
- date created: [2021-03-28 Sun]
- [2021-03-28 Sun] Made for second time, this time with no Lilly White flour -- King Arthur All Purpose instead. Just as light and fluffy on the inside and crispy on the outside.
