#+STARTUP: showeverything
* Marion Cunningham’s Lemon Crepe-like Pancakes
** Ingredients:
- 3 eggs, separated
- ¼ cup (30 grams) all-purpose flour
- ¾ cup (169 grams) cottage cheese
- ¼ cup (half a stick) butter, melted, plus more butter for greasing skillet
- 2 tablespoons sugar
- ¼ teaspoon salt
- 1 tablespoon grated lemon zest
** Method:
1. In a bowl, stir together the egg yolks, flour, cottage cheese, butter, sugar, salt and lemon zest until well mixed.
2. In the bowl of a stand mixer, beat the egg whites until they hold stiff peaks.
3. With large spoon or spatula, fold whites into yolk mixture, stirring gently until there are no yellow or white streaks.
4. Heat skillet or griddle over medium heat.
5. Grease lightly and spoon out about three large tablespoons of batter for each pancake.
6. Cook slowly for about 1½ minutes, then turn pancake over and cook for about 30 seconds.
7. Keep pancakes warm in 250° oven until ready to serve.
** Yield:
12 three-inch pancakes (enough for two hearty appetites)
** Credits:
- From https://cooking.nytimes.com/recipes/8797-marion-cunninghams-lemon-pancakes
- date created: [2025-03-20 Thu]
- [2025-03-15 Sat] Made a half recipe for T and me (using 1 egg). Got 5 pancakes, which really wasn't enough for a meal.
