#+STARTUP: showeverything
* Oatmeal Raisin Pancakes with Cinnamon Sour Cream
** Ingredients:
- 1 cup old fashion oats
- 1 cup all-purpose flour
- ¼ cup (packed) light brown sugar
- 2 teaspoons baking powder
- ½ teaspoon baking soda
- ½ teaspoon cinnamon
- 1⅔ cups buttermilk
- 2 large eggs
- 4 tablespoons unsalted butter, melted
- ½ teaspoon pure vanilla extract
- 1 cup plump raisins
- Cinnamon Sour cream, recipe follows
- Maple syrup for topping

** Method:
1. In a medium bowl, whisk together the oats, flour, brown sugar, baking powder, baking soda, and cinnamon.
2. In another bowl, whisk together buttermilk, eggs, melted butter and vanilla, blend thoroughly.
3. Pour the liquid ingredients over the dry ingredients and mix with the whisk until just combined. (Don't worry if the batter is a bit lumpy.)
4. With a rubber spatula gently fold in the raisins. (The batter will thicken as it stands.)
5. If necessary, lightly butter, oil, or spray your griddle or skillet.
6. Preheat over medium heat or if using an electric griddle set to 350° F.
   #+begin_tip
   If you want to hold the pancakes until serving time preheat your oven to 200° F.
   #+end_tip
8. Spoon ¼ cup of batter onto griddle for each pancake, allowing space for spreading, and use a spatula or the back of your spoon to lightly press the batter into rounds.
9. When the underside of the pancake are golden and the tops are speckled with bubbles that pop and stay open, flip over with a wide spatula and cook on the other side until light brown.
10. Serve immediately or place in oven while you make the rest of the batch.
** Yield:
Makes 14 (4-inch) pancakes
** Credits:
- date created: [2009-04-19 Sun]
- Recipe courtesy of Gourmet Magazine
