#+STARTUP: showeverything
* Pancakes, Eggless
** Ingredients:
- 1½ cups all-purpose flour
- 1 tablespoon baking powder
- 1 tablespoon sugar, optional
- ½ teaspoon salt
- 3 tablespoons melted butter, optional
- 1¼ cups milk, dairy or non-dairy
- 1 egg substitute
*** Egg Substitutions (pick one) 
- Flax egg :: mix 3 tablespoons warm water with 1 tablespoon ground flax meal. Wait 10 minutes until a gel-like mixture forms.
- Banana :: ¼ cup mashed banana
- Pumpkin :: ¼ cup canned pumpkin puree
- Chia egg :: mix 3 tablespoons hot water with 1 tablespoon chia seeds. Wait 10 minutes until a gel-like mixture forms and use that in the recipe.
- Commercial Egg Replacers :: see package directions for 1 egg. 



** Method:
1. In a large bowl, combine the flour, baking powder, salt, and sugar (if using). 
2. Select your egg replacer, and once mixed and you’ve waited the amount of time listed, add it to the middle of the bowl. If you’re using canned pumpkin or mashed banana, there’s no waiting.
3. Add the melted butter, if using, and milk to the bowl. 
4. From the middle, combine the wet ingredients with the dry ingredients, moving outwards to incorporate everything into a cohesive batter. 
5. Preheat a non-stick griddle or non-stick pan to medium-high heat. Grease it with butter or spray, and immediately pour a little less than ¼ cup of batter to form each pancake.
6. Wait about 2 minutes, until defined edges form and the batter has begun to bubble up at the top to flip. Cook for an additional minute until the tops feel “bouncy” to the touch. 
7. Remove from heat and serve.
** Credits:
- From https://www.laurafuentes.com/pancakes-without-eggs/
- date created: [2021-06-12 Sat]
- [2021-06-12 Sat] Made for T and Jeff. Pancakes were light and fluffy and we didn't notice lack of egg.
