#+STARTUP: showeverything
* Raspberry Almond Baked Oatmeal
** Ingredients:
- 1½ cups rolled oats
- 1 tsp. ground ginger
- ½ tsp. salt
- ¼ cup dry-roasted almonds, coarsely chopped
- 2 cups of unsweetened almond milk (or milk of choice)
- ¼ cup honey (85g) (or maple syrup)
- 2 Tbsp olive oil
- 1 tsp. vanilla
- 1 cup fresh raspberries + more for topping
** Method:
1. Preheat oven to 350° F.
2. Lightly coat a  8×8 (or 9×9) baking dish with oil.
3. In a large bowl, combine oats, ginger, salt, and chopped almonds.
4. In a separate bowl, whisk together milk, honey (or maple syrup), oil and vanilla then add to oat mixture, stirring until just combined.
5. Fold in fresh raspberries or berries of choice.
6. Spread oat mixture into a prepared baking dish and bake for 30 to 35 minutes until oats have set.
7. Remove oatmeal from oven and let stand for 10 minutes.
8. Top with additional fruit and drizzle with a little honey or maple syrup if desired.
9. Enjoy!

#+begin_tip
To prep this recipe ahead of time, simply mix all of your ingredients together and place in a 8×8 (or 9×9) baking dish, cover and refrigerate overnight.  Then just pop it in the oven and let it bake for 30 to 40 minutes while you get ready for work!
#+end_tip
** Credits:
- From https://www.eatyourselfskinny.com/raspberry-almond-baked-oatmeal/
- (Also see https://www.keepingthepeas.com/vegan-baked-oatmeal/ for a variation with apples and walnuts; I also added raisins, making it for Vera.)
- date created: [2021-02-02 Tue]
- [2021-01-31 Sun] Made for T who really liked it. I mixed it up the night before (but, honestly, it's not much of a time saver).
