#+STARTUP: showeverything
* Salted Caramel Sauce
** Ingredients:
- 1 cup (200g) granulated sugar
- 6 Tablespoons (90g) salted butter, room temperature cut up into 6 pieces
- ½ cup (120ml) heavy cream
- 1 teaspoon salt
** Method:
1. Heat granulated sugar in a medium saucepan over medium heat, stirring constantly with a high heat resistant rubber spatula or wooden spoon. Sugar will form clumps and eventually melt into a thick brown, amber-colored liquid as you continue to stir. Be careful not to burn.
2. Once sugar is completely melted, immediately add the butter. Be careful in this step because the caramel will bubble rapidly when the butter is added.
3. Stir the butter into the caramel until it is completely melted, about 2 minutes. If you notice the butter separating, remove from heat and vigorously whisk to combine it again. (If you’re nervous for splatter, wear kitchen gloves.)
4. Very slowly drizzle in ½ cup of heavy cream while stirring. Since the heavy cream is colder than the caramel, the mixture will rapidly bubble when added. Allow the mixture to boil for 1 minute. It will rise in the pan as it boils.
5. Remove from heat and stir in 1 teaspoon of salt. Allow to slightly cool down before using. Caramel thickens as it cools.
6. Cover tightly and store for up to 1 month in the refrigerator. Reheat in the microwave or on the stove to desired consistency.

** Credits:
- From https://sallysbakingaddiction.com/homemade-salted-caramel-recipe/
- date created: [2020-01-25 Sat]
- [2020-01-25 Sat] I made this for Mom but substituted half-and-half for the cream and it turned out well.
