#+STARTUP: showeverything
* Stuffed French Toast

** Ingredients:

- 8 (1-inch thick) slices bread (See Kelly's Note)
- 4 ounces (½ of an 8-oz. package) cream cheese, at room temp
- 2 teaspoons vanilla extract
- 1½ teaspoons fresh lemon juice
- 1 teaspoon grated lemon zest
- 1½ cups diced strawberries, divided

- ¾ cup heavy cream
- 4 large eggs
- 1 teaspoon cinnamon
- 1 Tablespoon sugar

- Unsalted butter, for cooking
- Maple syrup, for serving

** Method:
1. Cut a wide pocket into each slice of bread without cutting all the way through the bread.

2. In the bowl of a stand mixer fitted with the paddle attachment, beat together the cream cheese, vanilla extract, lemon juice, lemon zest and ½ cup diced strawberries until well combined, about 2 minutes.

3. Slather a portion of the cream cheese mixture inside each bread pocket and press each bread pocket closed.

4. In a medium bowl, whisk together the eggs, heavy cream, cinnamon and sugar.

5. Place a large pan over medium heat and add 2 tablespoons of butter. Once the butter has melted, dip each stuffed slice of toast into the egg mixture on all sides and shake off any excess. Place the bread immediately into the pan and cook until golden, about 2 minutes. Flip once and continue cooking until golden, about 2 minutes. Repeat the coating the cooking process with the remaining slices of bread. (Do not overcrowd the pan.)

6. Serve the French toast immediately topped with maple syrup and the remaining diced strawberries.

** Credits:
http://www.justataste.com/strawberry-cheesecake-stuffed-french-toast-recipe/

*** Kelly's Note:
Any variety of bread will work in this recipe. A few of my favorites include a loaf of sourdough, a French baguette or (extra-thick) Texas toast. Use whatever type of bread you prefer, however stale bread works best for French Toast, as it absorbs the most liquid.
*** My Notes:
- [2016-07-17 Sun] Made for Colwills, Doris and TC. Good, but /way/ too lemony... even though I used about half the zest and none of the lemon juice.
** Yield
PREP: 15 MINUTES
COOK: 5 MINUTES
YIELD: 4 SERVINGS
