#+STARTUP: showeverything
* Creamy White Bean Soup
** Ingredients:
- 2 tablespoons extra-virgin olive oil
- 1 medium yellow onion, chopped
- 2 medium stalks celery, chopped
- 1 tablespoon minced garlic
- 1 tablespoon Italian seasoning
- ¼ teaspoon crushed red pepper
- 2 (15-ounce) cans no-salt-added great northern beans, rinsed
- 1 (2 ounce) Parmesan cheese rind (optional)
- 4 cups unsalted vegetable broth
- ¾ teaspoon salt
- ½ teaspoon ground pepper
- 1 fresh or dried bay leaf
- ½ teaspoon grated lemon zest
- 2 teaspoons lemon juice
- ¼ cup grated Parmesan cheese
- 1 tablespoon chopped fresh flat-leaf parsley for garnish (optional)
** Method:
1. Heat 2 tablespoons oil in a large pot over medium-high heat.
2. Add chopped onion and chopped celery; cook, stirring often, until the onion is translucent, about 5 minutes.
3. Add 1 tablespoon garlic, 1 tablespoon Italian seasoning and ¼ teaspoon crushed red pepper; cook, stirring occasionally, until aromatic, about 2 minutes.
4. Stir in 30 ounces rinsed beans, 2-ounce Parmesan rind (if using), 4 cups broth, ¾ teaspoon salt, ½ teaspoon pepper and 1 bay leaf; bring to a boil over high heat.
5. Reduce heat to medium-low and cook, stirring occasionally, until the vegetables are tender, about 20 minutes.
6. Remove and discard the Parmesan rind (if using) and bay leaf.
7. Pour 2 cups of the soup into a blender.
8. Secure the lid on the blender and remove the center piece to allow steam to escape.
9. Place a clean towel over the opening.
10. Process until smooth, about 1 minute. (Use caution when blending hot liquids. Alternatively, pour 2 cups of the soup into a medium bowl; process until smooth using an immersion blender.)
11. Pour the pureed soup back into the remaining soup in the pot; stir to combine.
12. Stir in ½ teaspoon lemon zest and 2 teaspoons lemon juice.
13. Divide the soup among 4 bowls; sprinkle with ¼ cup Parmesan.
14. Garnish with 1 tablespoon parsley, if desired.
** Credits:
- From https://www.eatingwell.com/recipe/7939867/creamy-white-bean-soup/
- date created: [2026-01-19 Mon]
- <2026-01-19 Mon> Tasty. The vegetable broth was fairly salted; next time use unsalted.
