#+STARTUP: showeverything
* Hot and Sour Soup With Tofu
** Ingredients:
- 8 cups mushroom, vegetable stock
- 2 sticks celery, roughly chopped
- ½ head fennel, roughly chopped
- 1 large leek, halved lengthwise
- 3-inch piece ginger, peeled and sliced
- 1½ teaspoons freshly ground white pepper, plus more as needed
- 1 ½ teaspoon toasted sesame oil
- ¼ cup soy sauce, plus more as needed
- 2 tablespoons grapeseed oil
- ¼ teaspoon celery seeds
- 2 cups mushrooms, such as a mix of shiitake and fresh wood ear
- Kosher salt
- 4 ounces firm tofu, cutinto ¾-inch cubes
- ½ cup cooked, shredded crab meat(optional)
- ¼ cup distilled white vinegar, plus more as needed
- 3 tablespoons Chinese black vinegar, plus more as needed
- 3 tablespoons sliced scallions,to garnish
** Method:
1. In a large pot over medium-high heat, combine stock, celery, fennel, leeks, ginger, white pepper, sesame oil and soy sauce.
2. Simmer until aromatics infuse broth, 20 minutes. Meanwhile, set a wok or a large frying pan over medium heat. Add grapeseed oil and celery seeds. Cook until fragrant, about 30 seconds, then add mushrooms and a pinch of salt. Cook until mushrooms are tender and lightly browned, about 5 minutes.
3. Strain broth and return to pot, discarding aromatics. Add white and black vinegars to broth. Taste and add more vinegar, white pepper and/or soy sauce as needed. Divide mushrooms, tofu and crab, if using, among 4 bowls, and ladle hot broth over each serving. Garnish with scallions.
** Credits:
- From https://www.wsj.com/articles/hot-and-sour-soup-with-mushrooms-and-tofu-11614802587?mod=recipes
- date created: [2021-03-13 Sat]
