#+STARTUP: showeverything
* Spicy Vegetable Soup
** Ingredients:
- 24 ounces of frozen mixed vegetables
3 yellow potatoes, cubed
- 8-ounce can of tomato sauce
- 15-ounce can of fire roasted tomatoes
- 6 cups vegetable broth
- 1 tablespoon olive oil
- 1 yellow onion, diced
- 1 teaspoon minced garlic
- ½ teaspoon red chili flakes
- 1 teaspoon chili powder
- 2 bay leaves
- 1 teaspoon salt
- ½ teaspoon pepper
- grated Parmesan cheese for topping
** Method:
1. In a large stock pot, heat olive oil over medium heat and add 1 diced yellow onion, cooking until fragrant.
2. Then, add 1 teaspoon of minced garlic and keep sautéing for about eight minutes total, or until onions grow translucent.
3. Add 3 cubed potatoes, an 8-ounce can of tomato sauce, a 15-ounce can of fire roasted tomatoes, 6 cups of vegetable broth, ½ teaspoon of red chili flakes, 1 teaspoon of chili powder, 2 bay leaves, 1 teaspoon of salt, and ½ teaspoon of pepper.
4. Bring to a boil and then lower soup to a simmer.
5. Let simmer for 15 minutes, stirring occasionally.
6. Add the frozen mixed vegetables and stir, then simmer for five more minutes.
7. Remove bay leaves and serve.
** Credits:
- From https://www.mashed.com/368806/spicy-vegetable-soup-recipe/
- date created: [2023-03-27 Mon]
- [2023-03-27 Mon] Made for us and Chuck. I swapped out the frozen veggies for a pound of peas and a can of cannellini beans. It was nice and spicy.
