#+STARTUP: showeverything
* Asparagus Rolls with Herb Butter Sauce
** Ingredients:
- 4 sheets of filo pastry
- ¼ cup butter, melted
- 16 young asparagus spears, trimmed
*** Sauce
- 2 shallots, finely chopped
- 1 bay leaf
- ⅔ cup dry white whine
- 6 oz butter, softened
- 1 tbsp chopped fresh herbs
- salt and freshly ground black pepper
- chopped chives, to garnish
** Method:
1. Preheat the oven to 400 degrees F. Cut the filo sheets in half. Brush a half sheet with melted butter. Fold one corner of the sheet down to the bottom edge to give a wedge shape.
2. Lay 4 asparagus spears on top at the longest edge and roll up toward the shortest edge. Using the remaining filo and asparagus spears, make three more rolls in the same way.
3. Lay the rolls on a greased baking sheet. Brush with the remaining melted butter. Bake in the oven for 8 minutes, until golden.
4. Meanwhile, put the shallots, bay leaf and wine into a pan. Cover and cook over a high heat until the wine is reduced to 2-4 tbsp.
5. Strain the wine mixture into a bowl. Whisk in the butter, a little at a time until the sauce is smooth and glossy.
6. Stir in the herbs and add salt and pepper to taste. Return to the pan and keep the sauce warm. Serve the rolls on individual plates with a salad garnish if desired. Serve the sauce separately, sprinkled with a few chopped chives.
** Credits:
- From [[https://www.amazon.com/Fast-Vegetarian-Matthew-Drennan-2001-07-31/dp/B01K93C14U/ref=sr_1_1?dchild=1&keywords=Fast+Vegetarian+Food+drennan&qid=1595522860&sr=8-1][Fast Vegetarian Food]], page 58
- date created: [2020-07-23 Thu]
