#+STARTUP: showeverything
* Takeout Style Broccoli with Garlic Sauce
** Yield
Serves: 4

** Ingredients
- 1 pound broccoli, cut into florets
- 1 teaspoon dark soy sauce
- 2 tablespoons soy sauce
- 1½ teaspoons rice wine vinegar
- 2 teaspoons sugar
- ¾ cup hot chicken or vegetable stock (to keep the dish vegetarian)
- ½ teaspoon sesame oil
- A pinch of fresh ground white pepper
- 2 tablespoons vegetable oil
- 4 cloves of minced garlic (about a tablespoon)
- 1 tablespoon Shaoxing wine
- Cornstarch slurry (1½ tablespoons cornstarch mixed with 1½ tablespoons water)
- 1 teaspoon homemade chili oil (optional)

** Method
1. Wash the broccoli thoroughly and set aside. Mix the soy sauces, rice wine vinegar, sugar, stock, sesame oil, and ground white pepper, and set aside.

2. Heat the wok over high heat. Add the vegetable oil, garlic, and broccoli and quickly stir-fry so the garlic doesn't burn.

3. Stir fry for 15 seconds, and add the Shaoxing rice wine around the perimeter of the wok. Give everything a quick stir and add in the sauce mixture. Let the sauce come to a boil, and mix the cornstarch and water together to make a slurry.

4. Add the cornstarch slurry slowly while stirring the broccoli and sauce constantly. Let the sauce cook and thicken until it coats the back of a spoon. If you like a thick sauce, add more cornstarch and water. If you like your sauce thinner, add less cornstarch and water. If you'd like, stir in the chili oil at this point. Serve!

** Credits
http://thewoksoflife.com/2017/03/broccoli-garlic-sauce/
[2018-01-23 Tue] Made for myself. It was ok, a bit too vinegary.
