#+STARTUP: showeverything
 Crispy Cauliflower Buffalo Wings
** Ingredients:
- ½ head cauliflower, chopped into bite size pieces
- 1 cup garbanzo bean (or wheat) flour
- 1 cup water
- 1 tsp. garlic powder (or minced fresh garlic)
- ½ tsp. salt
- 1 tsp. melted butter or ghee
- ⅔ cup hot sauce
** Method:
1. Preheat oven to 450F.
2. In a medium size bowl, combine flour, water, garlic powder and salt. Whisk together until smooth.
3. Toss cauliflower into batter making sure to coat each piece completely, then place battered
   cauliflower on a lightly greased, non-stick baking sheet. 
4. Bake for 15 minutes, tossing half way through.

5. In the meantime, combine melted butter and hot sauce in a large bowl, stirring.
6. When cauliflower is done, remove it from the oven and gently toss it in the hot sauce mixture.
7. Place cauliflower back on the baking sheet and cook for an additional 25 minutes or until it
   becomes crispy. Allow cauliflower to cool for 15 minutes before serving. 
8. Serve with your favorite creamy dressing.
** Yield: Serves 4
** Credits:
http://www.mindbodygreen.com/0-13441/crispy-cauliflower-buffalo-wings-gluten-free.html
