#+STARTUP: showeverything
* Buffalo Bites
** Ingredients:
*** Buffalo Bites:
- 1 16-ounce container firm tofu (I used Organic firm from Trader Joe’s – the one in the pink package)
- 3/4 cup Frank’s Red Hot Buffalo Sauce, divided (½ + ¼ cup)
- 1/4 cup water
- 1 tablespoon + 1 teaspoon (vegan) butter, divided
- 2 tablespoons cornstarch
*** Dipping Sauce (or sub Vegan Ranch):
- 6 ounces unsweetened Greek-style non-dairy yogurt
- 1 teaspoon seasoning blend like Ranch seasonings (I used Trader Joe’s 21 seasoning salute)
** Method:
1. Remove tofu from package and drain excess liquid.
2. If pressing, place tofu block between two plates and place 2-3 cans on top. Place in refrigerator for 3-4 hours and drain additional water. You can skip this step if short on time.
3. Cube tofu into 1 inch cubes and place in a Tupperware container or baking dish large enough that cubes are close but not stacked.
4. Prepare marinade by combining 1 tablespoon melted non-dairy butter with ½ cup hot sauce + ¼ cup water. Mix. Pour over tofu. Cover tofu.
5. Place tofu in the refrigerator for 1-8 hours (or overnight).
6. Preheat oven to 400 degrees Fahrenheit.
7. Remove tofu from refrigerator and transfer to a bowl. Add cornstarch and gently toss until all tofu is lightly coated.
8. Line a baking sheet with a Sil-pat or parchment paper. Transfer tofu to baking sheet, spaced evenly.
9. Bake tofu for 30-45 minutes, until crispy on the outside, flipping halfway through.
10. Meanwhile, combine remaining ¼ cup hot sauce + 1 teaspoon melted non-dairy butter. Use to drench tofu immediately after removing from the oven.
11. Serve immediately.

** Credits:
- From https://kbaked.com/2018/01/04/baked-buffalo-tofu-bites/
- date created: [2020-12-28 Mon]
