#+STARTUP: showeverything
* Cauliflower, Potato, Fennel and Chilli Cheese Croquettes
** Ingredients:
- 2 baking potatoes
- 175g of cauliflower florets
- 100g of mature cheddar, cut into cubes
- 2 tsp fennel seeds
- 1 tsp cumin seeds
- 2 tsp chilli flakes
- salt, to taste
- 2 pinches of black pepper
- 2 eggs, beaten
- 50g of plain flour, you may need extra
- Panko breadcrumbs
- vegetable oil, for frying
** Method:
1. Preheat an oven to 375°F/190°C/gas mark 5.
2. Place the potatoes on a baking tray, prick a few times with a fork then place in the oven for about 1 hour, or until fluffy and cooked through.
3. When the potatoes are cool enough to handle, scoop out the insides and place in a large bowl.
4. Place the cauliflower in a steamer basket set over water and steam for 7–10 minutes or until tender, then leave to cool. Mash the cauliflower lightly with a fork and add it to the potato mixture.
5. Sprinkle in the fennel seeds, cumin seeds, chilli, salt and black pepper and mix well. Add the cubes of cheese and gently toss the mixture until evenly combined.
6. Make even sized ‘sausages’ with the croquette mixture, then roll and coat them in plain flour, then the egg and finally coat the panko breadcrumbs. (I made about 14 croquettes from this quantity of ingredients.)
7. Place the croquettes in the fridge to chill and set for 30–60 minutes.
8. When you are ready to fry them, heat the oil in deep-fryer or large heavy-based saucepan.
9. Deep fry the croquettes for 2–3 minutes or until golden, then transfer onto kitchen paper with a slotted spoon. Serve immediately.
** Credits:
- From https://www.greatbritishchefs.com/recipes/cauliflower-cheese-croquettes-recipe
- date created: [2020-01-20 Mon]
- [2021-01-09 Sat] Made for T. I got 8 croquettes out of the recipe. They were light, not greasy and quite tasty. A hit!
