#+STARTUP: showeverything
* Cauliflower Wings
** Ingredients:
- 4 cups vegetable broth
- 1 medium size head cauliflower, broken into about 32 florets
- 16 rice paper wraps
- ¾ cup red hot sauce or sauce of choice
** Method:
1. Bring the vegetable broth to a boil in a large saucepan over medium heat.
2. Drop in five cauliflower florets at a time, and parboil for 1 minute per batch, removing with a slotted spoon.
3. Repeat until all florets have been parboiled.
4. Allow them to cool for 5 minutes until they can be safely handles.
5. Take the pot off the heat and allow to cool slightly.
6. Slice the rice paper wraps in half with a pair of kitchen scissors, and dip them into the broth for about 15 seconds, until softened.
7. Wrap an individual rice paper half over each of the florets until they are covered completely.
8. Place on a baking sheet and broil at 500° F in the middle rack for 8 minutes, watching and turning about every 2 minutes as they brown.
9. Once lightly crisped, remove from the oven and allow to cool for 10 minutes before tossing in the hot sauce, or your preferred sauce of choice!
** Tags:
IsVegan
** Credits:
- From https://www.instagram.com/reel/CotbRLuJ2S3/ and page 184 of the PlantYou cookbook
- date created: [2024-02-21 Wed]
