#+STARTUP: showeverything
* Chipotle Ranch Dressing
** Ingredients, version 1:
+ 1 cup mayonnaise
+ 1 cup sour cream
+ 1 cup buttermilk
+ 1½ teaspoons granulated garlic
+ 1 teaspoon garlic powder
+ 1½ teaspoons onion powder
+ ¼ cup dried parsley ( I used fresh)
+ 1½ teaspoons dried chipotle powder
+ 1½ teaspoons lime juice
+ 1½ teaspoons salt

** Ingredients, version 2:
+ ½ cup mayo (or use sour cream, vegan mayo “Veganaise” – or make with silken tofu, see notes below)
+ 1 tablespoon water (for a thinner sauce)
+ 1 - 2 teaspoons lime juice (to taste)
+ ⅛ teaspoon salt, more to taste
+ ½ teaspoon chili powder
+ 1 teaspoon smoked paprika
+ ⅛ - ¼ teaspoon chipotle powder – you can also use one canned chipotle pepper (blending it with the mayo in a blender) or just stir in a teaspoon or two of the spicy smoky adobo sauce from the can. Start conservatively, adding more to taste.

** Method:
1. Mix in mixer or food processor on low speed until well mixed. Or whisk.
2. Refrigerate.

** Credits
http://www.food.com/recipeprint.do?rid=250131
https://www.feastingathome.com/chipotle-mayo/
Made [2017-07-02 Sun]. Tasty!
