#+STARTUP: showeverything
* Crackling Cornbread
** Ingredients:
- 1 cup stone-ground cornmeal
- 1 cup unbleached all-purpose flour
- ⅓ cup granulated sugar
- 2½ teaspoons baking powder
- ¼ teaspoon salt
- 1 cup buttermilk
- +1 cup diced, crisp-cooked bacon+
- 6 tablespoons (¾ stick) sweet butter, melted
- 1 egg, slightly beaten
** Method:
1. Preheat oven to 400 degrees F.
2. Grease a 9-inch-square baking pan.
3. Stir dry ingredients together in a bowl.
4. Then stir in buttermilk, +bacon,+ butter and egg and mix gently.
5. Pour batter into a the prepared pan, set on the middle rack of the oven and bake for 25 minutes.
6. Cornbread is done when edges are lightly browned and a knife inserted in the center comes out clean.
7. Cut into 3-inch squares to serve.
#+begin_note
Variation: Spoon the batter into 10 greased muffin cups and bake for about 20 minutes.
#+end_note
** Credits:
- From /The Silver Palate Cookbook/ by Julee Rosso and Sheila Lukins (with Michael McLaughlin), page 247.
- http://www.cookstr.com/recipes/crackling-corn-bread#UIc5zjOZugckUws9.99
- date created: [2020-07-26 Sun]
- I usually use a cast iron pan, and melt some of the butter in the pan to grease it.
