#+STARTUP: showeverything
* Indian-Style Rice Salad
Time: 30 to 60 minutes, depending on the type of rice

** Ingredients:
- 1½ to 2 cups brown or white basmati rice
- Salt and freshly ground black pepper
- ¼ cup chopped scallion
- ¾ cup cubed cooked potato
- ¾ cup cooked cauliflower florets
- ¾ cup cooked green peas
- ½ cup coconut milk, or more as needed
- 3 tablespoons rice wine vinegar, or more to taste
- 1 tablespoon curry powder, or to taste
- 1 jalapeno or other hot fresh chili, stemmed, seeded and minced, or to taste, optional
- ½ cup chopped fresh cilantro.

** Method:
1. Cook rice in abundant salted water, as you would pasta, until it's just done; white rice will take 10 to 15 minutes, brown 30 or a little longer.
2. Drain, rinse in cold water, drain again, then combine with vegetables in a large bowl.
3. Combine black pepper, coconut milk, rice wine vinegar and curry powder in a blender and turn machine on; a creamy emulsion will form within 30 seconds. Taste and add more vinegar a teaspoon or two at a time until balance tastes right to you, then add more curry powder, salt, or pepper, if needed.
4. Drizzle vinaigrette over rice and vegetables.
5. Use 2 big forks to combine, fluffing rice and tossing gently to separate grains.
6. Stir in chili, if using, and cilantro, taste, and adjust seasoning or moisten with a little more dressing.
7. Serve at room temperature, or refrigerate for up to a day, bringing salad back to room temperature before serving.

** Yield: 4 to 8 servings.

** Credits:
- New York Times "The Minimalist" 30 July 2008
- date created: [2008-07-31 Thu]
