#+STARTUP: showeverything
* Mexican-Style Cornbread
** Ingredients:
- 2 eggs
- 1 cup buttermilk
- ¼ cup (54 g) corn or coconut oil
- 1 ½ cups shredded Cheddar cheese, divided
- 1 can (8 ounce) cream-style corn
- 1 large onion, chopped
- 2 fresh jalapeno peppers, seeded and minced
- 1 cup cornmeal
- ½ cup all-purpose flour
- 2 teaspoons baking powder
- ½ teaspoon baking soda
- ½ teaspoon salt
** Method:
1. Gather all ingredients.
2. Preheat the oven to 375° F (191° C).
3. Grease an 8-inch square pan or a cast iron skillet.
4. Beat eggs in a medium bowl; mix in buttermilk and corn oil. Stir in 1 cup shredded cheese, creamed corn, onion, and jalapeños.
5. Whisk cornmeal, flour, baking powder, baking soda, and salt together in a large bowl; stir in egg mixture until combined.
6. Pour batter into the prepared pan; sprinkle remaining ½ cup cheese on top.
7. Bake in the preheated oven until top is golden brown and a toothpick inserted in the center comes out clean, about 30 to 35 minutes.
** Credits:
- From https://www.allrecipes.com/recipe/6802/mexican-style-cornbread/
- date created: [2025-04-06 Sun]
- Made for the Pridemores, Messners and T to a positive reception. It's light and fluffy and just a bit crisp on the exterior. I used coconut oil instead of corn oil in the recipe and to grease the pan. I also used a 50/50 mixture of Greek yogurt and oat milk instead of buttermilk. The original recipe called for cooking at 350° F (175° C), but several comments suggested cooking at a higher temperature, so I baked the cornbread in a hot cast iron pan at 375° for 30 minutes and it seemed just right.
