#+STARTUP: showeverything
* Oven-Roasted Brussels Sprouts With Balsamic Vinegar
** Ingredients:
- 2 to 3 cups Brussels sprouts
- 3 tablespoons balsamic vinegar
- Dash of coarse salt (sea salt or kosher salt)
- Freshly ground black pepper, to taste
- 3 tablespoons olive oil

** Method:
1. Gather the ingredients.
2. Heat the oven to 375 F.
3. Give the Brussels sprouts a rinse in cold water and dry on a paper towel.
4. Trim off the ends of the sprouts if they are large and firm. If they are smaller and more tender, just cut off the brown end. Pull off any loose outer leaves. Slice the sprouts in half lengthwise.
5. Place the Brussels sprouts in a single layer on a foil-lined baking sheet.
6. In a small bowl, whisk together the vinegar, salt, and pepper.
7. While whisking, slowly drizzle in the olive oil. Whisk until combined.
8. Drizzle the oil-and-vinegar dressing over the sprouts, reserving a little for serving, and gently toss to coat.
9. Roast in the oven for 25 minutes, turning once. The sprouts are done when they are browned and caramelized.
10. Serve the Brussels sprouts with an extra drizzle of the dressing if you wish, but they are also delicious just as they are from the oven.
11. Enjoy.
** Credits:
- https://www.thespruceeats.com/brussels-sprouts-with-balsamic-vinegar-3377791
- date created: [2020-01-18 Sat]
