#+STARTUP: showeverything
* Potato-Cheddar Soup With Quick-Pickled Jalapenos
** Ingredients:
- 2 jalapeños
- 2 limes, halved
- Kosher salt and black pepper
- Large pinch of granulated sugar or a drop of honey
- 3 tablespoons unsalted butter
- 1 large Spanish or white onion, diced
- 2 celery stalks, diced
- 4 garlic cloves, minced
- ½ teaspoon chili powder, plus more for garnish
- 2½ pounds Yukon Gold potatoes, peeled and cut into 1-inch cubes
- 1 quart vegetable broth
- 2 cups grated Cheddar (8 ounces), plus more for garnish
- 1 cup half-and-half, or use ½ cup whole milk and ½ cup heavy cream
- 3 scallions, white and light green parts, thinly sliced
- Chopped cilantro, for serving

** Method:
1. Thinly slice the jalapeños, discarding the seeds if you like. Put slices in a bowl and squeeze in enough lime juice to cover them. Add a pinch each of salt and sugar. Let sit at room temperature while you make the soup. (The jalapeños can be prepared up to 5 days ahead of time and stored in the refrigerator; they get softer and more pickle-y as they sit.)
2. In a large pot, melt the butter over medium heat.
3. Add onion, celery and a large pinch of salt, and sauté until lightly golden and soft, about 10 minutes.
4. Add garlic and chili powder and sauté until fragrant, 1 minute.
5. Add potatoes, broth and 2 teaspoons salt, and bring to a simmer. Cook until potatoes are very tender, 30 to 40 minutes.
6. Using an immersion blender or transferring the soup to a regular blender in batches, purée the soup, adding some water as needed to thin it out. (The soup can be as thick or brothy as you like.)
7. Return the soup to the pot if you removed it and reduce heat to medium-low.
8. Add cheese and half-and-half, and cook at a very gentle simmer, stirring, until the cheese melts, 1 to 2 minutes. Taste and season with salt and pepper as needed.
9. Top each bowl with pickled jalapeños, plus a drizzle of their pickling liquid and a pinch of chili powder, along with scallions, cilantro and more Cheddar.

** Credits:
- From https://cooking.nytimes.com/recipes/1021839-potato-cheddar-soup-with-quick-pickled-jalapenos
- date created: [2022-02-01 Tue]
- [2022-02-01 Tue] Hearty, flavorful soup.
