#+STARTUP: showeverything
* Quick Refrigerator Pickled Cucumbers
** Ingredients:
- 5 small cucumbers
- ¼ tsp mustard seed, whole
- ¼ teaspoon dill, dried
- ½ tsp black peppercorn
- 2 garlic cloves, whole
- 1 cup water
- 1 cup white vinegar (can sub with apple cider vinegar)
- 2 tbsp sugar
- 1 tbsp salt
** Method:
1. Slice the cucumbers into uniform coins or spears (your choice!). You’re going to use around 3 to 5 (depending on the specific size) cucumbers in this recipe per 16 oz. jar.
2. Add the cucumber slices, mustard seed, dill, peppercorn, and garlic into your jar. Don’t worry that the spices settle at the bottom, they will rise up again evenly distribute their flavor when you add the vinegar brine.
3. Mix the vinegar, water, salt, and sugar in a stainless steel pan and bring to a boil. You’ll need to babysit this.
4. As soon as it reaches a good boil, pour it over the cucumber mixture in the jar until they are just covered. Don’t let it over boil or some of the vinegar needed for the pickling process will boil out.
5. Put the top on immediately and put into the refrigerator. Let flavors blend overnight for best results.
** Credits:
- From https://southerneatsandgoodies.com/pickled-cucumbers/
- date created: [2023-02-20 Mon]
- [2024-08-02 Fri] Crisp pickles that have a lot going on taste-wise. Yummy!
