#+STARTUP: showeverything
* Roasted Cabbage with Walnuts and Parmesan
** Ingredients:
- 1 medium-large (1¾  pounds) or two small heads savoy cabbage
- 7 tablespoons extra-virgin olive oil, divided
- 1 teaspoon kosher salt, plus more to taste
- Freshly ground black pepper
- Scant ½ cup (1.75 ounces) walnut halves and pieces
- 1 large or 2 smaller garlic cloves
- 1 large lemon
- Red pepper flakes, such as Aleppo (optional)
- Grated parmesan, to taste
** Method:
1. Heat oven to 475ºF.
2. Remove any damaged outer leaves of cabbage and cut it 8 (for small ones) to 12 (for a large one) wedges.
3. Coat a large baking sheet with 2 tablespoons olive oil.
4. Arrange cabbage wedges in one layer, drizzling or brushing them with 2 more tablespoons olive oil and sprinkle with 1 teaspoon kosher salt and freshly ground black pepper to taste.
5. Roast for 8 to 10 minutes, until charred underneath (don’t panic if you see a few thin black edges; they’re going to taste amazing).
6. Use a spatula to flip each piece over and roast for 5 more minutes, until the edges of the cabbage are dark brown.
7. Meanwhile, while cabbage roasts, place nuts on a smaller tray or baking dish and roast them next to the cabbage for 4 to 5 minutes.
8. Remove and scatter them, still hot, onto a cutting board and coarsely chop them.
9. Scoop into a bowl and finely grate the zest of half a lemon and all of the garlic over it.
10. Add remaning 3 tablespoons olive oil to walnuts, a few pinches of salt and red pepper flakes and stir to combine.
    #+begin_tip
    If you’ve got a couple minutes to let it all infuse as it cools, let it rest.
    #+end_tip
11. When ready, squeeze the juice of half your lemon in and stir to combine. Adjust flavors to taste, adding more lemon if needed; you want this dressing to be robust.
12. The moment the cabbage comes out of the oven, spoon the walnut dressing over the wedges.
13. Grate parmesan all over, to taste.
14. Serve immediately, while piping hot. There will be no leftovers.
** Credits:
- From https://smittenkitchen.com/2019/11/roasted-cabbage-with-walnuts-and-parmesan/ by way of Nancy Burnett
- date created: [2021-03-13 Sat]
- [2021-02-16 Tue] T made it. Yummy!
