#+STARTUP: showeverything
* Roasted Brussels Sprouts
** Ingredients:
- 1½ pounds Brussels sprouts trimmed and halved
- 4 cloves garlic very roughly chopped (leave the pieces a bit chunky; add more if you live in a house of garlic lovers)
- 1 ½ tablespoons extra-virgin olive oil
- ½ teaspoon kosher salt
- ¼ teaspoon black pepper
- 2 tablespoons freshly ground or grated Parmesan
- Any optional additions: lemon, balsamic vinegar, herbs, red pepper flakes, etc.
** Method:
1. Place a rack in the upper third of your oven and preheat the oven to 400 degrees Place the Brussels sprouts and garlic in the center of a large rimmed baking sheet.
2. Drizzle with the olive oil and sprinkle with salt, pepper, and any other desired spice additions.
3. Gently mix until the Brussels sprouts are evenly coated, then spread them into a single layer on the baking sheet.
4. For even better crisping, flip the Brussels sprouts so that they are all cut sides down.
5. Bake for 10 minutes, then remove from the oven and stir in the Parmesan cheese.
6. Continue baking 10 to 20 additional minutes, until the Brussels sprouts are lightly charred and crisp on the outside and tender in the center.
     + The outer leaves will very dark too.
     + Watch carefully towards the end of the baking time, as the cooking time will vary based on the size of your sprouts.
     + Season with additional salt and/or pepper to taste.
     + Enjoy immediately.
#+begin_tip
/For Balsamic or Lemon Brussels Sprouts/: Drizzle the vinegar or lemon juice over the sprouts after removing them from the oven. Return the pan to the oven for 1 to 2 minutes, then serve.
#+end_tip

#+begin_tip
/To Make Dairy Free, Vegan, or Whole30/: Omit the Parmesan or swap it for nutritional yeast. Sprinkle on the nutritional yeast just before serving.
#+end_tip

** Credits:
- From https://www.wellplated.com/roasted-brussels-sprouts-with-garlic/
- date created: [2022-02-20 Sun]
- [2022-02-20 Sun] Made for Pat, Sharon, Lynn and TC: yum!
