#+STARTUP: showeverything
* Summer Farro Salad
** Ingredients
*** for Salad:
- 3/4  cup uncooked farro
- 1 pint strawberries hulled and quartered
- 2 medium avocados diced
- 3 cups loosely packed baby spinach roughly chopped
- 1/2 cup Vegan crumbled feta cheese
- 1/2  small red onion finely chopped
- 1/4 cup chopped toasted walnuts
*** for Dressing
- 3 tablespoons extra virgin olive oil** or aquafaba
- 2 tablespoons balsamic vinegar
- 1 tablespoons honey
- 1 teaspoon Dijon mustard
- 2 teaspoons poppy seeds
- 1/4 teaspoon kosher salt

** Method:
1. Prepare farro according to package instructions. Place in a serving bowl and let cool while you prepare the other ingredients.
2. In a small bowl, whisk together all of the ingredients until combined: olive oil or aquafaba, balsamic vinegar, honey, mustard, poppy seeds, and salt. Taste and adjust seasoning as desired.
3. Pour over the farro, then toss to coat.
4. Add the remaining ingredients to the bowl with the farro: strawberries, avocados, spinach, feta, red onion, and walnuts, then toss gently to combine. Serve chilled or at room temperature.
** Credits:
- From Patsy McCutcheon
- date created: [2023-06-24 Sat]
- [2023-06-29 Thu] Made for Greg and Mary Ann. Left out the avocados but it was still tasty.
