#+STARTUP: showeverything
* Sweet and Sour Cauliflower
** Ingredients:
- 6 tablespoons cornstarch (for the cauliflower) plus 1 teaspoon (for the sauce)
- 1 large cauliflower (about 2 pounds), cut into bite-size florets
- salt and pepper
- 3-5 tablespoons extra-virgin olive oil
- 3 tablespoons ketchup
- 3 tablespoons sugar
- 2 tablespoons rice vinegar
- 2 tablespoons soy sauce or tamari
- 1 garlic clove, finely chopped
- 2 scallions, thinly sliced
- rice or noodles, for serving
** Method:
1. If using an oven, heat it to 425°. (If using an air fryer, heat it to 400°, if preheating is recommended for your air fryer.)
2. Place 3 tablespoons cornstarch in a large bowl.
3. Add the cauliflower, season with a big pinch of salt and pepper, and toss to coat.
4. Drizzle in 2 to 3 tablespoons oil and toss until well coated.
5. Add 3 tablespoons cornstarch and toss.
6. Drizzle in another 1 to 2 tablespoons oil and toss well again, making sure there is no dry cornstarch on the cauliflower.
7. If using an oven:
     a. Grease a sheet pan with a drizzle of olive oil.
     b. Arrange the florets in a single layer on the baking sheet and roast for 10 minutes.
     c. Remove from the oven, flip the cauliflower to encourage even cooking, and return to the oven for another 8 to 10 minutes, cooking until it is tender and golden around the edges.
8. If using an air fryer:
     a. You may need to work in batches depending on the size of your machine.
     b. Arrange the cauliflower in a single layer on the rack, and air fry for 16 minutes, tossing the cauliflower halfway through, to encourage even crisping.
     c. Cook the remaining cauliflower.
9. While the cauliflower cooks, make the sweet and sour sauce: Place the ketchup, sugar, vinegar, soy sauce and garlic in a small pot.
10. Heat over medium, stirring, until the sugar melts and the mixture starts bubbling around the edges, about 1 minute.
11. Whisk the remaining 1 teaspoon cornstarch with 2 tablespoons of water, then slowly pour the cornstarch slurry into the pot, stirring constantly, until the mixture thickens, about 1 minute.
12. To serve, transfer the cauliflower to a bowl and drizzle the sweet and sour sauce over the florets.
13. Top with scallions. Serve with rice or noodles.
** Tags:
IsFavorite
** Yield:
4 servings
** Credits:
- From https://cooking.nytimes.com/recipes/1025452-sweet-and-sour-cauliflower
- date created: [2025-04-03 Thu]
- [2025-04-02 Wed] I used a bit less sugar (probably just over 2 tablespoons) but could probably use even less. Made for T and the Messners who seemed to like it. The cauliflower came out nice and crispy and the sauce was tasty.
