#+STARTUP: showeverything
* Vegan Baked Beans
** Ingredients:
- 2 tablespoons olive oil
- 1 small yellow onion, chopped small
- ⅛ cup blackstrap molasses
- ⅛ cup brown sugar
- ⅛ cup pure maple syrup
- ½ cup ketchup or tomato sauce
- 1 teaspoon salt
- 1 teaspoon smoked paprika
- 1 tablespoon apple cider vinegar
- 1 tablespoon vegan Worcestershire sauce
- 1 tablespoon yellow mustard
- 1-2 teaspoons Sriracha hot sauce or liquid smoke, to taste
- ½ cup water
- (2) 15-ounce cans small navy beans drained and rinsed,
** Method:
1. Preheat the oven to 350° F.
2. In a large pot, warm the olive oil over medium heat.
3. Add the chopped onion and stir for about 5 minutes, until translucent.
4. To the pot, add the molasses, brown sugar, maple syrup, ketchup, salt, smoked paprika, apple cider vinegar, vegan Worcestershire sauce, mustard, Sriracha hot sauce and water.
5. Stir well, then add the drained and rinsed beans.
6. Transfer to a 2-quart casserole dish (or use a dutch oven or other oven-safe pot) and cover with foil or an oven-safe lid.
7. Bake for 1 hour, then remove the foil/lid and cook for 30 more minutes.
8. Keep warm until ready to serve.
** Credits:
- From https://www.noracooks.com/vegan-baked-beans/
- date created: [2025-08-05 Tue]
- [2025-08-03 Sun] I made a batch using dried Great Northern beans. I let the beans soak overnight and then simmered them for about two hours... which was probably too long (beans were a bit mushy). I had cut the sugars back to about two-thirds, but it was still a bit on the sweet side; this recipe now reflects 50%. Instead of the hot sauce, I added 2 teaspoons of liquid smoke.
