#+STARTUP: showeverything
* Vegan Stuffed Mushrooms
** Ingredients:
- 5 portobello mushrooms (see notes)
- 1 tbsp oil
- 1 small/medium (110 g) onion diced
- 1 medium (100 g) pepper
- 1 tsp onion powder
- 1 tsp garlic powder
- 1/2 tsp ground cumin
- Salt, ground pepper, and chili powder to taste
- 2 cloves of garlic
- 1 cup canned (175 g) chickpeas drained and rinsed
- 1/3 cup (40 g) walnuts finely chopped
- 1 heaped tbsp (30 g) tomato paste
- 1 tbsp tamari or soy sauce
- 1/2 tbsp balsamic vinegar
- 4 tbsp dairy-free milk
- vegan cheese to taste
- Fresh herbs to garnish
** Method:
1. Preheat the oven to 360 F (180 C) and line a baking sheet with parchment paper.
2. Remove the stems of the mushrooms and chop them into pieces. Set aside.
3. Add the chickpeas to a bowl and mash them with a fork.
4. Heat oil in a large skillet, add onion, pepper, and all spices. Stir to combine and cook for 3-4 minutes.
5. Also, stir in garlic, mashed chickpeas, and walnuts.
6. Next add the tomato paste, tamari, balsamic vinegar, and dairy-free milk. Stir to combine.
7. Finally, add the chopped mushroom stems and stir. Cook for a few more minutes, then set aside.
8. Place the portobello mushrooms on the lined baking sheet and fill each mushroom with the filling until there is no filling left.
9. Bake in the oven for about 10 minutes, then add vegan cheese of choice (I used my vegan cheese sauce) and bake for a further 10 minutes. Garnish with fresh herbs and enjoy!
** Tags
IsVegan
** Credits:
- From https://elavegan.com/wprm_print/18133
- date created: [2022-07-04 Mon]
- <2022-06-28 Tue> J made these but mistakenly used cannellini beans. They were tasty.
