#+STARTUP: showeverything
* 5 minute baguette
** Ingredients:
- Flour 950g (33.5oz) use baker's flour or bread flour as called in the US (higher protein content, the one I use has 11.5g of protein per 100g)
- Salt 2x good tsp, approx 16g / 0.56oz
- Yeast ¾ tsp, approx 2g / 0.07oz
- Water 730ml / 25.7oz (I use filtered water at room temperature)
** Method:
1. Mix all the ingredients together until combined, you will see the dough will amalgamate into a ball, this should not take more than 2 minutes.
2. Cover and let it rise for 8 to 10 hours. (I leave the dough in the cold oven.)
3. Sprinkle some flour on the bench or a pizza dish/plate, scrape the dough on the dish and sprinkle again some more flour on top to avoid sticking.
   #+begin_tip
   You will need a plastic dough scraper and make sure you're not pressing the dough to keep the air inside.
   #+end_tip
4. Cut the dough in 4 (if you want 4 baguettes, but you can make 2, 3 or 5).
5. Take each piece and stretch it gently into a baguette shape and put it on a baking tray or plate with baking paper.
   #+begin_info
   This should not take more than 3 minutes and if you're well organised cleaning included.
   #+end_info
6. Bake at 480° F (250° C) for approx 25 minutes in a preheated oven depending how golden you want them.
7. /Et voila./
** Credits:
- From https://www.youtube.com/watch?v=Z-husjZkxHw
- date created: [2025-12-23 Tue]
