#+STARTUP: showeverything
* Amazing Rosemary Bread

** Ingredients:
- 1 tablespoon yeast
- 1 tablespoon sugar
- 1 cup warm water
- 2½ cups flour
- 1 teaspoon salt
- 2 tablespoons fresh rosemary
- 2 tablespoons vegan margarine

** Method:
1. Place yeast, sugar and water in large bowl or food processor and allow mixture to become bubbly. Mix in 1 tablespoon margarine, salt, and 2 cups of flour. Add one tablespoon of the fresh chopped rosemary. Knead for about 10 minutes by hand or in food processor about 5 minutes until smooth and elastic. Add more flour if necessary.
2. Oil a bowl, put dough in it and cover with a towel. Let dough rise in a warm place for one hour until doubled.
3. Punch down dough and divide in half. Let dough rest about 5 minutes.
4. Spray baking pan or cookie sheet with cooking spray. Shape the dough into 2 small rounded oval loaves. Sprinkle remaining 1 Tablespoon of rosemary over the loaves and press lightly into the surface.  Let loaves rise again until doubled, about 45 minutes.
5. Preheat oven to 375 degrees Fahrenheit. Bake for 15 to 20 minutes, until lightly browned. Carefully remove from oven, brush with remaining vegan margarine (and salt if desired).

** Yield: 
- Makes 2 loaves
- Preparation time: 2 hours, Baking time: 20 minutes

** Credits:
- http://vegweb.com/index.php?PHPSESSID=7404f53c6ca2ebfde2c6d58855366e29&action=printpage;topic=21486.0
- 2009-06-30
- date created: [2009-06-30 Tue]
