#+STARTUP: showeverything
* Artisan Breadsticks
** Ingredients:
*** Dough
- 1 1/2 cups (340g) water, lukewarm
- 3 tablespoons (25g) olive oil, divided
- 2 tablespoons (12g) King Arthur Pizza Dough Flavor, optional
- 1 teaspoon granulated sugar
- 2 teaspoons (12g) salt
- 2 tablespoons (7g) herbes de Provence, or other dried herbs
- 2 1/4 teaspoons instant yeast
- 4 1/4 cups (510g) King Arthur Unbleached Bread Flour
*** Egg Wash
**** Vegan
- 3 tablespoons unsweetened vegan milk (44mL) preferably one with a high protein content
- 1 teaspoon maple syrup or agave syrup (6.75g) use only ½ teaspoon if you don't want any hint of sweetness on your buns
- 1 teaspoon regular mustard  (5g) or dijon mustard
- 1 tablespoon mix of sesame seeds, for topping
**** Chicken-based Egg Wash
- 1 large egg beaten with 1 tablespoon water 
*** Topping
- egg wash (/either/ Vegan /or/ Chicken-based)
- 1/4 cup (43g) King Arthur Artisan Bread Topping or other seed mixture
** Method:
1. Mix and knead the dough ingredients — by hand, mixer, or bread machine set on the dough cycle — to form a slightly soft dough.
2. Cover and let rise for 1 hour, until puffy.
3. Drizzle with 1 tablespoon olive oil over a half-sheet pan (13" x 18") or other large, rimmed baking sheet.
4. Spread the dough into the pan, stretching it to the edges. If it shrinks back, let it rest for 10 minutes, and stretch again, repeating if necessary.
5. Use a lightly greased bench knife or pizza wheel to cut the dough into 12 or 13 crosswise strips, 1" wide. Then cut the dough in half lengthwise — you'll have 24 to 26 strips, each about 6 1/2" long.
6. Leave them right as they are, in the pan.
7. Cover and let the strips rise at room temperature for 45 to 60 minutes, until puffy.
8. Towards the end of the rising time, preheat the oven to 350°F.
9. Brush the strips with egg wash, and sprinkle on the topping.
10. Bake the breadsticks for 30 to 35 minutes, until they're light gold.
11. Remove the pan from the oven.
12. Once the breadsticks are cool enough to handle, cut along their score lines.
** Tags
IsVegan (or could be)
** Credits:
- From https://www.kingarthurbaking.com/recipes/artisan-breadsticks-recipe
- date created: [2022-09-05 Mon]
- [2022-09-05 Mon] Made for the Westfalls, using Penzy’s [[https://www.penzeys.com/online-catalog/tuscan-sunset/c-24/p-319/pd-s][Tuscan Sunset]], topping half with sesame seeds and the other half with everything bagel topping. Light, airy and tasty.
