#+STARTUP: showeverything
* Brötchen
** Ingredients:
*** Sponge:
- 2 cups flour
- ¾ cup room temperature water
- 2 ¼ tsp. dry yeast
*** Dough:
- 3 ⅓ to 3 ½ cups flour
- 1 cup lukewarm water
- 2 ¼ tsp. dry yeast
- 1 tbsp. honey
- 1 tbsp. Kosher salt
** Method:
1. The night before making the rolls, start by preparing the pre-dough aka sponge:
     a. Mix flour, water, and yeast in a small bowl, cover it airtight, and let it sit in the refrigerator overnight.
2. The next morning, continue with the main dough. Dissolve yeast and honey in lukewarm water in a stand mixer bowl:
     a. 2 ¼ tsp. dry yeast,1 tbsp. honey, 1 cup lukewarm water
     b. Add the flour, salt, and sponge to the bowl.
     c. Then knead all the ingredients for about 5 minutes on low speed, and then for 5 minutes on medium-high speed to form a smooth, soft dough.
     d. The dough should still be slightly sticky.
3. Cover the bowl airtight and let the dough rise for about 1 – 1 ½ hours.
4. After the resting period, turn the dough out onto a floured work surface, knead it well, and shape it into 10 equal-sized oval rolls.
5. Place the rolls on a baking sheet lined with parchment paper, cover with a clean kitchen towel, and let them rest for about 30 minutes.
6. Gently brush the rolls with water and make a lengthwise cut about ½ inch deep using a sharp knife or a lame.
7. Add about ½ cup water to the oven right before baking to create steam. (This will ensure a great texture for the rolls.)
8. Bake the rolls at 425°F in a preheated oven for about 20 minutes until golden brown.
9. Let the rolls cool on a rack and enjoy.
** Credits:
- From https://alltastesgerman.com/brotchen-authentic-german-bread-rolls/#recipe
- date created: [2025-04-10 Thu]
- [2025-04-10 Thu] They are really close to the brötchen that you get in Germany!
