#+STARTUP: showeverything
* Cheesy Herb Rolls
** Ingredients
*** Single Batch Rolls
- 3¾ cups (450g) unbleached all-purpose flour, plus more for dusting the work surface.
- 2 teaspoons salt
- ½ cup warm low fat milk (about 110 degrees)
- ½ cup heavy cream
- ⅓ cup warm water
- 2¼ teaspoons rapid rise yeast
- 2 teaspoons sugar
- 2½ tablespoons unsalted butter, melted
- ¼ cup sugar
- 1½ large eggs, beaten (crack one egg into a bowl, whisk, and then use half that amount with 1 whole egg.)
*** Double Batch Rolls
- 7½ cups (900g) unbleached all-purpose flour, plus more for dusting the work surface.
- 4 teaspoons salt
- 1 cup warm low fat milk (about 110 degrees)
- 1 cup heavy cream
- ⅔ cup warm water
- 2 scant tablespoons rapid rise yeast
- 4 teaspoons sugar
- 5 tablespoons unsalted butter, melted
- ½ cup sugar
- 3 large eggs, beaten
*** Single Batch Herbs
- ¼ teaspoon parsley
- ¼ teaspoon dill
- ¼ teaspoon thyme
- ¼ teaspoon basil
- ¼ teaspoon rosemary
- ½ cup parmesan cheese, (kraft powdered kind)
- ½ cup butter, melted
- 2 teaspoons garlic
*** Double Batch Herbs
- ½ teaspoon parsley
- ½ teaspoon dill
- ½ teaspoon thyme
- ½ teaspoon basil
- ½ teaspoon rosemary
- 1 cup parmesan cheese, (kraft powdered kind)
- 1 cup butter, melted
- 4 teaspoons garlic

** Method
*** Rolls
1. (/unnecessary/ ???Adjust oven rack to the lowest position and heat to 200 degrees. Once the oven temp reaches 200, maintain the heat for 10 minutes and turn off the oven.??? /unnecessary/)
2. Mix { 1¾ cups (210g) , 3½ cups (420g) } of the flour and the salt in a bowl.
3. Mix the milk, cream, butter, and {¼, ½} cup sugar in a saucepan and heat over medium heat until foam forms around the edges. Remove from the burner and place on a hot pad in the fridge to cool only to luke warm. You do not want cold milk, but it cannot be hot either.
4. In a glass measuring cup, add the warm water and yeast with the 2 teaspoons of sugar. Allow to foam for 5-10 minutes.
5. In a bowl of a standing mixer, add the milk mixture and about 1 cup (120g) of the flour. Using the dough hook, mix for about 30 seconds. scrape down the sides of the bowl and add the yeast mixture. beat again for 3 minutes. Add the eggs and beat for 30 seconds. Add the remaining flour and beat on medium then medium high for 1-2 minutes or until the dough is pulling away from the mixer but still slightly sticky to the touch.
6. Place in a clean, lightly oiled bowl and cover with a towel to rise for 1-2 hours, sometimes I let mine go for 3 hours.
7. Punch down the dough and place on a lightly floured surface.
8. Form into balls and then roll only the tops in butter, then herb mixture and then place in greased pie dishes (about 2 dishes), covered lightly with a towel to rise for 1 hour or until doubled in size.
9. Bake at 375 degrees for 15-20 minutes or until lightly golden on top. Serve immediately.
*** Herb Mixture
1. Mix butter and garlic in one bowl, seasoning and cheese in another.
** Credits:
http://www.ohsweetbasil.com/herby-garlicky-cheesy-bread.html
- [2016-07-03 Sun] Made for 4th of July party. They were a big hit with the crowd, but I thought they were a lot like the stuff you get at Olive Garden.
- [2020-12-25 Fri] Made for Ho-Ho-Heimburg Christmas. They went over well. *Note:* The amount of butter (½ cup) for the herb dip in the single recipe seemed to be enough for the double batch.
