#+STARTUP: showeverything
* Chewy Sourdough Italian Bread

** Ingredients:
- 1 cup (~225 grams) active sourdough starter, at its peak
- 4½ cup (540 grams) bread flour, plus more for kneading
- 1½ cup (355 ml) water
- 1 Tbsp. (21 grams) honey
- 1 Tbsp. (14 grams) olive oil
- 2½ tsp. salt
** Method:
1. Mix all ingredients except salt in a large bowl, being sure that all of the ingredients are hydrated. The dough should be shaggy and wet. Cover and allow to sit, or autolyse, for 30 minutes.
2. Sprinkle the salt over the dough and mix it in, stretching and folding the dough over itself as you go. The dough will be sticky but less so as the salt mixes in. Flour a clean work surface and turn the dough out onto it. Sprinkle the dough lightly with flour and knead gently for 5-8 minutes, adding more flour as needed. The dough should be tacky but not so sticky that it isn’t workable.
3. Once the dough is soft and pliable, form it into a ball. Oil the mixing bowl you started with and place dough in, rough side up. Move the ball of dough around in the bowl so that the smooth portion is coated in oil. Flip it over and cover tightly with a lid or plastic wrap. Set aside to ferment for 8-12 hours, or overnight.
4. In the morning, slice the dough in half while still in the bowl, being careful not to deflate it too much. Oil a baking sheet generously or line it with parchment paper. Sprinkle the oiled pan or parchment paper generously with flour or a coarse semolina or cornmeal. Flour your hands and scoop out one of the portions of dough. It will be fairly wet and sticky. Shape it roughly into a torpedo loaf, approximately 12″ long, pushing the dough together to make it as high and thin as you can. Place it on one side of the sheet pan. Repeat with the other dough.
5. Cover with a damp towel or plastic wrap and allow to proof for 1.5 – 2 hours or until it is puffy. It won’t double in size but should spring up nicely in the oven.
6. Preheat the oven to 450 degrees for 30 minutes. Remove the plastic wrap from the loaves, slash as desired with a very sharp knife, and place in hot oven. Bake for 15 minutes, rotate sheet pan, and bake an additional 10-15 minutes or until it makes a hollow sound when the bottom is thumped or it reaches an internal temperature of 190 degrees.
7. Move to a cooling rack. Serve warm, torn and dipped in olive oil or spread with butter. Or, cool completely and use for garlic bread or sub sandwiches.
** Credits:
https://www.culturesforhealth.com/learn/recipe/sourdough-recipes/chewy-sourdough-italian-bread/
