#+STARTUP: showeverything
* Cinnamon Raisin Sourdough Bread
** Ingredients:
*** Dough
- ½ cup (113g) sourdough starter, ripe (fed) or discard
- 3 cups (360g) King Arthur Unbleached All-Purpose Flour
- 2½  teaspoons instant yeast
- 1 tablespoon sugar
- 1¼  teaspoons (8g) salt
- 1 large egg
- 5 tablespoons (71g) butter, softened
- ⅔ cup (152g) lukewarm water
*** Filling
- ¼ cup (50g) sugar
- 1½ teaspoons cinnamon
- 2 teaspoons King Arthur Unbleached All-Purpose Flour
- 1 large egg, beaten with 1 tablespoon water
- ½ cup (74g) raisins

** Method:
*** To make the dough
1. Weigh your flour; or measure it by gently spooning it into a cup, then sweeping off any excess. Combine all of the dough ingredients, and mix and knead — using your hands, a stand mixer, or a bread machine set on the dough cycle — to make a soft, smooth dough.

2. Place the dough in a lightly greased container, and allow it to rise for 1 1/2 to 2 hours, until it's just about doubled in bulk.

*** To make the filling
1. While the dough is rising, make the filling by stirring together the sugar, cinnamon, and flour.

*** To finish bread
1. Gently deflate the dough, and transfer it to a lightly greased work surface.

2. Roll and pat the dough into a rough rectangle approximately 6" x 20".

3. Brush the dough with the egg/water mixture and sprinkle it evenly with the filling and raisins, leaving a bare strip about 1" wide along one short edge; this will make the log you're about to roll easier to seal.

4. Starting with the short end that's covered with filling, roll the dough into a log. Pinch the ends to seal, and pinch the long seam closed.

5. Transfer the log, seam-side down, to a lightly greased 9" x 5" loaf pan. Cover and allow the bread to rise until it's crested about 1" over the rim of the pan, about 1 hour.

6. While the dough is rising, preheat the oven to 350°F.

7. Bake the bread for 40 to 45 minutes, tenting it lightly with aluminum foil after the first 15 to 20 minutes. The bread's crust will be golden brown, and the interior of the finished loaf should measure 190°F on a digital thermometer.

8. Remove the bread from the oven, and gently loosen the edges. Turn it out of the pan, and brush the top surface with butter, if desired; this will give it a soft, satiny crust. Allow the bread to cool completely before slicing.
** Credits:
- From https://www.kingarthurbaking.com/recipes/cinnamon-raisin-sourdough-bread-recipe
- date created: [2021-08-09 Mon]
- [2021-08-09 Mon] Having had a timing issue, after the initial rise, I popped it in the refrigerator overnight; I let it warm up for an hour in the morning and all was good. A tender and tasty loaf. 
  #+begin_note
  I increased raisins to 100g which was a fine amount, but the ends were not very filled.
  #+end_note
