#+STARTUP: showeverything
* Crusty Homemade Bread
** Ingredients
- 1.5 teaspoons active dry yeast
- 1.75 cups warm water (110° to 115°)
- 3.5 cups (420 grams) plus 1 tablespoon all-purpose flour, divided
- 2 teaspoons (6 grams) salt
- 1 tablespoon cornmeal or additional flour
- 1 tablespoon sesame seeds (optional and optimal)
** Method
1. In a large bowl, dissolve yeast in warm water. Using a rubber spatula, stir in 3.5 cups flour and salt to form a soft, sticky dough. Do not knead. Cover and let rise at room temperature 1 hour.
2. Stir down dough (dough will be sticky). Turn onto a floured surface; with floured hands pat into a 9-in. square. Fold square into thirds, forming a 9x3-in. rectangle. Fold rectangle into thirds, forming a 3-in. square. Place in a large greased bowl, turning once to grease the top. Cover and let rise at room temperature until almost doubled, about 1 hour.
3. Punch down dough and repeat folding process. Return dough to bowl; refrigerate, covered, overnight.
4. Grease the bottom of a disposable foil roasting pan with at least 4-in.-high sides; dust pan with cornmeal. Turn dough onto a floured surface. Knead gently 6-8 times; shape into a 6-in. round loaf. Place into prepared pan; dust top with remaining 1 tablespoon flour or sesame seeds (not both). Cover pan and let rise at room temperature until dough expands to a 7-½-in. loaf, about 1-¼ hours.
5. Preheat oven to 500°. Using a sharp knife, make a slash (¼ in. deep) across top of loaf. Cover pan tightly with foil. Bake on lowest oven rack 25 minutes.
6. Reduce oven setting to 450°. Remove foil; bake bread until deep golden brown, 25-30 minutes. Remove loaf to a wire rack to cool.
** Credits
[2020-02-19 Wed] created
- from TasteofHome via Flipboard https://www.tasteofhome.com/recipes/crusty-homemade-bread/
- [2020-02-23 Sun] Made for TC. Fine crumb, tasty and crusty as advertised.
- [2020-03-13 Fri] Made for us, with sesame seeds. Bake at 450 for a bit shorter time and not quite as crusty (although TC liked that).
- [2020-03-16 Mon] Made for Nancy B’s birthday, with sesame seeds.
- [2020-04-05 Sun] Made during quarantine.
- [2020-04-11 Sat] Made during quarantine... for Easter dinner!
- [2020-05-02 Sat] Made for Seth Ransom. :-(
