#+STARTUP: showeverything
* Custardy Popovers
** Ingredients
- 4 eggs
- 1 cup milk
- 1 cup unbleached white flour
- ½ tsp. salt
- 4 Tbs. melted butter

** Method
1. Turn on the oven (to 375F) and put the muffin tin in while preheating.
2. Beat together the eggs and milk. Add flour and salt. Beat with a whisk until uniform. Don't over beat or whip.
3. When ready and the oven is preheated, take out the muffin tin, use a brush to coat all sides and bottom of the muffin wells with the melted butter. Work quickly before the muffin tin cools down.
4. Fill each muffin hole about ⅔ full with batter. Put tin back in the oven as quickly as you can.
5. Bake for 15 minutes in a convection oven or 35 minutes in a conventional oven without opening the oven door.
6. Take the muffins out, prick with a fork to let steam escape and help them hold their shape. Serve immediately with butter, jam and/or berries.

** Credits:
[[http://galsonfamilycookbook.blogspot.com/2010/11/custardy-popovers-from-moosewood.html][Galson Family Cookbook]], taken from the first Moosewood book
I've made these a few times; always a hit!
But you've got to eat them quick; they have a short shelf life.
