#+STARTUP: showeverything
* French Bread Rolls
French Bread Rolls are the perfect yeast bread to serve on the weekend because they're warm and fluffy on the inside, crusty on the outside, and incredibly easy to make!

** Ingredients:
- 1½ cups warm water (110°F)
- 3 teaspoons active dry yeast
- 2 tablespoons sugar
- 2 tablespoons vegetable oil
- 2 teaspoons kosher salt, divided
- 3½ (420g) cups flour
- 2 tablespoons unsalted butter, melted
- spray bottle with ice water
** Method:
1. To a stand mixer add the warm water, yeast and sugar and let sit for 10 minutes until cloudy.
2. Add the oil, half the salt and 2 cups of the flour with the dough hook and let it combine on medium speed adding the flour in ¼ cup increments until the dough starts to come together and eventually starts to pull away from the bowl, then turn up the speed and let it knead for 5 minutes.
3. Add to an oiled bowl and turn in the bowl to coat with oil then cover with a damp towel and let rise in a warm spot until it doubles in size for 60 minutes.
4. Divide the dough into 16 balls, place on a greased baking sheet and let rise for an additional 30 minutes then brush gently with butter and sprinkle with remaining salt before baking at 400°  for 18-20 minutes, spraying the dough with ice water twice mid-way through the baking process to make the crust chewier.
** Credits:
- From https://dinnerthendessert.com/crusty-french-bread-rolls/#wprm-recipe-container-40613
- date created: [2024-01-21 Sun]
- [2024-01-20 Sat] Made for T. They were tender and chewy on the inside and quite flavorful.
