#+STARTUP: showeverything
* French Bread Rolls
French Bread Rolls are the perfect yeast bread to serve on the weekend because they're warm and fluffy on the inside, crusty on the outside, and incredibly easy to make!

** Ingredients:
- 1½ cups warm water (110°F)
- 3 teaspoons active dry yeast
- 2 tablespoons sugar
- 2 tablespoons vegetable oil
- 2 teaspoons kosher salt, divided
- 3½ cups (420g = 240g + 180g) flour
- 2 tablespoons (28 g) unsalted butter, melted
- sesame seeds (/optional/)
- spray bottle with ice water
** Method:
1. To a stand mixer add the warm water, yeast and sugar and let sit for 10 minutes until cloudy.
2. Add the oil, half the salt and 2 cups of the flour with the dough hook and let it combine on medium speed, adding the flour in ¼ cup increments until the dough starts to come together and eventually starts to pull away from the bowl.
3. Turn up the speed and let it knead for 5 minutes.
4. Add to an oiled bowl and turn in the bowl to coat with oil.
5. Cover with a damp towel and let rise in a warm spot until it doubles in size for 60 minutes.
6. Divide the dough into 16 balls (~51g each), place on a greased baking sheet and let rise for an additional 30 minutes.
7. Brush gently with butter and sprinkle with remaining salt or sesame seeds.
8. Bake at 400° for 18-20 minutes, spraying the dough with ice water twice mid-way through the baking process to make the crust chewier.
** Tags:
IsFavorite
** Yield:
16 rolls
** Credits:
- From https://dinnerthendessert.com/crusty-french-bread-rolls/#wprm-recipe-container-40613
- date created: [2024-01-21 Sun]
- [2024-01-20 Sat] Made for T. They were tender and chewy on the inside and quite flavorful.
- [2025-01-11 Sat] Made for the T. and the Messners. These rolls always kill, but -- for some reason -- they seem to shine even more reheated the next day! We agree that, although not quite the same, they are reminiscent of the breakfast rolls (brötchen) we had loved in Germany.
