#+STARTUP: showeverything
* Hot Cross Buns
** Times
- PREP:  25 mins. to 35 mins.
- BAKE:  20 mins. to 20 mins.
- TOTAL:  2 hrs 45 mins. to 3 hrs 15 mins.

- YIELD: 12 to 14 buns

This soft dough is easily shaped, and makes tender, aromatic buns, ready for an icing cross on top.
** Ingredients:
*** Buns:
- ¼ cup (57g) apple juice or rum
- ½ cup (78g) mixed dried fruit
- ½ cup (78g) raisins or dried currants
- 1.25 cup (283g) milk, room temperature
- 2 large eggs, plus 1 egg yolk (save the white for the topping)
- 6 tablespoons (85g) butter, room temperature
- 2 teaspoons instant yeast
- ¼ cup (53g) light brown sugar, firmly packed
- 1 teaspoon ground cinnamon
- ¼ teaspoon ground cloves or allspice
- ¼ teaspoon ground nutmeg
- 1¾ teaspoons salt
- 1 tablespoon baking powder
- 4.5 cups (539g) King Arthur Unbleached All-Purpose Flour
*** Topping:
- 1 large egg white, reserved from above
- t Tablespoon (14g) milk
*** Icing:
- 1 cup + 2 tablespoons (128g) confectioners' sugar
- ½ teaspoon vanilla extract
- pinch of salt
- 4 teaspoons milk, or enough to make a thick, pipeable icing
** Method:
1. Lightly grease a 10" square pan or 9" x 13" pan.

2. Mix the rum or apple juice with the dried fruit and raisins, cover with plastic wrap, and microwave briefly, just till the fruit and liquid are very warm, and the plastic starts to "shrink wrap" itself over the top of the bowl. Set aside to cool to room temperature. Note: If you worry about using plastic wrap in your microwave, simply cover the bowl with a glass lid.

3. When the fruit is cool, mix together all of the dough ingredients (including the eggs and the egg yolk from the separated egg); hold out the fruit for the time being. Knead the mixture, using an electric mixer or bread machine, until the dough is soft and elastic. Mix in the fruit and any liquid not absorbed.

4. Let the dough rise for 1 hour, covered. It should become puffy, though may not double in bulk.

5. Divide the dough into billiard ball-sized pieces, about 3¾ ounces each. A heaped muffin scoop (about ⅓ cup) makes about the right portion. You'll make 12 to 14 buns. Use your greased hands to round them into balls. Arrange them in the prepared pan.

6. Cover the pan, and let the buns rise for 1 hour, or until they've puffed up and are touching one another. While the dough is rising, preheat the oven to 375 degreesF.

7. Whisk together the reserved egg white and milk, and brush it over the buns.

8. Bake the buns for 20 minutes, until they're golden brown. Remove from the oven, carefully turn the buns out of the pan (they should come out in one large piece), and transfer them to a rack to cool.

9. Mix together the icing ingredients, and when the buns are completely cool, pipe it in a cross shape atop each bun.

*** Tips from our bakers
Want to make these buns a day or so ahead of time? Try the *tangzhong technique*, a Japanese method for increasing the softness and shelf life of yeast rolls. 

- Begin by measuring out the flour and milk you'll be using in the recipe. 
- Now take 3 tablespoons of the measured flour and ½ cup of the measured milk; put them in a saucepan set over medium-high heat.
- Cook the mixture, whisking constantly, until it thickens and forms a thick slurry; this will take about 1½ to 2½ minutes. 
- Transfer the cooked mixture to a bowl, let it cool to lukewarm, then combine it with the remaining flour, milk, and other dough ingredients. 
- Proceed with the recipe as directed. 
- Well-wrapped and stored at room temperature, your finished hot cross buns should stay soft and fresh for several days.
** Credits:
https://www.kingarthurflour.com/recipes/PrintRecipe?RID=352&radio=1
