#+STARTUP: showeverything
* Irish Soda Bread
Printed from COOKS.COM

** Ingredients:
- 2 c. unsifted all-purpose flour
- 2 tbsp. sugar
- 1 tsp. baking powder
- 1 tsp. baking soda
- ½ tsp. salt
- 3 tbsp. butter, softened
- ½ c. dark seedless raisins
- 1 c. buttermilk
- 1 tbsp. butter, melted

** Method:
1. Preheat oven to 375 degrees. Using solid vegetable shortening, lightly grease the surface of a small baking sheet. Set aside until bread is shaped.
2. Assemble all ingredients for Irish soda bread. (Make bread the same day you plan to serve it.)
3. Put flour, sugar, baking powder, baking soda and salt in a sifter; sift over a large bowl.
4. Add softened butter and cut into flour mixture, using a pastry blender or fork until mixture looks like fine crumbs.
5. Add raisins and toss thoroughly.
6. Pour buttermilk into flour mixture all at once.
7. Gently toss mixture together with a fork until all dry ingredients are just moistened. Do not overmix.
8. Using hands, gently gather flour mixture together and press firmly into a ball.
9. Put dough on a lightly floured pastry cloth or board. Knead gently with the palms of your hands until dough is smooth (about 1 minute). Shape into a smooth round ball and place on the prepared baking sheet.
10. Using hands, flatten dough into a circle that is about seven inches in diameter. (Dough will be about 1½" thick.) Press a large floured knife into center of loaf, halfway through dough. Repeat, at right angle, to divide loaf into quarters.
11. Bake bread for 30 to 40 minutes, or until top is golden brown and loaf sounds hollow when tapped on the bottom and sides with a wooden spoon.
12. Remove to a wire rack to cool. Brush top with melted butter and later, dust with flour. Makes one loaf.

** Credits:
- http://www.cooks.com/rec/doc/0,194,157171-238200,00.html
- date created: [2009-05-02 Sat]
