#+STARTUP: showeverything
* Japanese Milk Bread Rolls
** Ingredients:
*** TANGZHONG (starter)
- 43g (3T) water
- 43g (3T) whole milk
- 14g (2T) King Arthur Unbleached Bread Flour or Organic Bread Flour

*** DOUGH
- 298g (2.5 cups) King Arthur Unbleached Bread Flour or Organic Bread Flour
- 18g (2T) Baker's Special Dry Milk or 11g (2T) nonfat dry milk
- 50g (¼ cup) sugar
- 1 teaspoon salt
- 1 tablespoon instant yeast
- 113g (½ cup) whole milk
- 1 large egg
- 57g (¼ cup; 4T) melted unsalted butter

** Method:
1. To make the tangzhong: Combine all of the ingredients in a small saucepan, and whisk until no lumps remain.
2. Place the saucepan over low heat, and cook the mixture, whisking constantly, until thick and the whisk leaves lines on the bottom of the pan, about 3 to 5 minutes.
3. Transfer the tangzhong to a small mixing bowl or measuring cup and let it cool to room temperature.
4. To make the dough: Combine the tangzhong with the remaining dough ingredients, then mix and knead -- by hand, mixer, or bread machine -- until a smooth, elastic dough forms.
5. Shape the dough into a ball, and let it rest in a lightly greased covered bowl for 60 to 90 minutes, until puffy but not necessarily doubled in bulk.
6. Gently deflate the dough, divide it into 8 equal pieces, and shape each piece into a ball.
7. Place the rolls into a lightly greased round bun pan. Cover the pan, and let the rolls rest for 40 to 50 minutes, until puffy. To use another pan, see "tips," below.
8. Preheat the oven to 350F. Brush the rolls with milk or egg wash (1 large egg beaten with 1 tablespoon cold water), and bake for 28 to 32 minutes, until golden brown on top; a digital thermometer inserted into the center of the middle roll should read at least 190F.
9. Remove the rolls from the oven. Allow them to cool in the pan for 10 minutes, then transfer them to a rack to cool completely.

** Yield: 8 rolls.
** Credits:
- https://www.kingarthurflour.com/recipes/japanese-milk-bread-rolls-recipe
- [2018-08-19 Sun] I make them in an 8" cake tin for T and me. Taste, light. They were a bit large; consider using a muffin pan to make 10 or 12 rolls?
- [2022-11-24 Thu] I make them for Thanksgiving at the McCaggs. Light, fluffy and tasty.
