#+STARTUP: showeverything
* Naan
** Ingredients:
- ⅜ cup (3 ounces) lukewarm water to dissolve yeast (even though the recipe calls for ¾ cup)
- 1 tsp active dry yeast
- 2 cups all-purpose flour plain flour
- 1 tsp salt
- 1 tsp sugar
- ⅛ tsp baking soda
- 2 Tbsp oil canola
- 2½ Tbsp plain yogurt
- 1 tsp clarified butter (ghee), to butter the Naan
- ¼ cup All Purpose flour for rolling
** Method:
1. Dissolve yeast in lukewarm water and let it sit for 10 minutes or until the mixture becomes frothy.
2. Add sugar, salt and baking soda to the flour and mix well.
3. Add the oil and yogurt to make crumbly dough.
4. Add the water/yeast mixture and additional water as needed to make into firm dough. Note: The dough will soften as it rises.
5. Knead the dough until smooth.
6. Cover the dough and keep in a warm place three to four hours, until nearly double in volume.
7. Heat the oven to 500°F with pizza stone approximately thirty minutes, until stone is hot. (Using a baking/pizza stone will help to give the Naan close to same kind of heat as a clay tandoor.)
8. Knead the dough for about one minute.
9. Divide dough into six equal parts and roll each piece into an oval, dusting the surface lightly with dry flour to help with the rolling.
10. Lightly wet your hands and flip the rolled Naan between your palms. Place two Naan on your baking/pizza stone and put it into the oven.
11. Bake the Naan two at a time. The Naan will take two to three minutes to cook, depending upon your oven. The baked Naan should be golden brown on top.
12. Take Naan out of the oven and brush lightly with clear butter or ghee.
13. Wait two to three minutes before baking the next Naan to give oven a chance to regain lost heat.
** Tags
Favorite
** Credits:
- From https://www.manjulaskitchen.com/Naan-bread/
- date created: [2021-12-18 Sat]
- [2021-12-17 Fri] I made a double batch for MaryAnn's birthday dinner (and we wound up eating less than half of them). The recipe called for *way* too much water; I added nearly a full cup additional flour (to a doubled recipe). But the end-product was great. I received comments that this was “probably the best Naan I’ve ever had.” They were light and fluffy on the inside and a bit crispy on the exterior. And tasty. So instead of using ¾ cup of water, consider using only ⅜ cup to dissolve yeast.
- [2023-01-26 Thu] Made for Squirrels' party. They were a hit although I may have rolled the bread a bit too thinly. They got a bit more crispy than I'd prefer.
- [2023-03-12 Sun] Made for G, MA and the Grosecloses, to popular acclaim.
