#+STARTUP: showeverything
* Pain de Campagne
** Ingredients:
*** Levain
- 50g mature whole wheat starter
- 100g water
- 100g whole wheat flour
*** Main Dough
- 200g of the levain
- 350g water
- 50g rye
- ½ tsp diastatic malt
- 450g bread flour
- 10g salt (about 0.56 Tablespoons)
** Method:
1. Mix levain ingredients. Allow to peak, between four and five hours in a 28 degrees C kitchen. It ought to have a nice fruity aroma that wasn't at all sour.
2. Disperse the levain in the water with a wire whisk until it has a good foam on top. Next, whisk in rye and malt powder. Then add bread flour with spatula and mix until all the flour has been moistened.
3. Autolyse for 50 minutes.
4. Add salt.
5. Knead to medium gluten development.
6. Bulk ferment for 1 hour with a turn at 30 minutes.
7. Pre-shape dough and allow to rest for 10 minutes.
8. Shape final dough and put into well-floured banneton.
9. Let rise for about half an hour, covered.
10. Retard dough for 12 hours in the refrigerator.
11. Insert baking stone and preheat oven to 230 degrees C (= 446 degrees F) for 30 minutes.
12. Bake with steam for 15 minutes.
13. Reduce heat to 200 C (= 392 degrees F) and bake for a further 30 - 35 minutes until golden brown.
14. Cool completely on a wire rack.
** Credits:
http://www.thefreshloaf.com/node/38229/pain-de-campagne
*** [2019-07-06 Sat] icymi
- My starter was comprised of white flour and I used KA AP flour instead of bread flour and all of the levain.
- I skipped the 12 hour dough retard.
- I made a double batch.
- *Issue*: the two loaves ran together on the peel and stone. I had to saw them apart while they were in the oven.
- Good oven spring. Moist, with a nice crumb and not too sour (although T disagreed on the latter point).
- Made French toast the next morning, but, frankly, the bread was better as plain ol' toast.
