#+STARTUP: showeverything
* Pan de Cristal
** Ingredients:
- 15g olive oil
- 500g water
- 500g King Arthur Unbleached Bread Flour
- 2.5g (¾ teaspoon) instant yeast
- 10g salt
** Method:
1. Oil a two-quart rectangular baking dish (10” x 7”) with the olive oil. If you don’t have a 2-quart dish, an 8” or 9” square pan will work. Don’t worry about any pan you use being oven-safe; you won’t be baking the bread in it.
2. To make the dough: Weigh your flour; or measure it by gently spooning it into a cup, then sweeping off any excess.
3. In a medium bowl, mix the water, flour, yeast, and salt until thoroughly combined and homogeneous. Note: The dough starts off very slack and wet. That’s OK; it will transform itself through time and folds.
4. Pour the dough into the pan. Check the dough’s temperature by inserting a digital thermometer into the center. If it's less than 72°F, move the pan to a warmer spot, e.g., your oven with the light turned on.
5. Cover the pan and allow the dough to rest for 20 minutes.
6. /Start with a bowl fold/: Use your wet hands to grab a section of dough from one side, lift it up, then press it down into the middle. Repeat this 8 to 12 times, rotating the starting point of the grab around the dough.
7. Cover the dish and allow the dough to rest for 20 minutes.
8. /Then do a coil fold/: With wet hands, reach under the dough and stretch the middle upward until the dough releases from the dish. Roll it forward off your hands, allowing it to fold over (or “coil”) on itself. This is called a coil fold. Rotate the dish 90 degrees (a quarter turn) and repeat. Continue performing this folding action until the dough feels like it won’t stretch and elongate easily, usually four to five times initially. Note: You’ll be doing this three more times, each time building strength and developing the dough. See “tips,” below, for more details,
9. Cover the pan and allow the dough to rest for 20 minutes.
10. Repeat the coil fold. Cover the bowl and allow the dough to rest for 20 minutes.
11. At this point, the dough should be easier to handle and feel tighter. Repeat the coil fold using only two or three folds this time. Cover the bowl and allow the dough to rest for 20 minutes.
12. Repeat the coil fold one last time, using only one or two folds if the dough is relatively strong. Cover the bowl and allow the dough to rest for about 80 minutes.
13. To divide the dough: As gently as possible, turn the dough out onto a heavily floured surface, maintaining the rectangle or square shape – be careful not to deflate the delicate dough. Sprinkle a generous amount of flour on top of the dough, leaving no exposed sticky spots. Then, working as gently as possible, use a bench knife or other sharp knife to divide it into four pieces. Gently place two pieces on a piece of parchment, leaving space between them. Repeat with the remaining two pieces of dough, placing them on another piece of parchment.
14. Allow the loaves to rest at room temperature for 2 hours, uncovered. While the loaves are resting, preheat the oven to 475°F with a baking stone or steel on a lower rack. Allow the oven to preheat for 1 hour to ensure it’s thoroughly heated. The loaves are ready for the oven when there are a few large bubbles on the surface of each loaf and they feel light and airy.
15. To bake the bread: Carefully slide the two loaves (still resting on the parchment) into the oven onto the preheated stone or steel. If space is tight and the full sheet of parchment won’t fit on the stone or steel, cut the parchment between the two loaves and arrange them as best you can. Allow the other two loaves to continue to rest.
16. Bake the loaves for 15 minutes, then transfer them, from the stone or steel, directly onto a rack in the upper third of the oven for an additional 13 to 15 minutes. Moving them allows the baking stone or steel to become hot again in preparation for the next two loaves. After a total of 30 minutes of baking, remove the loaves from the oven and allow them to cool on a rack.
17. Repeat the process with the two remaining loaves. Cool the bread fully before slicing.
18. /Storage information/: Wrap the bread loosely and store it at room temperature for up to several days; freeze for longer storage.

Sample timelines:  
|------------+------------+---------------|
| 7:00 a.m.  | 12:00 p.m. | Mix the dough |
| 7:20 a.m.  | 12:20 p.m. | Bowl fold     |
| 7:40 a.m.  | 12:40 p.m. | Coil fold #1  |
| 8:00 a.m.  | 1:00 p.m.  | Coil fold #2  |
| 8:20 a.m.  | 1:20 p.m.  | Coil fold #3  |
| 8:40 a.m.  | 1:40 p.m.  | Coil fold #4  |
| 10:00 a.m. | 3:00 p.m.  | Divide        |
| 12:00 noon | 5:00 p.m.  | Bake          |
|------------+------------+---------------|

** Credits:
- From [[https://www.kingarthurbaking.com/recipes/pan-de-cristal-recipe]]
- date created: [2022-02-01 Tue]
- [2022-02-01 Tue] This recipe has crazy high hydration. But it gives good directions, including videos of how to do the folds, which really do strengthen the dough. The one issue is that the bake time is way too long: 15 minutes on a hot stone and then perhaps 5 more on a rack is all that is required. More than that and you get some pretty dark crust. The bread was light and crispy, with about as much flavor as you can expect from a same-day bread.
- [2022-03-26 Sat] They really only need that first 15 minutes... 
