#+STARTUP: showeverything
* Pane Pugliese
Makes 2 loaves

** Ingredients:
*** Biga
- 0.5 cup (113g) cool water
- 1.25 cup (149g) King Arthur Unbleached All-Purpose Flour
- ⅛ teaspoon instant yeast

*** Dough
- all of the biga (above)
- 1.5 cup (340g) lukewarm water
- 4 cups (482g) King Arthur Unbleached All-Purpose Flour
- 2 teaspoons salt
- 1 teaspoon instant yeast

** Instructions
1. In a small mixing bowl, combine the water, flour, and yeast to form a soft dough. Don't knead it; just make sure all of the ingredients are well-incorporated. Set this mixture aside in a warm place, covered, for 12 to 16 hours; overnight is fine.

2. Knead all of the dough ingredients together, using a mixer or bread machine, until the dough is cohesive and elastic (though not necessarily smooth), about 10 minutes.

3. Cover the dough and let it rise in a warm place for 2 to 3 hours, gently stirring it down each hour. Letting it rise the full 3 hours will enhance the bread's flavor.

4. Lightly grease a half-sheet pan or other flat pan; or line with parchment. Scoop the very wet dough, in two separate pieces, onto the pan lengthwise, shaping each piece into a rough oval as best you can.

5. Cover the dough with heavily greased plastic wrap, and allow it to rise for about 90 minutes. It'll spread quite a bit; don't worry, it's supposed to. Towards the end of the rising time, preheat the oven to 450 degreesF.

6. Spray the loaves heavily with warm water, and bake them for 25 to 30 minutes, or until they're a deep golden brown.

7. Turn the oven off, prop the door open, transfer the loaves from the pan to the oven rack, and allow them to cool in the turned-off oven.

** Credits:
- https://www.kingarthurflour.com/recipes/pane-pugliese-recipe
- [2018-01-08 Mon] Made two loaves while I worked from home. T & I were both pleased with it overall: light and crusty. Somewhat reminiscent of [[https://www.kingarthurflour.com/recipes/no-knead-crusty-white-bread-recipe][No-knead crusty white bread]], but with a bit more character.
