#+STARTUP: showeverything
* Potica
** Ingredients:
*** Dough
- 4 tablespoons (57g) unsalted butter, softened
- ¼ cup (50g) sugar
- 1 teaspoon (6g) salt
- ¾ cup (170g) milk
- 2 large eggs
- 2½  teaspoons instant yeast or active dry yeast
- 2 teaspoons vanilla extract
- 3 cups (361g) King Arthur Unbleached All-Purpose Flour
- ¼ cup (46g) potato flour or ½ cup (46g) dried potato flakes
*** Filling
- 4½  cups (510g) chopped walnuts or pecans
- ¾ cup (149g) sugar
- 2 tablespoons (15g) King Arthur Unbleached All-Purpose Flour or 1 tablespoon Instant ClearJel
- ¼ teaspoon salt
- 2 teaspoons cinnamon
- 3 large eggs
- ¼ cup (57g) milk
- ¼ cup (78g) maple syrup
- 1 teaspoon vanilla extract
- 2 teaspoons grated orange rind (zest), optional
*** Topping
- 1 large egg, beaten with 2 tablespoons water
- ¼  cup (28g) finely chopped walnuts or pecans
** Method:
1. To make the dough: Place the butter, sugar, and salt in a large mixing bowl. Bring the milk to a simmer on the stove or in the microwave and pour over the ingredients. Stir briefly, then let the mixture cool to lukewarm.
2. While the mixture is cooling, weigh your flour; or measure it by gently spooning it into a cup, then sweeping off any excess.
3. When cooled, whisk in the eggs, yeast, and vanilla. Whisk about 1 cup of the all-purpose flour with the potato flour (or potato flakes) and stir into the wet ingredients. Add the remaining flour, mixing to form a soft dough.
4. Knead the dough for 8 to 10 minutes, until shiny and smooth. Cover the dough and let it rise for 1 hour, then refrigerate it for at least 1 hour, and as long as overnight.
5. To make the filling: Put the nuts, sugar, flour or Instant ClearJel, salt, and cinnamon in the bowl of a food processor or blender. Process in short bursts to grind the nuts.
6. With the food processor running, add the eggs, milk, maple syrup, and vanilla. Add the orange zest and pulse to incorporate.
7. To assemble: On a greased work surface, roll the dough into a 26" x 18" rectangle, with a long side facing you. Spread the filling evenly over the surface, leaving 1" of one long edge uncovered.
8. Roll the dough toward the uncovered edge, pinching to seal the seam and the ends to enclose the filling.
9. Grease two 8 1/2" x 4 1/2" loaf pans and line with parchment. Cut the rolled-up dough in half, so that you end up with two logs about 13" to 14" long.
10. Working with one piece at a time, bring the ends of the log together to make a ring shape, pinching and sealing the spot where they meet to enclose the filling. Flatten the ring gently (it'll shape itself into a 6 1/2" to 7" oblong). Settle the ring into the bottom of the pan with its two sides next to one another (not on top of each other), and the original long seam facing down. Press the ring gently to spread it over the bottom and into the corners of the pan.  
11. Repeat with the second piece of dough and the second pan.
12. Cover the loaves and let them rise until puffy, up to 1 1/2 hours. Toward the end of the rise time, preheat the oven to 350°F.
13. When the loaves have risen, brush the tops with the beaten egg and sprinkle with the finely chopped nuts.
14. Bake the loaves for 50 to 55 minutes. Check the tops after 20 minutes, tenting with foil if necessary to keep them from over-browning. The breads are done when the centers read 190°F when measured with a digital thermometer.
15. Remove from the oven and let cool in the pans on a rack for 20 minutes before tipping out of the pans and returning to the rack to finish cooling completely.
16. Store bread, well wrapped, on the counter for up to three days; freeze for longer storage.
** Credits:
- From https://www.kingarthurbaking.com/recipes/potica-recipe
- date created: [2021-03-14 Sun]
- [2021-03-14 Sun] It's a rich Slovenian bread, not far off from babka. This one is packed with pecans and cinnamony goodness, slightly sweet and citrusy.  Both Tracey and found it not too terrible.
