#+STARTUP: showeverything
* Rustic Sourdough Two Ways
** Ingredients:
- 1 cup (227g) ripe Sourdough Starter
- 1½ cups (340g) lukewarm water
- 1 teaspoon yeast
- 2½ teaspoons salt
- 5 cups (602g) all-purpose flour
- ¾ cup (96g) fruit blend (e.g., a mixture of Thompson raisins, golden raisins, dried cranberries, etc.)
- ½ cup (57g) toasted nuts (perhaps mixed variety)
** Method:
1. Combine all ingredients except for the fruit and nuts, kneading to form a smooth dough.
2. Allow the dough to rise in a covered bowl until doubled in size, about 90 minutes.
3. Gently divide the dough in half; it'll deflate somewhat.
4. Knead the fruit and nuts into half the dough.
5. Shape the dough into two rounds or oval loaves, as desired.
6. Place in flour brotforms or couche or towel-lined bowls.
7. Cover and let rise until very puffy, about 1 hour.
8. Toward the end of the rising time place a baking stone or steel in the oven and preheat to 425°.
9. Turn the risen loaves over onto a piece of parchment.
10. Spray the loaves with lukewarm water and dust generously with flour.
11. Make two fairly deep diagonal slices in each. Use firm, quick motions; a sharp knife or lame works well here.
12. Slide loaves onto the stone.
13. Bake the breads for 25 to 30 minutes, until they are a very deep golden brown.
14. Remove from the oven and cool on a rack.
** Credits:
- From King Arthur Baking Company catalog, Holiday Inspiration 2021, page 38.
- date created: [2021-11-02 Tue]
- [2021-10-06 Wed] I made both loaves. The plain one was fairly insipid. But the fruited one was quite pleasant and made lovely toast for several days.
