#+STARTUP: showeverything
* Sandwich Bread
** Ingredients:
- 4 teaspoon active dry yeast
- 1 ¼ cup warm water
- 1 cup almond milk (or any nondairy milk)
- 2 tablespoon avocado oil
- 2 tablespoon sugar
- 1 tablespoon salt (use less if on a low sodium diet)
- 3-4 cups bread flour (can substitute 1½ cups with whole wheat flour); probably need ~5 cups(!)
** Method:
1. Mix the yeast and sugar with ¼ cup of water and set aside for five minutes until it froths, indicating yeast is active.
2. To the yeast and water mixture, add the remaining cup of water, milk, oil and salt. Then add 2½ cups of bread flour or 1 cup of bread flour and 1½ cups of whole wheat flour, if using that.
3. Mix in a stand mixer on low speed or by hand until a dough forms. If it's sticky, continue adding more bread flour, a little at a time, until you have a soft and supple but not sticky or tacky dough.
4. Continue kneading for another 10 minutes.
5. Form a smooth ball with the dough and place in an oiled bowl, turning over once to cover the top with oil. Cover and let it rise in a warm place for 1 to 1 ½ hours, until doubled in volume.
6. Punch down the dough, form into a ball, and return it to the bowl to rise for another hour.
7. Grease two standard (6-cup) loaf pans. Now punch the dough down again and divide it into two. Using a rolling pin, roll out each loaf into a rectangle, about 6 X 8 inches. Roll it up into a cylinder and tuck the seams underneath. Place each loaf into a loaf pan.
8. Cover the dough loosely with oiled cling wrap or with a shower cap, and set it aside to rise for about 1 hour until the dough rises above the pan, forming a nice dome.
9. Preheat the oven to 400 degrees. Bake the loaves for 35 minutes.
10. Cool on a rack for about 10 minutes, then remove the loaves from the pan and continue cooling before you slice.
** Credits:
- From https://holycowvegan.net/perfect-sandwich-bread/#recipe
- date created: [2023-02-28 Tue]
- [2023-02-26 Sun] Made and used for cucumber finger sandwiches for a Vegan High Tea. Was well-received.
