#+STARTUP: showeverything
* Socca (Farinata)
** Ingredients:
- cup chickpea flour
- 1 teaspoon salt
- 1 teaspoon freshly ground black pepper
- 4 to 6 tablespoons olive oil
- ½ large onion, thinly sliced
- 2 teaspoons chopped fresh rosemary
** Method:
1. Heat the oven to 450°.
2. Put a well-seasoned or nonstick 12-inch pizza pan or cast-iron skillet in oven. (If you have a socca pan, obviously that will work well also.)
3. Put the chickpea flour in a bowl; add the salt and pepper.
4. Slowly add 1 cup lukewarm water, whisking to eliminate lumps.
5. Stir in 2 tablespoons olive oil.
6. Cover and let sit while the oven heats, or for as long as 12 hours. The batter should be about the consistency of heavy cream.
7. Remove the pan, pour 2 tablespoons of the oil into it and swirl.
8. Add the onions return the pan to the oven and cook, stirring once or twice, until they’re well browned, 6 to 8 minutes.
9. Stir in the rosemary.
10. Stir the onions and rosemary into the batter, then immediately pour the batter into the pan.
11. Bake for 10 to 15 minutes, or until the pancake is firm and the edges set.
12. Heat the broiler and brush the top of the pancake with 1 or 2 tablespoons of oil if it looks dry.
13. Set the pancake a few inches away from the broiler, and cook just long enough to brown it in spots.
14. Cut it into wedges, and serve hot or warm.
** Credits:
- From https://cooking.nytimes.com/recipes/1014757-socca-farinata
- date created: [2022-09-01 Thu]
