#+STARTUP: showeverything
* Soft Sourdough Sandwich Bread
** Ingredients:
*** Active Sourdough Starter
- 2 teaspoons (10 g) sourdough starter
- 3 tablespoons (25 g) all-purpose flour
- 5 teaspoons (25 g) water
*** Dough
- ¼ cup (50 g) sourdough starter (active)
- 1 cup + 2 ½ tablespoons (275 g) water
- 4 tablespoons (60 g) olive oil
- 1 tablespoon honey (maple syrup or sugar)
- 4 cups + 2 tablespoons (500 g) all-purpose flour
- 2 teaspoons (10 g) sea salt
** Method:
*** Day 1
**** 7 AM - Feed your sourdough starter
1. 12 hours before you mix the dough feed your sourdough starter.
2. Add the ingredients to a clean jar, stir, cover loosely, and let rise at room temperature, 68-72°F (20-22°C), until doubled.
**** 7 PM - Mix the dough
1. Add the dough ingredients to the bowl of a stand mixer.
2. Use a dough whisk or a stiff spatula to get the dough started.
3. Switch to your hands and mix the dough until it resembles a shaggy mess and there are no dry bits in the bowl.
4. Cover the bowl and let the dough rest for 1 hour for the flour to fully absorb the water.
**** 8 PM - Knead and First Rise
1. Mix the dough on LOW speed (3) for 8-10 minutes, using the dough hook attachment.
2. Remove the dough hook, cover the bowl, and allow the dough to rise at room temperature, 68-72°F (20-22°C), for 10-12 hours or until it has doubled in size.
*** Day 2
**** 6 AM - Shape and second rise
1. Turn the dough out onto a lightly floured work surface and gently press it into a rectangle with the short end closest to you.
2. Fold the left and right sides of the dough into the middle.
3. Starting from the end farthest from you, roll the dough towards yourself into a log shape.
4. Use your hands to gently cup the dough and pull it towards yourself to create tension on the outside.
5. Pinch the ends to seal any edges.
6. Transfer the dough, seam-side down, into a lightly greased bread pan.
7. For easier removal, you can also line the pan with parchment paper.
8. Allow the dough to rest at room temperature, uncovered until the dough has risen 1 inch above the rim of the pan, about 2-3 hours depending on the temperature of your kitchen.
**** 9 AM - Bake
1. Preheat the oven to 450°F (232°C).
2. Transfer the pan to the oven and turn the oven down to 375°F (190°C).
3. Bake for 45-50 minutes.
4. Allow the bread to cool in the pan for 10-15 minutes before transferring the loaf to a cooling rack.
** Credits:
- From https://littlespoonfarm.com/soft-sourdough-sandwich-bread-recipe/#recipe
- date created: [2025-07-24 Thu]
