#+STARTUP: showeverything
* Sourdough Cinnamon Rolls
** Ingredients:
*** Dough
- 477g all-purpose or bread flour
- 133g milk, whole (/about ½ cup/)
- 191g butter, unsalted
- 191g eggs (/about 4/)
- 48g sugar, caster
- 11g salt
- 200g sourdough starter
*** Filling
- 215g light brown sugar
- 40g all-purpose flour
- 2 tablespoons butter, unsalted and melted
- 2 teaspoons cinnamon, ground
- ¼ teaspoon salt
*** Cream Cheese Glaze
- 114g (4oz, half a block) cream cheese softened to room temperature
- 62g powdered sugar
- 37g milk, whole
- 1 teaspoon vanilla extract
** Method:
*** Mix (9:00 a.m.)
1. Cut the butter into ¼” pats and let warm to room temperature while mixing the rest of the ingredients.
2. In the bowl of a stand mixer fitted with the dough hook attachment, add the eggs, milk, sugar, and sourdough starter.
3. Whisk together until incorporated.
4. Add the flour and salt and mix on speed 1 for 3 minutes until incorporated.
5. Let the dough rest for 10 minutes.
6. After the 10-minute rest turn the mixer to speed 2 and mix for about 5-6 minutes until the dough starts to come together and all clumps have disappeared. The dough should start to pull from the sides of the bowl but it will not completely remove from the bottom. If the dough just doesn’t want to come together and it’s overly wet add a little flour, a tablespoon at a time until it comes together.
7. With the mixer set to speed 1, add the butter one pat at a time, waiting to add each until the previous is absorbed.
8. Continue until all the butter is added and the dough is shiny and smooth, this could take around 8-10 minutes.
*** Bulk fermentation (9:30 a.m. to 11:30 a.m.)
1. Transfer the mixed dough to a bulk container and let ferment for 2 hours at 75ºF (23°C).
2. Perform 3 to 4 sets of stretch and folds at 30-minute intervals.
*** Chill dough (11:30 a.m. to 2:00 p.m.)
1. Place the covered bulk fermentation container into the fridge for at least 2 hours to thoroughly chill.
*** Shape rolls (2:00 p.m.)
1. First, make the filling: In a bowl mix together the filling ingredients and set aside.
2. Next, take out your dough from the fridge, lightly flour your work surface and the dough, and roll out to an 11×21″ rectangle with a long side closest to your body.
3. Spread the filling evenly over the dough.
4. Roll the dough up away from you into a tight log.
5. Cut the log into pieces every 1¾”.
6. Transfer the cut pieces to a baking pan with space around each one.
*** Proof (2:30 p.m. to 4:30 p.m.)
1. Cover the pan and proof somewhere warm, around 77°F (25°C), for 2 to 3 hours.
     + The dough will relax and puff up during this time.
     + They’re ready to bake when the dough feels very soft and light—give the dough additional time to proof if necessary.
*** Bake (4:30 p.m.)
1. Preheat your oven to 400°F (200°C).
2. Slide the rolls into the oven once preheated and bake for 20-35 minutes.
3. Spread the glaze over the rolls once cooled.
** Credits:
- From https://www.theperfectloaf.com/sourdough-cinnamon-rolls/#tasty-recipes-11562-jump-target
- date created: [2021-10-17 Sun]
- A hit each time I’ve made them. Some say they don’t even need the glaze.
