#+STARTUP: showeverything
* Sourdough Baguettes (King Arthur)
** Ingredients:
*** For 6 baguettes or 3 Italian loaves
- 1¼  cups (283g) lukewarm water
- 2 cups (482g) sourdough starter, ripe (fed) or discard
- 4½ to 5 cups (539g to 602g) King Arthur Unbleached All-Purpose Flour
- 2½ teaspoons (15g) salt
- 2 teaspoons sugar
- 1 to 2 teaspoons instant yeast (depending on the vigor of your fed starter)
- 4 teaspoons vital wheat gluten
*** For 3 baguettes or 1½  Italian loaves
- ⅝ cups (142g) lukewarm water
- 1 cup (241g) sourdough starter, ripe (fed) or discard
- 2¼ to 2½  cups (270g to 301g) King Arthur Unbleached All-Purpose Flour
- 1¼ teaspoons (7.5g) salt
- 1 teaspoon sugar
- 1 teaspoons instant yeast (depending on the vigor of your fed starter)
- 2 teaspoons vital wheat gluten
** Method:
1. In a large bowl, combine the water, starter, and half the flour, mixing until smooth.
2. Stir in the salt, sugar, yeast, and gluten, then most of the additional flour.
3. Stir until the dough pulls away from the sides of the bowl, adding only enough additional flour as necessary; a slack (sticky) dough makes a light loaf.
4. Knead the dough for about 7 minutes in a stand mixer; or 8 to 10 minutes by hand, on a lightly greased work surface. You may also knead this dough using the dough cycle on your bread machine; once it's finished kneading, transfer it to a bowl to rise, as directed below.
5. Turn the dough into an oiled bowl, cover the bowl, and let the dough rise until doubled in bulk, about 90 minutes.
6. Gently deflate the dough, and divide it into six pieces (for thin baguettes) or three pieces (for thicker Italian loaves).
7. Shape each piece into a 16" long loaf, and place the loaves, at least 4" apart, on parchment-lined baking sheets, or in lightly greased baguette pans (French loaf pans). If you're using baguette pans, make the loaves 15" long.
8. Cover the loaves with lightly greased plastic wrap, and let them rise for 1½  to 2 hours, or until they're nice and puffy. Towards the end of the rising time, preheat your oven to 450°F.
9. For a classic look, make three diagonal slashes in each loaf, cutting about ¼" deep. For taller, rounder baguettes, don't slash.
10. Bake the baguettes for about 25 minutes, or until they're a rich golden brown. If you baked in baguette pans, remove the loaves from the oven and unmold. Turn off the oven, return the loaves (without the pan) to the oven, and crack the oven door open a few inches. If you baked on a parchment-lined baking sheet, simply turn off the oven and crack the oven door open a few inches. Letting the loaves cool right in the turned-off oven helps preserve their crunchy crust.
11. Remove the baguettes from the oven, and cool them completely on a rack. Store any leftovers in a paper bag for a day or so; paper will preserve their crunchy crust better than plastic. Freeze for longer storage.
** Credits:
- From https://www.kingarthurbaking.com/recipes/sourdough-baguettes-recipe
- date created: [2021-06-05 Sat]
- [2021-06-06 Sun] Made for Heimburg dinner. Due to a pickleball-related incident, the bread rose way too long (instead of 2 hours it was more like 3½). The bread rose but after slashing fell and was quite flat. But good flavor.
- [2022-12-06 Tue] Made again. The bread is fine but without much flavor.
