#+STARTUP: showeverything
* Sourdough Bread (New York Times)
** Ingredients:
- 20 grams mature starter, which you should keep refrigerated until you’re ready to use it
- 700 grams high-quality white bread flour, plus more for feeding starter and dusting work surfaces
- 300 grams high-quality whole-wheat flour, whole-grain rye flour, or spelt flour, or a combination
- 20 grams kosher salt or fine sea salt
- Rice flour, for dusting (optional)
** Method:
*** Day 1
1. /Feed your starter (refreshing)./

   In the morning, three days before you plan to serve your bread (Friday morning, for example, for loaves on Sunday), pull your starter from the refrigerator and decant 20 grams of it into a small, clean, clear container. Return any remaining starter to the refrigerator for future use. Stir in 100 grams of room-temperature tap water until the starter is evenly dispersed, then stir in 100 grams of white flour until you have a smooth paste.
   #+begin_note
   The yeast and bacteria in your starter become sluggish in the cool environment of your refrigerator. They must be energized through successive feedings, a process called refreshing, to be active enough to raise the dough.
   #+end_note

   #+begin_tip
   In the morning, I use *25g* of starter and mix with *25g* of water and *25g* of flour.\\
   That evening, I add *75g* of water plus *75* grams of flour.\\
   This yields 225g of ripe starter the next day.
   #+end_tip

2. /Let rise./

   Cover the container, and let sit at room temperature until it has at least doubled in volume and its surface teems with sudsy bubbles, 10 to 12 hours, depending on your kitchen’s temperature.
3. /Feed your starter a second time./

   Once the starter has doubled in size (the evening of the first day), discard all but 20 grams of starter. To the 20 grams of starter, add 100 grams of water, then mix and incorporate another 100 grams of white flour. Cover and set aside at room temperature to be used in your dough the next day.
*** Day 2
The bulk of your work occurs on this day, so you’ll want to set aside some time to tend to your dough. Depending on environmental conditions, your dough may take anywhere from five to nine hours to finish its rises. It’s not active time, but you’ll want to stay close to keep an eye on it.
1. /Mix together flour and water and let sit (autolyse)./

   Early on the second day, weigh 700 grams of white bread flour and 300 grams of whole-wheat or whole-grain rye or spelt flour (or a blend) in a large mixing bowl. Mix to combine. Weigh out 750 grams of lukewarm tap water (about 90 degrees) and add to the flours. Mix gently with a clean hand or a flexible bench scraper until all the flours are hydrated and no dry spots remain. Cover with a damp dish towel, and let sit at least 30 minutes while you wait until your starter is ready (see Step 2).
   #+begin_note
   The  Tupperware "What-a-bowl" weighs 359 grams.
   #+end_note
   #+begin_tip
   If starter is the life force of bread, then the stretchy strands known as gluten are its backbone. When two proteins in flour come into contact with water, gluten forms a network inside the dough, trapping the gas produced by the yeast. To build lots of gluten from the get-go, bakers employ a technique known as autolyse, in which flour and water are mixed and left to rest, usually before adding the starter. During autolyse, gluten bonds form that create the basic structure of the dough. As little as 30 minutes of autolyse can be effective, but generally speaking a couple of hours is optimal. It will give your gluten a head start and decrease the amount of mixing down the line.
   #+end_tip
2. /Make sure the starter is ready to use (perform a float test)./

   When the sudsy bubbles on the surface of a starter form a dome and it appears on the verge of collapse, drop about a teaspoon of starter into a small bowl of room temperature water. If it floats, the starter is full of gas and ready to use (ripe). If it sinks, let it sit, checking every 30 minutes, until you see even more activity and then try the test again.
3. /Combine the autolyse and starter./

   Add 200 grams of ripe starter to the bowl with the flour-water mixture. Pinching with your thumb, forefinger and middle finger on one hand and rotating the bowl with the other, mix until the starter is completely incorporated.
4. /Assess texture and add salt./

   At this point, the dough should be wet but also extremely extensible (having the ability to stretch without snapping back). Sprinkle 20 grams salt and 20 grams of water across the dough, and pinch, as before, to incorporate. Cover with a damp towel and let sit for 10 minutes.
   #+begin_tip
   Adding salt tightens the gluten network, so the dough will go from very extensible to more elastic (having the tendency to snap back after being stretched) and stringy.
   #+end_tip
5. /Mix the dough./

   Uncover the dough. Slide a wet hand down along the inside of the bowl and underneath the dough. Grasp a handful and stretch it upward until you feel resistance, then fold it back onto the dough mass. Repeat this motion continuously for 10 minutes, rotating the bowl about 90 degrees each time. As you work the dough, it will progress from very slack and sticky to smoother and more elastic.
6. /Check if the dough has built enough gluten (perform the windowpane test)./

   After 10 minutes of mixing, pinch off a golf ball-size piece of dough and gently stretch it with your fingertips, working it both longer and wider until you have a thin, even membrane through which light can pass. If the dough tears before this point, continue to mix and check again every 10 minutes. (If you’re mixing for more than 20 minutes and the dough is not yet at this point, feel free to move on. Your bread will still turn out.) Use a flexible bench scraper to scrape dough out onto a clean surface. Rinse the bowl to remove any dried flour, then return the dough to the damp bowl.
   #+begin_tip
   This will help determine if the dough has developed sufficient gluten to give it strength, which enables it to hold its shape.
   #+end_tip
7. /Prepare for the dough’s first rise (bulk fermentation)./

   Mark where the dough hits the side of the bowl with a piece of tape. Note the time, and the temperature of the dough. It should be 76 degrees to 80 degrees. Cover the dough with a damp towel and let sit for 60 minutes.
   #+begin_tip
   Bulk fermentation is the period after the starter has been added during which the dough undergoes its first rise. The yeast and bacteria produce gas and flavor, so a longer fermentation will result in a more flavorful bread. If your dough is above or below the optimal 76- to 80-degree range, that’s fine, just note that it will accelerate or slow the bulk fermentation accordingly. If fermentation seems to be moving slowly, you can move your dough to a warmer place, like the inside of the oven with the oven light on.
   #+end_tip
8. /Fold the dough./

   Using a wet hand and the same mixing motion as Step 5, but with a gentler touch to avoid knocking out any gas, perform four folds, making a full rotation of the bowl. Cover the bowl, wait 1 hour, then perform the same series of four folds. Cover and repeat every 60 minutes, until the dough feels pillowy and filled with air, which can take at least 3 hours and as many as 7. Each time you fold the dough, it should feel lighter and sit higher in the bowl.
   #+begin_tip
   Determining when bulk fermentation is complete can be difficult. The dough should more or less double in size — use the mark on the bowl as a reference — but that’s not a guarantee. You should see lots of bubbles on the surface and sides of the dough.
   #+end_tip
   #+begin_quote
   “It’s like cream versus whipped cream,” said Avery Ruzicka, the baker and an owner of Manresa Bread in California.
   #+end_quote

   #+begin_quote
   “You should be able to see that there’s volume to it.” Or as Ethan Pikas, of Cellar Door Provisions in Chicago, said, “It should feel very smooth and aerated. It will feel very alive.”
   #+end_quote
9. /Shape dough for the first time (pre-shaping)./

   Clear and lightly flour a work surface. Gently turn out the dough, letting its weight coax it out of the bowl and loosening the sides with the bench scraper. Divide the dough in half with the bench scraper. Using floured hands and working with one piece of dough at a time, gently pull all the edges of the dough toward the center to create a round, tidy packet. (The non-floured surface will readily stick to itself.) Use a bench scraper to turn the loose ball of dough over so it rests seam-side down. Cover with a clean towel and repeat with the second half of dough. Let both pieces of dough rest, covered, on the work surface for 20 minutes.
   #+begin_tip
   Pre-shaping the dough guarantees uniform loaf size and helps to organize the gluten strands roughly into the final shape of the baked loaves. The following rest period relaxes the gluten and makes final shaping easier, leading to bread with a better overall rise.
   #+end_tip
10. /Prepare the shaping baskets./

    As dough rests, line two baskets or mixing bowls with clean kitchen towels. Stir together a 50/50 mixture of white bread flour and rice flour. (Rice flour will prevent sticking.) Dust the interiors of the baskets generously with the 50/50 flour mixture. Set aside.
11. /Shape the dough a last time (final shaping)./

    Uncover one piece of dough and lightly dust the top with the 50/50 flour mixture. In one decisive motion, use the bench scraper to lift and turn the dough over floured-side down. Slide your fingertips beneath the dough and stretch it gently into a square shape.

    Fold the left side of the dough inward toward the center, then fold the right side inward and overtop of the left fold. Starting at the end closest to you, roll the dough away from you into a bulky spiral.
    Let the dough sit for a minute or two on its seam to help it seal, then use a bench scraper to lift up the dough and place it seam-side up in one of the prepared baskets. Lightly dust the exposed part of the dough with more of the 50/50 flour mixture, and cover with a kitchen towel. Repeat with the second piece of dough.
12. /Let the shaped dough rise inside the baskets (proofing)./

    Rest loaves at room temperature, checking on them periodically, until the surface of the dough has settled and the entire loaves have slightly increased in volume, 1 to 1½ hours.
13. /Check if dough is proofed (the poke test)./

    Press a floured finger about ½ inch into the dough. If the dough springs back immediately, it needs more time — check again every 20 minutes. But, if it springs back slowly and a slight impression remains, the dough is proofed.
14. /Chill the dough./

    Once the dough passes the poke test, cover the baskets with plastic wrap and transfer to the refrigerator. Chill overnight and up to two days before baking. The longer the dough spends in the refrigerator, the tangier the final bread will taste.
*** Day 3
1. /Prepare the oven./

   About an hour before baking, arrange a rack in the lower third of your oven and place a large, uncovered Dutch oven inside. Heat the oven to 500 degrees.
2. /Prepare the dough./

   Remove one loaf from the refrigerator and uncover. Lightly dust the exposed dough with the 50/50 flour mixture, massaging it into the surface. Place a piece of parchment paper over the basket, making sure the parchment is longer and wider than the basket by several inches. Invert the loaf onto the parchment paper. Remove the basket, then slowly peel away the towel. Dust the rounded side of the dough with more of the 50/50 flour mixture, rubbing it into the surface to coat evenly.
3. /Make a slash in the dough./

   Use a /lame/ or a serrated knife to make a long, slightly off-center slash about ¼-inch deep, angling the blade toward the midline of the loaf.
   #+begin_tip
   Slashing the bread will help the bread expand predictably in the oven.
   #+end_tip
4. /Bake the dough./

   Very carefully place the heated Dutch oven on the stovetop. Taking care not to touch the sides, use the parchment paper to lower the loaf into the Dutch oven. Cover and return it to the oven. Bake for 20 minutes. Then, carefully remove the lid and reduce the oven temperature to 450 degrees. Continue to bake the loaf uncovered until the surface is deeply browned all over, another 30 to 40 minutes. Remove the Dutch oven from the oven, and use tongs to help you pull out the loaf. Transfer the Dutch oven back to the oven, and set the oven temperature back to 500 degrees. Repeat the process with the second loaf of bread.
   #+begin_tip
   The bread is baked covered in the beginning to trap stream, which helps the loaf expand and rise as much as possible.
   #+end_tip
5. /Cut and serve!/

   Allow the loaves to cool completely, for a few hours, before cutting into them. Whole loaves can be stored uncovered at room temperature for 1 day. Once cut, bread should be stored in paper bags at room temperature and will keep for 5 days or longer. After the second day, it benefits from light toasting.
** Credits:
- date created: [2020-04-19 Sun]
- From [[https://cooking.nytimes.com/guides/59-how-to-make-sourdough-bread/][How to Make Sourdough Bread, A Guide By Claire Saffitz]]
- [2020-04-19 Sun] Made two beautiful loaves (gave one to Nancy). Since I didn't use rice flour, I had to scrape the dough off the towels before placing into Dutch oven. Also, I screwed up on the second loaf: I didn't cover the Dutch oven until the middle (instead of first) 20 minutes. It didn't rise as much as the first, but wasn't too bad.
- [2020-05-03 Sun] Made a half recipe (one loaf). I tried to optimize the stickiness by doing the final rise not over a towel but (lightly floured) parchment instead. The paper sort of worked, but was a bit of a hassle to pick out of the cooked bread, since the bread rose around it. The big problem I had is that I forgot to lower the temperature after I removed the Dutch oven top. The bread cooked quicker and was a quite a bit darker than it ought to have been.
- [2020-05-17 Sun] In a bit of a hurry, I realized that I skipped the final rise. I did pull the dough out of the refrigerator early (1 hour for one loaf and 2 hours for the other). They stuck pretty badly to the towels and didn't bake up quite as high, but seemed fine otherwise. I have one to Nancy and Pat who came for a social distancing event on the deck.
- [2020-09-20 Sun] I preformed the loaves and basically just popped them into floured towel-lined bowls. I used potato flour to keep the bread from sticking to the towel and parchment. It worked for keeping things from sticking although it burned in the oven. (Not terrible but, then again, not attractive.) The parchment got embedded in the second loaf and I had to pick out pieces of parchment.
