#+STARTUP: showeverything
* Sourdough Spelt Rye Bread 

** Ingredients:
- 200 grams 100% hydration active sourdough starter (i.e. 100 gram flour and 100 gram water)
- 675 gram water, divided
- 750 grams all-purpose spelt (or AP flour)
- 250 grams whole grain rye
- 20 grams salt

** Method:
*** Day 1:
1. Place sourdough starter in a large bowl. Pour in 60% (405 grams) of the water and mix with a wooden spoon or Danish dough whisk to break up the starter.
2. Whisk the dry ingredients together in a separate bowl and add to the sourdough/water mixture.
3. Mix using a wooden spoon or Danish dough whisk until the dough is too thick, then continue mixing with wet hands. Gradually add the rest of the water (270 grams) and mix thoroughly until the flour is completely incorporated and the dough is a shaggy mass.
4. Form the dough into a rough ball, place in a lightly greased bowl. Cover and let it rest for 20 to 30 minutes.
5. Stretch and fold the dough. Cover again and let the dough bulk ferment for two hours. Perform two stretch and folds during the first hour; once every 30 minutes. Let the dough rest for the 2nd hour.
6. Cover the dough tightly and place in the refrigerator overnight.
*** Day 2:
1. The next day, remove the dough from the refrigerator and allow it to warm up to room temperature for 1½ to 2 hours before shaping.
2. Make twenty-four 75 gram balls (or larger if you prefer); let them rest for 15 minutes.
3. Shape into small batards or tight boules and place them on cornmeal-dusted parchment paper (or a silpat).
4. Let the rolls rise at room temperature for 45 minutes.
5. While the dough is on its last rise preheat your oven to 475 degrees F. with a baking stone on the bottom rack and steam pan (or iron skillet) on the top shelf.
6. Slide the rolls onto the preheated baking stone using the back of a baking sheet or a baker's peel. Immediately throw 3 or 4 ice cubes in the steam pan to generate steam. You can also spritz the rolls once or twice during the first couple of minutes of baking.
7. Bake the rolls for about 20 minutes. After 5 minutes turn the heat down to 450 degrees F.
8. Remove the rolls from the oven and place on a wire rack to cool.

** Credits:
- From https://www.breadexperience.com/sourdough-spelt-rye-bread-rolls/
- date created: [2020-01-31 Fri]
- [2020-02-02 Sun] Made for Ken and Amy's pre-Superbowl party. The dough was kind of sticky at first, but not too bad to deal with. It produced pretty light and airy rolls with a crisp crust. Very flavorful. T wasn't thrilled with them.
