#+STARTUP: showeverything
* Sourdough Pretzels
** Ingredients:
*** Pretzels
- ¾ cup (170g) water
- 1 cup (227g) sourdough starter, unfed/discard
- 3 cups (361g) High-Gluten Flour* or King Arthur Unbleached All-Purpose Flour
- ¼ cup (35g) Baker's Special Dry Milk or nonfat dry milk
- 2 tablespoons (14g) non-diastatic malt powder or 1 tablespoon (14g) sugar
- 1 tablespoon butter or vegetable oil
- 1½ teaspoons salt
- 2 teaspoons instant yeast

*Add an additional 2 tablespoons (28g) water if using high-gluten flour.

*** Topping
- 1 tablespoon non-diastatic malt powder or sugar
- 2 tablespoons (28g) water
- pretzel salt
- 2 tablespoons (28g) melted butter, optional

** Method:
1. Prepare a baking sheet by spraying it with vegetable oil spray, or lining it with parchment paper. If you're not using King Arthur Flour's brand, grease the parchment with vegetable oil spray to make double-sure the pretzels won't stick.
2. Mix and knead the dough ingredients — by hand, mixer, or bread machine — to make a cohesive, fairly smooth dough. It should be slightly sticky; if it seems dry, knead in an additional tablespoon or two of water.
3. Cover the dough and let it rest for 45 minutes. It will rise minimally. Towards the end of the rising time, preheat the oven to 350°F.
4. Turn the dough out onto a lightly greased work surface, fold it over a few times to gently deflate it, then divide it into 12 pieces, each weighing about 2¼ to 2½ ounces.
5. Roll each piece of dough into an 18" rope. Shape each rope into a pretzel.
6. Dissolve the malt in the water. Brush the pretzels with the solution, and sprinkle lightly with coarse pretzel salt.
7. Bake the pretzels for 25 to 30 minutes, until they're a light golden brown. Note: This is correct; there's no need to let the shaped pretzels rise before baking.
8. Remove the pretzels from the oven, and brush with melted butter, if desired.

** Credits:
- From https://www.kingarthurflour.com/recipes/sourdough-pretzels-recipe
- date created: [2020-03-15 Sun]
- [2020-03-15 Sun] Let the dough rise for several hours, but it came out fine. They were better reheated (made them a tad crispier).
