#+STARTUP: showeverything
* Sourdough Hamburger Buns
** Ingredients:
*** Dough
- ¾ cup (170g) ripe sourdough starter*
- ¾ cup (170g) water, lukewarm
- 1 teaspoon instant yeast, /optional/ *
- 2 cups (240g) unbleached all-purpose flour
- ¼ cup (27g) medium rye flour, ¼ cup (28g) wheat flour, or ¼ cup (30g) unbleached all-purpose flour
- 2 tablespoons (25g) potato flour
- 2 tablespoons (14g) nonfat dry milk
- 1 ½ teaspoons (9g) table salt
- 1 tablespoon granulated sugar
- 4 tablespoons (57g) unsalted butter, softened
*** Topping
- seeds and/or seasonings, /optional/
- 1 large egg yolk beaten with 1 teaspoon water /or/
**** Vegan Egg Wash
- 3 tablespoons (44mL) unsweetened vegan milk preferably one with a high protein content
- 1 teaspoon (6.75g) maple syrup or agave syrup (use only ½ teaspoon if you don't want any hint of sweetness on your buns)
- 1 teaspoon (5g) regular mustard or dijon mustard
** Method:
1. In the bowl of your stand mixer, combine the sourdough starter, water, and yeast.
2. Weigh your flours; or measure them by scooping them into a cup and sweeping off any excess.
3. Combine the flours, dry milk, salt, and sugar, then add to the mixer bowl with the starter and water.
4. Fit your mixer with the paddle attachment and turn it to its lowest speed.
5. Mix all the ingredients together for 2 to 3 minutes to make a sticky, cohesive dough.
6. Stop the mixer, scrape the bowl, and switch to the dough hook.
7. Add the butter, then turn the mixer up a speed or two and continue to knead until the dough is smooth and elastic, about 8 to 12 minutes longer.
8. Try the windowpane test: you should be able to stretch a piece of dough until you can see through it.
9. Cover the dough and let it rest in a warm place (75°F to 80°F) for about 4 hours.
10. To de-gas and even out the temperature of the dough, stretch and fold it in the bowl two or three times during the rest.
11. You can be fairly flexible in your timing of these; one stretch and fold per hour is ideal.
12. Turn the dough out onto a lightly floured work surface and divide it into 6 pieces of equal weight; if you have a scale, each piece should weigh about 120g.
13. Shape the dough pieces into tight balls and place them on a lightly greased or parchment-lined baking sheet, or into the lightly greased wells of a hamburger bun pan.
14. A baker shaping dough into rolls by folding the corners into the center and then rounding the dough into a ball.
15. Press the balls gently to flatten them slightly; they should come close to filling the wells of the bun pan, if you're using it.
16. A baker using the palm of their hand to gently flatten each roll.
17. Cover the buns and let them rise until puffy, about 4 hours in a warm place.
18. Twenty minutes before you’re ready to bake, preheat the oven to 375°F.
19. Uncover the buns and brush them with the beaten egg yolk/water mixture.
20. Sprinkle with toppings.
21. Bake the buns for 20 to 25 minutes, until golden brown and a digital thermometer inserted into the center of one bun reads at least 190°.
22. Remove the buns from the oven and allow them to cool before serving.
23. Store buns at room temperature for several days; freeze for longer storage.
*** Tips
#+begin_tip
If you don’t want to wait for your starter to be completely ripe (or if you’d like a little added leavening insurance), add the teaspoon of optional yeast to your dough. Note that the rising/proofing times will take less than half the amount of time with the additional yeast, likely about 90 minutes (with just one round of stretching and folding the dough) for the first rise, and about 90 minutes for the second.
#+end_tip

#+begin_tip
You know your starter is ripe and ready to leaven bread when it doubles or triples in volume within 6 to 8 hours of being fed. If your starter has been refrigerated, you’ll need to give it a series of feedings at room temperature to get it to this state. Depending on the initial health of your starter, this may take just two or three feedings spaced every 12 hours, or up to five to seven days of feeding every 12 hours.
#+end_tip

#+begin_tip
Looking at the total time it takes to make them, these buns clearly require some planning. You don’t have to bake them all in one day, though. You can prepare the dough through shaping, then let the shaped buns rest at room temperature, covered, for 1 to 2 hours before transferring them to the refrigerator overnight or for up to 24 hours. When you’re ready to bake, pull the buns out of the refrigerator and leave them at room temperature, still covered, for an hour or so. Preheat the oven, uncover the buns, brush on the egg wash, and bake. You may need to extend the bake time by a couple of minutes, but the added refrigeration will also lend the buns more robust sourdough flavor.
#+end_tip
** Credits:
- From https://www.kingarthurbaking.com/recipes/sourdough-hamburger-buns-recipe
- date created: [2025-07-19 Sat]
