#+STARTUP: showeverything
* Sourdough Rye Bread with Beer
Makes 1 large loaf

** Ingredients:
- 8 oz. liquid sourdough starter, bubbly and well fed
- 12 oz. room temperature beer (such as Anchor Steam lager)
- ¾ ounce honey, (1 tablespoon)
- 5 oz. rye flour (I used light, but dark/pumpernickel would be good, too), (1 cup)
- 12 oz. white bread flour (plus extra as needed), (2¼ cups)
- 2½ teaspoons sea salt
** Method:
1. Combine all ingredients except salt in the bowl of a stand mixer in the order listed. Attach the dough hook, and knead on low speed (1 on a Kitchen Aid) until the dough is evenly moistened; it should be wet and sticky. Cover the bowl tightly with a lid or plastic wrap and let rest 20 minutes. (This is called autolyse and allows the flour to absorb some of the water, and the gluten strands to begin straightening out; it makes for less kneading in the end, and will prevent you from adding too much flour right off the bat.)
2. After 20 minutes, add the salt and mix the dough on medium-low (2 on a Kitchen Aid) for 10 minutes, adding more bread flour 1 tablespoon at a time within the first 5 minutes until the dough comes away from the sides of the bowl. After 10 minutes, the dough should be smoother, but still tacky to the touch.
3. Optionally, scrape the dough out onto a lightly floured surface and knead for a few minutes by hand, adding as little flour as necessary to keep it from sticking to your hands and the counter. It should still be a bit sticky, but should feel smooth and clay-like.
4. Place the dough in a large plastic container and cover. Allow dough to double in volume, 3 - 4 hours. (The warmer the spot you choose, the faster it will rise; the ideal temperature being 75-85º.) Alternatively, let the dough rise in the fridge or a cool place overnight. If you do, let the dough come to room temperature before shaping it.
5. Gently turn the dough out onto a lightly floured surface, pressing out the air bubbles. Shape into a boule by tucking the edges under itself, then gently rotating the dough on the surface to form a taught outer layer of dough.(Here's a quick video of how to shape a boule.) For an oval-shaped loaf, roll the boule seam-side-down, between the pads of your hands and the counter to elongate.
6. If you have a rising basket, sift a light layer of flour onto the inside, and place the boule in it upside-down, pinching the seam shut. (If you don't have a rising basket, place the boule directly on a peel or board dusted with cornmeal or flour.) Place the whole deal in a large plastic bag, such as a trash can liner. Inflate the bag and close it with a twist tie or clip. Alternatively, just use a loaf pan.
7. Let the bread rise a second time until doubled, about 1½ - 2 hours. When the bread is ready to bake, it will hold an indentation of your finger when you press it lightly, rather than springing back.
8. Bake at 425 degrees until the bread's internal temperature rises to 200 degrees, about 35 minutes.
*** Baking on a stone
1. While the bread is rising, about an hour before you're ready to bake, remove all but the lowest rack of your oven. Place a baking stone on the rack (or a heavy duty baking sheet), and place a metal, non-teflon pan of any size that you don't care about sacrificing (it will get rusty) on the floor of the oven.
2. Crank the oven up to 500º.
3. When the bread has doubled, gently turn it out onto a wooden peel dusted with flour or cornmeal. Holding alameor sharp knife at a 45º angle to the loaf, draw the blade, about 1" deep, across the top of the loaf, beginning and ending 2" from the bottoms of the boule. Make 2 or 3 diagonal slashes this way (see photo in post, above).
4. Fill a 1 cup measure with ice cubes. Quickly slip the boule off the peel and onto the stone, and toss the cubes into the hot pan on the floor of the oven. This will steam the outside of the loaf, allowing it to expand as it bakes.
5. Bake the loaf for 15 minutes without opening the oven, then turn the oven down to 450º and bake another 15 - 20 minutes or so, until the bread is a deep, burnished golden-brown and the loaf sounds hollow when thumped on the bottom. An instant read thermometer inserted into the middle should read around 200º, the temperature at which the starches in the dough are set.
*** Cool and Store
1. Let cool completely on a wire rack, 1 - 2 hours, before enjoying. When hot, the bread is still 'baking' from the residual heat and steam inside the loaf, so step away from the bread until it is truly cool.
2. This bread keeps well for more than a week. The best way to store this type of bread is in a paper bag at room temperature for a couple of days. After that, put the whole thing, paper bag and all, into a plastic bag and continue to store at room temp. After a couple of days like that, it there's any left over, cut leftovers into ½" chunks, fry in a heavy skillet in light olive oil, and toss into soups or salads for the best croutons ever.
** Credits:
- [2020-01-05 Sun] I used the Kitchen Aid but did not knead the dough, with a ~4 hour first rise and 90 minute second. I used stone ground rye and All Purpose white, with a bit of vital wheat gluten added. I baked it in a loaf pan without the stone. It turned out well, although the crumb wasn't quite as open as in the photos. But then again, I took the starter out of the frig after it had been sitting for a week. I think it would have benefited from some invigoration.
https://bojongourmet.com/beer-rye-sourdough/
- date created: [2020-01-05 Sun]
