#+STARTUP: showeverything
* Texas-Style Cornbread
This cornbread is made with cream style corn and chile peppers, along with shredded cheese.

** Ingredients:
- 1½ cups yellow cornmeal
- 1 teaspoon salt
- 1 teaspoon baking soda
- 1½ cups buttermilk
- 1 large egg, lightly beaten
- 2 tablespoons melted butter or bacon drippings
- ¼ cup chopped chile peppers, mild or hot, or use chopped and drained canned or pickled
- jalapeño chile peppers to taste
- 1 cup cream-style corn
- 1 cup shredded sharp Cheddar cheese

** Method:
1) Preparation:
2) Preheat the oven to 425 degrees or 400 degrees for a glass baking dish.
3) In mixing bowl, combine cornmeal, salt, and baking soda.
4) Add buttermilk and egg; beat until batter is smooth.
5) Place butter in 8-inch square pan or baking dish and heat in preheated oven.
6) Pour half of the batter into the hot pan.
7) Spoon cream-style corn evenly over batter, scatter chile peppers over corn layer, and sprinkle with the shredded cheese.
8) Top with remaining batter.
9) Bake cornbread until golden brown, about 20 to 25 minutes. Serve hot.

** Yield: 
Serves 6 to 8.

** Credits:
- By Diana Rattray, About.com
- http://southernfood.about.com/od/cornbread/r/bl01002b.htm
- date created: [2009-05-02 Sat]
