#+STARTUP: showeverything
* Vegan Burger Buns
** Ingredients:
*** Burger Buns
- 4 ¾ cups all purpose flour + extra for kneading (570g)
- 2 tablespoons granulated sugar (24g) or liquid such as maple syrup or agave
- 2 ¼ teaspoons instant yeast (about 1 packet) (7g)
- 2 teaspoons sea salt (12g)
- 1 ½ cups warm water (not hot - warm to touch)  (354mL) ranging between 110 to 120°F
- 4 tablespoons olive oil (60mL) or any oil
*** Vegan Egg Wash
- 3 tablespoons unsweetened vegan milk (44mL) preferably one with a high protein content
- 1 teaspoon maple syrup or agave syrup (6.75g) use only ½ teaspoon if you don't want any hint of sweetness on your buns
- 1 teaspoon regular mustard  (5g) or dijon mustard
- 1 tablespoon mix of sesame seeds, for topping
** Method:
1. In a large bowl, add the flour, sugar, yeast, and salt. Whisk the ingredients together. 
2. Create a well in the centre of the flour. Slowly add the warm water and olive oil to the dry ingredients, and then mix together with a spatula until just incorporated. The dough should look shaggy. 
3. Flour a clean surface, and then pour/add the dough onto the surface. Flour your hands and fold the dough together. Knead the dough for about 8-10 minutes with your hands and knuckles. The dough might be sticky at first, but you can add up to ¼ cup flour while flouring and kneading to make it easier to manage. You want the end dough ball to be smooth, with slight dimples with a bit of tension formed.
4. Lightly grease the ball of dough with some additional oil and place back into the bowl in a ball. Cover the bowl with a plastic wrap or a kitchen towel and let it sit for at least 1 hour on the counter in a warm area. If your kitchen is too cold, you can place it in your OFF oven with the pilot light on which will provide enough residual heat for it to rise. The dough should rise and double in size.
5. Punch down the dough and fold over.
6. Divide the dough into 8 equal balls and roll each into a ball. Using your fingers, pinch and pull the undersides to shape each ball round. Now would be a great time to check out my highlight on Instagram where I video'd this for clarification! But you essentially want to make them round.
7. Line up the balls, about 4 inches apart if you don't want them to spread into one another/touch, on one or two baking sheets (depending on the size or your baking sheet - you want them decently spread out since they'll puff up, then spread again while baking).
8. Cover with a light kitchen towel and allow the balls to proof/rise for another 45 minutes.
9. You can also begin preheating your oven to 400°F/200°C within the last 20 minutes so it's ready when they're done rising.
10. Using a silicone brush/pastry brush, brush the vegan egg wash over the buns and the sides. Sprinkle some sesame seeds over the top and any other seeds you might desire.
11. Bake your buns for 15 minutes in the oven. Remove, and allow to cool on the baking sheet for about 5 minutes, then transfer to your cooling rack. Allow to cool fully. The buns also get much softer once they begin to cool.
12. Slice, tear, slather in butter, and enjoy!
*** Vegan Egg Wash
1. Mix the vegan milk, maple syrup/agave and the mustard thoroughly together to combine.
#+begin_tip
If you don't want any sweetness, you can lower this to ½ teaspoon maply syrup/agave. You don't have to use all of the vegan egg wash, just as much as you desire for a golden brown top.
#+end_tip
** Tags
IsVegan
** Credits:
- From https://jessicainthekitchen.com/vegan-burger-buns-soft-and-fluffy/
- date created: [2022-02-27 Sun]
- [2022-02-26 Sat] Made Tofu banh mi sliders for T, Greg and MaryAnn with these buns. These were very good buns, but I made eight buns out of them and they were of a good size for burgers (as advertised). They were too large for sliders (/my bad!/). Next time I’d try making twelve (or sixteen?) buns for sliders.
- [2022-05-02 Mon] Made for Louise and Todd. I did form sixteen 63-gram buns and they were the perfect size. At bake time I also baked the tofu and roasted a pan of cauliflower so the bottom of the buns weren't as crisp as they ought to be.
