#+STARTUP: showeverything
* Za'atar-Rubbed Pitas
** Ingredients:
- 5 tablespoons extra-virgin olive oil
- 4 teaspoons za’atar, divided
- 1/8 ounce (1/2 envelope) instant yeast
- 2/3 cup (180 milliliters) lukewarm water
- 2 cups (250 grams) all purpose flour, plus more for dusting
- 1 teaspoon fine sea salt
** Method:
1. In a small bowl, stir together 3 tablespoons olive oil and the za'atar.
2. In a small bowl, stir the yeast into the water and let stand for 5 minutes.
3. In a large bowl, whisk together the flour, salt and the remaining 2 tablespoons olive oil; then add the yeast and using your hands, combine the mixture until a dough forms.
4. Knead the dough in the bowl for a few minutes, then cover the bowl with plastic wrap and let stand somewhere warm, until doubled in size, about 1 hour.
5. (/optionally/) Preheat the oven to 200°.
6. Divide the dough into 6 equal balls.
7. Lightly dust your work surface with flour and roll out each ball of dough into a disk about 1/4-inch thick.
8. Let the disks rest for 10 minutes.
9. When you’re ready to cook the pitas, place a large, heavy skillet over medium-high heat. Once hot, place a dough disk and cook on one side until the edges begin to come away from the pan, about 45 seconds.
10. Flip the pita it over and cook until very lightly browned, 30 to 45 seconds.
11. Keep the pita warm in the oven while you repeat with the remaining dough disks.
12. Rub the za’atar oil over the surface of each pita. Serve right away or keep warm until ready to serve.
** Credits:
- From https://www.washingtonpost.com/recipes/zaatar-rubbed-pitas/17240/
- date created: [2023-02-20 Mon]
- [2023-02-19 Sun] Made for T. She liked them, but I would prefer naan.
