#+STARTUP: showeverything
* Claridge's Scones

** Ingredients:
- 11½	ounces (330 g.) plain flour, plus extra for dusting
- 2¼	ounces (60 g.) caster sugar
- 1½	tablespoons baking powder
- ¼	teaspoon salt
- 3¼	ounces cold unsalted butter, cubed
- 2½	ounces (70 g.) raisins (optional)
- 3¾	ounces (fluid ounce) (110 ml.) buttermilk
- 3	ounces (fluid ounce) (90 ml.) milk
- 1	beaten with a pinch of salt, for the egg wash

** Method:
1. In a large bowl, combine the flour, sugar, baking powder and salt, then add the butter and rub into the flour mixture with your fingers until you have a fine crumb (you could also pulse this five to six times in a food processor to achieve the same sandy texture, but it’s almost as fast to work by hand).
2. If you’re making raisin scones, stir the raisins in now.
3. Transfer to a smaller container, cover and leave to rest in the refrigerator overnight, or until thoroughly chilled.
4. The next morning, preheat the oven to 475 degrees Fahrenheit (240 degrees Celsius), Gas Mark 9.
5. Transfer the butter and flour mixture to the standing mixer. Slowly mix in the buttermilk and milk until the dough comes together.
6. On a lightly floured surface, roll out the dough to form a circle, about 8 inches (21 cm.) in diameter and ¾ inch (2 cm.) thick, then cut out 12 scones using the pastry cutter. Transfer the scones to the prepared baking tray.
7. Using a pastry brush, carefully brush the tops with the egg wash. We like to let our scones sit out for 20 minutes at room temperature to give the baking powder a chance to activate before we bake them.
8. Bake until evenly golden, about 12–13 minutes. Leave to cool for 5 minutes, then serve warm.
9. To serve: We strongly suggest serving these only on the day of baking. Leftover scones can be frozen and will remain good for up to three weeks: as needed, defrost completely, then reheat in a preheated 350 degree Fahrenheit (180 degree Celsius), Gas Mark 4 oven for 3 minutes.

** Yield:
Makes: 12 small scones 
Prep time: 4 hrs 40 min 
Cook time: 12 min

** Credits:
https://food52.com/recipes/80618-claridge-s-scones

[2019-03-17 Sun]: Made for TC. The batter was /very/ sticky. I couldn't think of slicing the dough, so I used a biscuit cutter to roughly shape and move a bit of dough to the pan. The cutter I used was too large (4"?) so I lowered the heat to 450 degrees, but the scones turned out fine. (I did have them spend a bit of time on convection to crisp them up.) I also sprinkled with some coarse sugar. Oh yeah, and half of the flour I used was [[https://www.whitelily.com/white-lily-biscuits][White Lily]]. And oh yeah, instead of raisins, I threw some frozen blueberries in. The dough turned purple, but it was ok.
