#+STARTUP: showeverything
* Gingerbread Granola
** Ingredients:
*** Dry
- 293 g rolled oats (GF for gluten-free eaters)
- 193 g raw nuts (I used almonds, pecans, and a few walnuts)
- 37 g organic cane sugar (or sub extra molasses or maple syrup mixed in with wet ingredients)
- ¼ tsp sea salt
- 1½ tsp ground cinnamon
- ¾ tsp ground ginger
- 1 pinch ground cloves (optional)
*** Wet
- 60 ml coconut or olive oil
- 80 ml maple syrup (sub agave, or honey if not vegan)
- 30 ml molasses
- 1 tsp vanilla extract (optional)

** Method:
1. Preheat oven to 325 degrees F (162 C).
2. Mix the dry ingredients together in a large bowl.
3. In a small saucepan over medium low heat, warm the coconut oil, maple syrup, molasses and vanilla extract. Pour over the dry ingredients and mix well.
4. Spread the mixture evenly onto a a large baking sheet and bake for 18–22 minutes, stirring near the halfway point to ensure even cooking. The coconut oil will help this granola crisp up nicely, but be sure to watch it carefully as it browns quickly.
5. Once the granola is visibly browned (about 19 minutes for me), remove from the oven and let cool completely on the pan before storing. Consider turning the oven off and leaving the pan in it for the granola to get extra crispy.
6. Keep in a container that has an air-tight seal and it should keep for a few weeks.

** Yield:
10½-cup servings

** Credits:
- https://minimalistbaker.com/gingerbread-granola/
- date created: [2019-12-02 Mon]
