#+STARTUP: showeverything
* Hollandaise Sauce (Food Network)
** Ingredients:
- 4 egg yolks
- 1 tablespoon freshly squeezed lemon juice
- ½ cup unsalted butter, melted (1 stick)
- Pinch cayenne
- Pinch salt
** Method:
1. Vigorously whisk the egg yolks and lemon juice together in a stainless steel bowl and until the mixture is thickened and doubled in volume.
2. Place the bowl over a saucepan containing barely simmering water (or use a double boiler,) the water should not touch the bottom of the bowl.
3. Continue to whisk rapidly. Be careful not to let the eggs get too hot or they will scramble.
4. Slowly drizzle in the melted butter and continue to whisk until the sauce is thickened and doubled in volume.
5. Remove from heat, whisk in cayenne and salt.
6. Cover and place in a warm spot until ready to use for the eggs benedict. If the sauce gets too thick, whisk in a few drops of warm water before serving.
*** Yield
1 cup sauce
*** Credits:
- date created: [2021-04-04 Sun]
- https://www-foodnetwork-com.cdn.ampproject.org/v/s/www.foodnetwork.com/recipes/tyler-florence/hollandaise-sauce-recipe-1910043.amp?amp_js_v=a6
- [2021-04-04 Sun] Made for Easter brunch Veggie Benes. Everythhing about it was good: texture, taste, appearance.... until the final step. I had had a nice, velvety smooth creamy texture and then put the pot in the warming oven for too long: the sauce curdled a bit.
