#+STARTUP: showeverything
* Peanut Dipping Sauce
** Ingredients:
- ¾ cup creamy peanut butter
- ¼ cup rice vinegar
- ⅓ cup reduced sodium tamari or reduced-sodium soy sauce
- 3 tablespoons honey
- 1 ½ teaspoons grated fresh ginger or ½ teaspoon ground ginger
- 1 to 2 medium cloves garlic, pressed or minced, to taste
- ¼ teaspoon red pepper flakes, plus more for sprinkling
- 2 to 4 tablespoons water or coconut milk, or as necessary to reach your desired consistency
- Optional garnishes: sprinkling of chopped roasted peanuts and additional red pepper flakes
** Method:
1. In a 2-cup liquid measuring cup or medium-sized mixing bowl, whisk together the ingredients until well blended. If your peanut butter is particularly thick, you may need to use the full 4 tablespoons of water to thin out the mixture (or more, if necessary).
2. Feel free to adjust to taste here—for example, sometimes I want my sauce more savory and add another clove of garlic, or a little sweeter, so I add extra honey.
3. If you’re serving the sauce as a party dip, transfer it to a serving bowl and sprinkle with chopped peanuts and red pepper flakes for some visual interest!
** Credits:
- From https://cookieandkate.com/peanut-dipping-sauce/#tasty-recipes-23875-jump-target
- date created: [2023-02-20 Mon]
- [2023-02-18 Sat] Made for T, Greg and Mary Ann as a dipping sauce for baked tofu. Yum!
