#+STARTUP: showeverything
* Oat Milk
** Ingredients:
- ½ cup whole rolled oats
- 3 cups water
- 2 teaspoons maple syrup
- ½ teaspoon vanilla extract
- ⅛ teaspoon sea salt
- ¼ cup flaked coconut (/optional/)
** Method:
1. Combine the oats, water, maple syrup, vanilla, and salt in a blender and blend for 30 seconds.
2. Place a fine mesh strainer over a large bowl and strain the milk without pushing any excess pulp through the strainer. This will create a creamier texture that’s not gritty or gummy.
3. Add more maple syrup, to taste, if desired. Chill overnight.
   #+begin_note
   If you want to drink your oat milk right away, I recommend adding ice - it's flavor is best when well chilled.
   #+end_note

#+begin_note
As the oat milk sits in the fridge, natural separation will occur. You can shake it, if you like, but I like it's texture best when I leave pulp at the bottom and pour off the top.
#+end_note

** Credits:
- From https://www.loveandlemons.com/oat-milk/#wprm-recipe-container-42113
- date created: [2023-02-10 Fri]
- [2023-03-01 Wed] I like to shake the milk each time before I use it because otherwise it is quite thin. But shaking it does make it a tiny bit slimy.
