#+STARTUP: showeverything
* Sangria
Depending on the type of red wine you use, whether it is light bodied like a Beaujolais or deep and rich like a Cabernet, add the sparkling water to taste. Sangria is best enjoyed the day it is made, otherwise the oils from the citrus rind begin to impart flavor.

Prep Time: 15 minutes
Total Time: 2 hours
Yield: About 1½ quarts

** Ingredients
- 1 (750-ml) bottle red wine
- ¼ cup brandy
- ¼ cup orange flavored liqueur (recommended: triple sec or Grand Marnier)
- 2 tablespoons fresh lime juice
- 2 tablespoons fresh orange juice
- ¼ cup sugar
- ½ orange, thinly sliced
- ½ lemon, thinly sliced
- 1 unwaxed apple, cored, and cut into thin wedges
- 1 (750-ml) bottle sparkling water, or to taste, chilled

** Method:
1. Combine everything but the sparkling water in a large plastic container or glass pitchers.
2. Cover and chill completely, 1 to 2 hours. When ready to serve, add 2 cups of the sparkling water, adding more to taste, if desired.

** Credits:
- http://emerils.com/print/124088
- Made for Jan's Ice Cream Social [2017-06-13 Tue]
    + swapped strawberries for apples and cranberry juice or orange
