#+STARTUP: showeverything
* Habanero Hot Sauce

** Ingredients
- 5 garlic cloves, unpeeled
- ½ cup peeled, roughly chopped carrot (you'll need 1 medium carrot)
- ½ cup roughly chopped white onion (you'll need about half of a small onion)
- 12 medium (about 5 ounces) orange habanero chiles, stemmed
- 1 cup apple cider vinegar
- About 2 teaspoons Salt
- ¼ teaspoon Sugar

** Method
1. Roast the garlic in a skillet over medium heat, turning regularly until soft and blackened in spots, 10 to 15 minutes. Cool and peel.

2. In a small saucepan, combine the carrot, onion and habanero chiles with the vinegar and 1 cup water. Partially cover and simmer over medium-low heat until the carrots are thoroughly tender, about 10 minutes.

3. Pour into a blender jar, add the roasted garlic, salt and sugar. Blend until smooth. Thin with a little additional water if you think your hot sauce is too thick. Taste and season with additional salt if you think necessary.

4. Pour into jars or bottles and store in the refrigerator until you're ready to add some dazzle to a dish.

** Yield
- Servings: 2cups

** Credits
- http://www.rickbayless.com/wp-content/plugins/wp-ultimate-recipe/template/recipe_print.php
- Recipe from Season 5 of Mexico-One Plate at a Time
