#+STARTUP: showeverything
* Asparagus Frittata with Basil, Shallots and Parmesan

** Ingredients:
- 1 pound thin asparagus
- 2 Tablespoons extra-virgin olive oil
- 3 medium shallots, minced (onions will do in a pinch!)
- 6 large eggs -- egg beaters work just fine!
- ½ cup freshly grated Parmigiano-Reggiano cheese (I use Pecorino Romano)
- ¼ cup shredded fresh basil leaves (I use 1 tsp dried)
- kosher salt and freshly ground black pepper

** Method:
1. Snap and discard tough asparagus ends.
2. Slice the asparagus on the bias into 1-inch-long pieces.
3. Steam the asparagus in a bamboo steamer (or boil in salt water for 1½ minutes), until almost tender.
4. Preheat the broiler.
5. Heat the oil in a 10-inch nonstick skillet with an oven proof handle.
6. Swirl the oil to coat the bottom of the pan evenly.
7. Add the shallots and saute over medium heat until translucent, about 3 minutes.
8. Add the asparagus and cook for 30 seconds.
9. In a medium bowl, use a fork to lightly beat the eggs, cheese, basil and salt and pepper.
10. Add the egg mixture to the pan and stir gently with a fork to incorporate the vegetables.
11. Cook over medium-low heat, occasionally sliding a spatula around the edges of the pan to loosen the frittata as it sets.
12. Continue cooking until the frittata is set, except for the top, about 8 minutes.
13. Place the pan directly under the broiler and cook just until the top is golden brown and set, 1 to 2 minutes.
    #+begin_tip
    Do not let the frittata burn!
    #+end_tip
15. Invert the frittata onto a large platter.
16. (Optionally sprinkle with a little kosher salt.)
17. Cut it into wedges and serve.
    #+begin_tip
    The frittata may also be cooled to room temperature and then cut and served.
    #+end_tip

** Credits:
- Recipe source: The Complete Italian Vegetarian Cookbook, by Jack Bishop, page 245.
- As served at Easter Brunch at Tracey and John's, April 2004.
- date created: [2007-06-27 Wed]
