#+STARTUP: showeverything
* Asparagus Frittata with Basil, Shallots and Parmesan

** Ingredients:
- 1 pound thin asparagus
- 2 Tbls extra-virgin olive oil
- 3 medium shallots, minced (onions will do in a pinch!)
- 6 large eggs -- egg beaters work just fine!
- ½ cup freshly grated Parmigiano-Reggiano cheese (I use Pecorino Romano)
- ¼ cup shredded fresh basil leaves (I use 1 tsp dried)
- kosher salt and freshly ground black pepper

** Method:
1. Snap and discard tough asparagus ends. Slice the asparagus on the bias into 1-inch-long pieces. Steam the asparagus in a bamboo steamer (or boil in salt water for 1½ minutes), until almost tender.
2. Preheat the broiler. Heat the oil in a 10-inch nonstick skillet with an oven proof handle. Swirl the oil to coat the bottom of the pan evenly. Add the shallots and saute over medium heat until translucent, about 3 minutes. Add the asparagus and cook for 30 seconds. 
3. In a medium bowl, use a fork to lightly beat the eggs, cheese, basil and salt and pepper. Add the egg mixture to the pan and stir gently with a fork to incorporate the vegetables. Cook over medium-low heat, occasionally sliding a spatula around the edges of the pan to loosen the frittata as it sets. Continue cooking until the frittata is set, except for the top, about 8 minutes.
4. Place the pan directly under the broiler and cook just until the top is golden brown and set, 1 to 2 minutes. Do not let the frittata burn.
5. Invert the frittata onto a large platter. (Optionally sprinkle with a little kosher salt.) Cut it into wedges and serve. The frittata may also be cooled to room temperature and then cut and served. 

** Credits:
- [As served at Easter Brunch at Tracey and John's, April 2004. Recipe source: The Complete Italian Vegetarian Cookbook, by Jack Bishop, page 245.]
- date created: [2007-06-27 Wed]
