#+STARTUP: showeverything
* Baked Tofu With Peanut Sauce and Coconut-Lime Rice
** Ingredients:
- 2 tablespoons peanut or vegetable oil, plus more for brushing the pan and drizzling
- ⅔ cup lime juice (from about 5 limes), and zest of 1 lime
- Kosher salt
- 8 baby bell peppers or 1 medium bell pepper (any color will do), stemmed and thinly sliced lengthwise
- Black pepper
- 1 cup long-grain rice like jasmine or basmati
- ½ cup full-fat coconut milk
- 1 cup smooth, natural peanut butter
- 1 tablespoon red miso
- 1 tablespoon grated ginger
- 1 tablespoon fish sauce (optional)
- 2 teaspoons chopped habanero pepper, stem and seeds removed, or 1 tablespoon sambal
- 2 tablespoons buckwheat honey or molasses
- 2 (14-ounce) package extra-firm tofu, drained and sliced crosswise, ¼-inch thick
- 3 cups peppery greens, like arugula, mizuna or baby mustard greens
- 2 scallions, trimmed and thinly sliced
** Method:
1. Heat the oven to 450 degrees and lightly brush a large rimmed sheet pan with oil.
2. In a small bowl, stir 4 tablespoons lime juice with ½ teaspoon salt until salt dissolves.
3. Add the sliced peppers, a few cracks of black pepper and set aside.
4. In a small pot, combine the rice with 1 cup water and the coconut milk. Season with salt and bring to a simmer. Cover and cook over medium-low until the rice is just tender, 12 to 15 minutes. Remove from the heat and let sit, covered, until ready to serve.
5. In a medium bowl, whisk 4 tablespoons lime juice with the peanut butter, miso, ginger, fish sauce (if using), habanero, 2 tablespoons oil, 1 tablespoon honey and ¾ cup water. Stir until smooth and season to taste with salt.
6. Arrange the tofu pieces in a single layer on the oiled baking sheet and season with salt. Spoon about 2 tablespoons of the peanut sauce over each, covering the top and allowing the sauce to run down and coat the sides. Drizzle the tops with some oil, and roast until glaze is set, deep brown and caramelized along the edges, 18 to 20 minutes.
7. Add the remaining lime juice and 1 tablespoon honey to the leftover peanut sauce in the bowl to make the dressing; set aside.
8. Divide the greens among bowls. Add the lime zest and half the sliced scallions to the rice, then fluff with a fork. Top the greens with the rice, then the tofu. Spoon the peanut dressing over everything, and garnish with the drained pickled peppers and remaining sliced scallions.
** Credits:
- From https://cooking.nytimes.com/recipes/1020530-baked-tofu-with-peanut-sauce-and-coconut-lime-rice
- YIELD: 4 servings
- TIME: 25 minutes
- date created: [2021-01-27 Wed]
- [2022-02-19 Sat] Lots of interesting flavors going on which work well together. This took about 90 minutes from start to finish, so allocate time for these many steps. The rice was tasty, but a bit too crunchy. I’d use more than a cup of water next time (maybe 1½ cups?)
