#+STARTUP: showeverything
* Baked Risotto with Roasted Vegetables
** Ingredients:
- 1 tablespoon extra-virgin olive oil
- ½ onion, finely chopped
- ¾ cup (150 g) Arborio rice
- ¼ cup (60 ml) dry white wine
- 2 to 2¼  cups (480 to 540 ml) hot water or broth
- ¾ teaspoon kosher salt
- Pinch of freshly ground black pepper
- 1 to 2 tablespoons unsalted butter
- ¼  cup (30 g) freshly grated Parmigiano-Reggiano cheese, plus more for garnish

** Method:
1. Preheat the oven to 400°F / 200°C / gas 6.
2. Roast the vegetables on a single baking sheet/tray on the top rack of the oven (the risotto will bake on the bottom rack).
3. Meanwhile, heat the olive oil in an ovenproof saucepan or Dutch oven over medium-high heat.
4. Add the onion and cook, stirring, until it is soft and translucent, about 3 minutes.
5. Add the rice and stir to coat with the oil.
6. Stir in the wine and cook until the wine has evaporated, 1 minute more.
7. Stir in 2 cups (480 ml) of the hot water or broth, salt, and pepper, and bring to a boil.
8. Cover and transfer to the oven.
9. Bake on the bottom rack during the last 25 minutes of roasting time for the vegetables.
10. After 25 minutes, check the risotto. Most of the liquid should be absorbed and the rice just cooked.
11. Remove the risotto from the oven and stir in another ½ cup (120 ml) hot cups of water or broth and the butter and cheese.
12. Serve topped with roasted vegetables with thin shavings of Parmigiano-Reggiano.
** Credits:
- From https://www.epicurious.com/recipes/food/views/baked-risotto-with-roasted-vegetables-395552
- date created: [2021-07-31 Sat]
