#+STARTUP: showeverything
* BBQ Chickpea and Carrot Sliders
** Ingredients:
- 1 medium onion, peeled and thinly sliced or julienne
- ½ teaspoon olive oil (optional)
- 1 bag (8 oz.) of shredded carrots
- 1 can (15 oz.) chickpeas, drained, rinsed and lightly crushed
- ¾ cup of Smoky BBQ Sauce, or your favorite store-bought variety
- 3 tablespoons apple cider vinegar
- 1 tablespoon maple syrup
- ½ cup light beer, (optional) if not using, increase the low sodium vegetable stock by ½ cup
- ¾ cup vegetable stock, low sodium
- 1 tablespoon Sriracha or hot sauce of choice
- 1 teaspoon garlic powder
- 2 teaspoons onion powder
- 1 teaspoon sea salt (optional)
- Handful of cilantro, chopped (optional)
*** Toppings:
- 1 cup thin shaved cabbage
- 1 cup sliced pickles
** Method:
1. Put all the ingredients except the cilantro and toppings into a large saucepan or cook pot.
2. Set the pan or pot on high heat for 4+ hours until the carrots are wicked tender and the liquid has thickened up.
3. Add chopped cilantro and mix.
4. Once the chickpea and carrot mixture is ready, assemble the sliders.
5. If the buns are not as soft as you would like, lightly toast them before using.
6. On each side of the bread add a condiment of your choice.
7. Pile on the BBQ mixture.
8. Top with shaved cabbage and sliced pickles. Don’t forget the paper towels when serving these!
#+begin_tip
To increase the protein, swap out the bag of carrots for your choice of 12 ounces of thinly sliced tofu, tempeh or other plant-based meat.
#+end_tip

#+begin_tip
Top your sliders with fresh thinly sliced red chilies if you like an extra kick.
#+end_tip
** Credits:
- From https://gamechangersmovie.com/recipes/bbq-chickpea-and-carrot-sliders via Jan Messner
- date created: [2025-07-06 Sun]
- Jan only cooks this for about an hour on medium heat. She does not add maple syrup, salt or spices; she uses Stubbs Spicy BBQ sauce instead.
