#+STARTUP: showeverything
* Bean and Cheese Burritos
** Ingredients:
- 4 tablespoons safflower or canola oil
- ½ cup finely chopped yellow onion (from ½ medium onion)
- ½ cup finely chopped green bell pepper (from ½ pepper)
- salt and black pepper
- 2 garlic cloves, minced
- 2 (15-ounce) cans pinto beans, ½ cup of bean liquid reserved and the rest drained
- ½ cup store-bought or homemade pico de gallo or salsa
- ¼ teaspoon smoked paprika
- 6 (9- to 10-inch) flour tortillas
- 2 cups shredded sharp Cheddar (8 ounces)
- sour cream and hot sauce, for serving
** Method:
1. In a large nonstick skillet, heat 2 tablespoons of the oil over medium.
2. Add onion and bell pepper, season with salt and pepper, and cook, stirring occasionally, until light golden and tender, about 8 minutes.
3. Stir in garlic until fragrant, 1 minute.
4. Add pinto beans, pico de gallo, smoked paprika, reserved bean liquid and ½ cup of water, and bring to a simmer.
5. Cook, stirring and mashing occasionally with a potato masher or the back of a spoon, until liquid is absorbed and mixture is thick, about 8 minutes.
6. Season with salt and pepper. Transfer refried beans to a bowl, and wipe out skillet.
7. Spread ½ cup of the refried beans in the center of each tortilla and top each with ⅓ cup of the cheese.
8. Fold the short sides of the tortilla over the filling; fold the bottom of the tortilla up and over the filling and tightly roll.
9. In the skillet, heat 1 tablespoon of the oil over medium.
10. Add 3 burritos seam side down and cook until golden, turning occasionally, 3 to 5 minutes.
11. Transfer to serving plates and repeat with the remaining 1 tablespoon oil and 3 burritos.
12. Serve warm with sour cream and hot sauce on the side.
** Credits:
- date created: [2026-08-02 Sun]
- From https://cooking.nytimes.com/recipes/1022532-bean-and-cheese-burritos
