#+STARTUP: showeverything
* Black Bean and Rice Enchiladas
** Ingredients:
- 1 tablespoon olive oil
- 1 green bell pepper, chopped
- 1 onion, chopped
- 3 cloves garlic, minced
- 1 can (15 ounce) black beans, rinsed and drained
- 1 can (14.5 ounce) diced tomatoes and green chilies
- ¼ cup picante sauce
- 1 tablespoon chili powder
- 1 teaspoon ground cumin
- ¼ teaspoon red pepper flakes
- 2 cups cooked brown rice
- 8 6-inch flour tortillas, warmed
- 1 cup salsa
- 1 cup shredded Cheddar cheese
- 3 tablespoons chopped fresh cilantro leaves
- ¼ cup shredded Cheddar cheese
** Method:
1. Preheat oven to 350° F (175° C).
2. Lightly grease a 9x13-inch baking dish.
3. Heat oil in a large skillet over medium heat; cook and stir green pepper, onion, and garlic until tender, about 7 minutes.
4. Stir in beans, tomatoes, picante sauce, chili powder, cumin, and red pepper flakes; bring to a boil.
5. Reduce heat to low and simmer, uncovered, until heated through and mixture thickens, about 5 minutes.
6. Fold in rice and 1 cup Cheddar cheese; cook until heated through, about 5 minutes.
7. Spoon a rounded ½ cup bean mixture down the center of each tortilla.
8. Fold sides over filling and roll up.
9. Place enchiladas seam side down in baking dish; spoon salsa over each tortilla.
10. Cover baking dish with aluminum foil.
11. Bake in preheated oven for 25 minutes.
12. Uncover and sprinkle with cilantro and ¼ cup Cheddar cheese. Bake until cheese is melted, 2 to 3 minutes.
** Credits:
https://www.allrecipes.com/recipe/222598/black-bean-and-rice-enchiladas/print/?recipeType=Recipe&servings=8&isMetric=false
