#+STARTUP: showeverything
* Burrito Bowls
** Ingredients:
- ¼ cup avocado or other neutral-tasting oil
- 1 medium red onion, coarsely chopped, divided
- 1 jalapeño, seeds removed if desired, coarsely chopped, divided
- ½ teaspoon ground cumin
- 1 cup long-grain white rice
- 1 (15-ounce) can black or pinto beans
- Kosher salt
- 3 cups corn kernels (from 3 cobs, or two drained 15-ounce cans, or frozen corn, thawed and shaken dry)
- ¼ cup chopped cilantro, plus more leaves for garnish
- 1 lime
- 4 ounces grated Monterey Jack cheese (1 cup)
- 1 large avocado
** Method:
1. In a large skillet or Dutch oven with a lid, heat 2 tablespoons oil over medium.
2. Add half the red onion and half the jalapeño, along with the cumin, and cook until fragrant and softened, 3 to 5 minutes.
3. Add the rice and beans (including the bean liquid).
4. Fill the can with water and add that, too (1¾ cups).
5. Season with 1 teaspoon salt.
6. When boiling, cover, reduce heat to low and cook undisturbed until the rice is tender, 18 to 20 minutes.
7. Meanwhile, in a medium bowl, stir together the remaining half red onion, half jalapeño and 2 tablespoons oil; the corn; cilantro; and juice from the lime.
8. Season to taste with salt.
9. When the rice is ready, turn off the heat and sprinkle with cheese.
10. Cover and let rest for 4 minutes.
11. Spoon the rice and beans into bowls.
12. Quarter the avocado and add a piece to each bowl, then top with the corn salsa and a few leaves of cilantro.
** Credits:
- From https://cooking.nytimes.com/recipes/758128148-burrito-bowls
- date created: [2025-09-25 Thu]
