#+STARTUP: showeverything
* Cajun Meat Loaf with Chili Sauce

** Meat Loaf

*** Ingredients:
- 1 cup long grain brown rice
- ¼ cup oil
- ⅔ cup dried lentils
- 1½ teasp. salt
- 2 cups diced onion
- 1 cup celery, chopped
- 1 cup diced green pepper
- 4 chopped jalapeno peppers
- 1 Tblsp garlic, chopped
- 1 cup pecans, chopped
- ½ cup sesame seeds
- ½ teasp black pepper
- 1 pinch white pepper
- 2 cups TVP
- 1½ cups barbecue sauce
- 9 eggs
- 1 pound cheddar cheese grated
- 8 ounces tomato juice
- ¼ cup soy sauce

**** Barbecue Sauce Ingredients
- 1 cup		tomato sauce
- ½ teasp		liquid smoke
- ¼ cup		sugar
- ¼ cup		cider vinegar
- ¼ cup		tomato paste

*** Ingredients (50%):
- ½ cup long grain brown rice
- 2 Tbls oil
- ⅓ cup dried lentils
- ¾ teasp. salt
- 1 cup diced onion
- ½ cup celery, chopped
- ½ cup diced green pepper
- 2 chopped jalapeno peppers
- ½ Tblsp garlic, chopped
- ½ cup pecans, chopped
- ¼ cup sesame seeds
- ¼ teasp black pepper
- 1 pinch white pepper
- 1 cup TVP
- ¾ cups barbecue sauce
- 4 eggs
- ½ pound cheddar cheese grated
- 4 ounces tomato juice
- 2 Tbls soy sauce

**** Barbecue Sauce Ingredients
- 1 cup		tomato sauce
- ½ teasp		liquid smoke
- ¼ cup		sugar
- ¼ cup		cider vinegar
- ¼ cup		tomato paste

*** Method:
1. Take half the oil, and saute uncooked rice over low heat until golden. Stir often.

2. Add 3 (1.5 for half) cups water, and cook uncovered until rice is tender.

3. In another saute pan, place lentils, 4 cups (2 cups for half) water and  ½ teaspoon salt. Cook until tender, about 30 minutes and drain. (Do not overcook; lentils should be chewy.)

4. In a large saute pan, take the rest of the oil and saute half the onions until brown.

5. Add the rest of onions, celery and peppers and cook until tender, or about 5 minutes.

6. Mix in the rest of the ingredients, except eggs, cheese and tomato juice. Let cool, then beat eggs with tomato juice and add to mixture.

7. Add  ¼ cup (or 2 Tbls for half) soy sauce. Knead. Wait 5 minutes so TVP can soak up moisture. Taste TVP to see if smooth. If crunchy, add water. Add cheese and place in baking dish. (Optionally, cover loaf with paper thin cheese: e.g., mozerella.)

8. Cover with aluminum foil and bake at 275 degrees for 1 hour or until center is cooked.

9. The meat loaf may be served with ketchup, or with the spicy chili sauce, below.


** Spicy Chili Sauce

*** Ingredients
- 1 medium	onion, chopped
- 1			green pepper chopped
- 2			jalapeno peppers, chopped
- 1 stalk		celery, diced
- ¼ cup		oil
- 1 large can	Italian tomatoes
- ½ teasp		coriander
- 1 heaping teasp	cumin
- ¼ cup		soy sauce

*** Method:
1. Saute onions. Add peppers, celery and jalapeno peppers and saute until tender. Break tomatoes into pieces with fingers and add spices. Cook for 10 minutes. Salt to taste.

** Credits:
- Park and Orchard Recipe
- from The Record: 6 November 1988
- date created: [2007-06-27 Wed]
