#+STARTUP: showeverything
* Cauliflower Adobo
** Ingredients:
- 1 large cauliflower (2½ to 3 pounds)
- Kosher salt
- 2 teaspoons black pepper, plus more as needed
- 3 tablespoons canola oil, plus more as needed
- ½ cup rice wine vinegar
- 5 tablespoons soy sauce
- 2 teaspoons raw or light brown sugar
- 6 garlic cloves, smashed and peeled
- 3 bay leaves
- 1 Thai chile, halved lengthwise, or ¼ teaspoon red-pepper flakes
- 3 scallions, thinly sliced, for serving (optional)
** Method:
1. Trim leaves and woody stalk from the cauliflower, then cut through the root into 8 wedges.
2. Season both sides of each wedge with salt and pepper.
3. Reserve any loose cauliflower pieces.
4. In a large skillet or Dutch oven, heat the oil over medium-high heat.
5. Place one layer of the wedges in the skillet cut-side down and cook without moving them until well browned on one side, 3 to 4 minutes.
6. Transfer to a plate and continue until all the cauliflower is seared, adding more oil as needed.
7. Return all the cauliflower to the pan with uncooked side facing down.
8. Add ¼ cup water, any loose cauliflower pieces, 2 teaspoons black pepper, rice wine vinegar, soy sauce, sugar, garlic, bay leaves and Thai chile.
9. Cover and let simmer over medium heat until the cauliflower is crisp-tender, about 5 minutes.
10. Uncover, turn the heat to medium-high, and cook, basting the cauliflower occasionally with the sauce, until the cauliflower is tender and the sauce has thickened and reduced to about ¾ cup, 8 to 10 minutes.
11. Serve the cauliflower with plenty of sauce and a sprinkle of scallions, if using.
** Yield:
4 servings
** Credits:
- From https://cooking.nytimes.com/recipes/1019927-cauliflower-adobo
- date created: [2025-06-29 Sun]
