#+STARTUP: showeverything
* Cheddar Sweet Corn Pie
** Ingredients:
- 3 tablespoons unsalted butter, divided (2 tablespoons + 1 tablespoon)
- 1/2 yellow onion, finely chopped
- 2 cloves garlic, minced
- 4 cups fresh or frozen (and thawed) corn kernels
- 2/3 cup half-and-half
- 2 cups sharp cheddar cheese, grated, divided (1½ cups + ½ cup)
- 3/4 cup panko or seasoned breadcrumbs, divided (½ cup + ¼ cup)
- 3 large eggs
- 1/2 teaspoon chili powder
- 1/2 teaspoon paprika
- 3 1/2 tablespoons fresh chives, plus extra for garnish, finely chopped, optional
- kosher salt and freshly ground pepper, to taste
** Method:
1. Preheat oven to 375º F and lightly grease a pie dish with butter or non-stick spray.
2. Melt 2 tablespoons butter in a large pan or skillet over medium-high heat and sauté onion until softened and translucent, 6-8 minutes. Season with salt and pepper.
3. Add garlic and cook for another 1-2 minutes, or until fragrant, then transfer mixture to a large bowl.
4. Add corn, half-and-half, 1½ cups cheddar cheese, ½ cup breadcrumbs, chives, salt and pepper to the bowl with the onion and mix until combined.
5. In a separate bowl, beat eggs with chili powder and paprika, then stir mixture into bowl with corn and onion until incorporated. Pour mixture into greased pie dish.
6. Microwave remaining 1 tablespoon butter until melted. Let cool slightly, then whisk together with remaining ¼ cup panko crumbs, ½ cup cheese and chives. Season with salt and pepper.
7. Evenly sprinkle panko mixture over corn, then place pie dish in oven and bake for 35 minutes, or until corn is puffed up and edges are starting to brown.
8. Remove from oven and let cool 5-10 minutes, then top with more chives or paprika. Enjoy!

** Credits:
- From https://12tomatoes.com/cheddar-corn-pie/
- date created: [2020-12-05 Sat]
