#+STARTUP: showeverything
* Creamy, Spicy Tomato Beans and Greens
** Ingredients:
- 6 tablespoons olive oil
- ⅔ cup Panko bread crumbs
- salt and black pepper
- 1 medium yellow onion, minced
- 4 garlic cloves, minced
- ½ teaspoon crushed red pepper
- ⅓ cup tomato paste
- 2 cans (14-ounce) cannellini beans or other creamy white beans, rinsed
- 1 cup heavy cream
- ½ cup chopped jarred sun-dried tomatoes in oil
- ⅔ cup finely grated Pecorino or Parmesan
- 4 cups, packed (3 ounces) baby arugula
- 2 teaspoons finely grated lemon zest plus 4 teaspoons juice (from 1 lemon)
- Toasted bread (optional), for serving

** Method:
1. In a medium skillet, heat 2 tablespoons olive oil over medium.
2. Stir in the Panko, season with salt and pepper, and cook, stirring frequently and shaking the pan, until toasted and golden, about 3 minutes.
3. Transfer seasoned Panko to a paper-towel lined plate, then wipe out the skillet.
4. Add another 2 tablespoons olive oil to the skillet and heat over medium.
5. Add the onion, garlic and crushed red pepper, season with salt and pepper, and cook, stirring frequently, until softened, about 4 minutes.
6. Add the tomato paste and stir until darkened and mixture is combined, about 3 minutes.
7. Stir in beans, heavy cream, sun-dried tomatoes and ⅓ cup water, and simmer, stirring occasionally, until flavors meld, about 5 minutes.
8. Stir in half the cheese, then season to taste with salt and pepper.
9. In a medium bowl, toss the arugula with the seasoned Panko, lemon zest and juice, plus the remaining ⅓ cup cheese and 2 tablespoons olive oil; season with salt and pepper.
10. Pile the greens at the center of the bean mixture. Serve with toasted bread, if desired.
** Yield:
4 servings
** Credits:
- From https://cooking.nytimes.com/recipes/1025325-creamy-spicy-tomato-beans-and-greens
- date created: [2025-04-10 Thu]
