#+STARTUP: showeverything
* Crispy Spiced Chickpeas With Peppers and Tomatoes
** Ingredients:
- 2 (15-ounce) cans chickpeas, rinsed and patted dry
- ½ cup olive oil
- 2 teaspoons ground cumin
- 1 teaspoon ground coriander
- ½ teaspoon ground turmeric
- ¼ teaspoon ground cayenne
- 1 teaspoon fine sea salt, plus more to taste
- 6 fresh thyme sprigs
- 2 red, orange or yellow bell peppers (or a combination), stems and seeds removed, sliced lengthwise ¼-inch thick
- 2 medium tomatoes, diced
- 1 small red onion, sliced
- 2 jalapeños, stem and seeds removed, sliced
- Juice of 1 lemon
- 1 garlic clove, finely grated or mashed to a paste
- 1 cup fresh herbs (any combination of parsley, cilantro, mint or dill)
- ½ cup pomegranate seeds
- Couscous or rice, for serving (optional)
** Method:
1. Heat the oven to 450° and arrange racks on the top and bottom thirds of the oven.
2. In a large bowl, toss chickpeas with 2 tablespoons oil, the cumin, coriander, turmeric, cayenne and ½ teaspoon salt until evenly coated. Spread onto a rimmed sheet pan in a single layer and top with 3 thyme sprigs.
3. On a second sheet pan, combine bell peppers, tomatoes, onion, jalapeños and remaining thyme sprigs with 2 tablespoons oil and remaining ½ teaspoon salt. Spread vegetables into one layer.
4. Place chickpea pan on the bottom rack and vegetables on the top rack and roast for 10 minutes. Switch pan positions. Roast chickpeas until crisped but still tender, about 5 minutes, and roast vegetables until golden brown, about 10 minutes. If the vegetables are tender but not browned, place the pan under the broiler for 1 to 2 minutes to caramelize. Discard thyme sprigs.
5. While the chickpeas and vegetables roast, whisk lemon juice, garlic and remaining ¼ cup oil in a small bowl. Season with salt to taste.
6. Arrange vegetables on a large platter and drizzle with half the dressing, then top with crispy chickpeas, fresh herbs and pomegranate seeds. Drizzle remaining dressing over everything. Serve with couscous or rice, if you like.
** Tags:
IsVegan
** Credits:
- From [[https://cooking.nytimes.com/recipes/1020381-crispy-spiced-chickpeas-with-peppers-and-tomatoes?action=click&module=RecipeBox&pgType=recipebox-page&region=all&rank=0][The New York Times recipes]]
- date created: [2022-08-26 Fri]
