#+STARTUP: showeverything
* Crispy Vegan Cauliflower Tacos
** Ingredients:
Tacos
- 1 medium cauliflower sliced into long pieces – see note
- ½ cup full fat coconut milk
- Juice and Zest of 1 lime
- ½ teaspoon salt
- ½ cup panko breadcrumbs gluten free if necessary
- ½ cup cornmeal
- ½ cup unsweetened shredded coconut
- 1 ½ teaspoons smoked paprika
- 1 teaspoon cumin
- ½ teaspoon garlic powder
- ¼ teaspoon turmeric
- ½ teaspoon salt
- ¼ teaspoon pepper

Sweet and Sour Slaw
¾ cup chopped red cabbage
- ¾ cup chopped green cabbage
- ½ cup shredded carrots
- Juice of 1 lime
- 1 tablespoon white vinegar
- 1-2 teaspoon(s) pure maple syrup
- ½ teaspoon salt

Tangy Vegan Tartar Sauce
- ⅓ cup homemade vegan mayonnaise or your favorite store-bought vegan mayo
- ⅓ cup diced dill pickle
- Juice and Zest of 1 lime
- 1 ½ teaspoons dried dill
- ½ teaspoon salt
- Dash of sriracha optional


** Method:
1. Preheat oven to 400°F.
   For the Slaw:
2. Make the slaw first so it has time to marinate and soften just a bit. Whisk all the wet ingredients together and pour them over the veggies in a medium bowl. Cover it and put it in the fridge.
   For the Baked Cauliflower:
3. Whisk together the coconut milk, zest and juice of 1 lime and½ teaspoon salt in a wide shallow bowl, set aside.
4. Whisk together the panko, cornmeal, shredded coconut, smoked paprika, cumin, garlic powder, turmeric, ½ teaspoon salt and the pepper in another wide shallow bowl, set aside.
5. Line a baking sheet with parchment paper and line up your breading station in this order: cauliflower, wet batter, dry breading, baking sheet.
6. Take a slice of the cauliflower and place it in the coconut milk batter, flipping it over to make sure all sides are covered. Next, place that piece of cauliflower in the dry breading mix, pressing it down and flipping it over to make sure it’s coated evenly on both sides. The breading should stick easily and not fall off. Transfer your breaded piece of cauliflower to the lined baking sheet. Repeat with all remaining slices of cauliflower. My medium sized cauliflower filled up one baking sheet perfectly!
7. Bake the breaded cauliflower for 25 to 30 minutes, flipping each piece over after 15 minutes, until both sides are golden brown and crispy.
   For the Tartar Sauce:
8. While the cauliflower is baking, make your tartar sauce. In a small bowl, stir together all ingredients. Place in the fridge until you are ready to use it.
   For the Tacos:
9. To assemble the tacos, place a tortilla on a plate, top with a bit of the slaw, a piece or two of the crispy breaded cauliflower and top with a big dollop of tangy tartar sauce. Garnish with an extra squeeze of lime or dash of sriracha.

** Credits:
- From https://www.veggieinspired.com/crispy-baked-cauliflower-tacos/#recipe
- date created: [2023-03-24 Fri]
