#+STARTUP: showeverything
* Curried Lentil Dish

** Ingredients:
- 15 Tbs lentils (assortment of channa dal, toor dal, urad dal, masoor dal and moong dal (mung beans))

** Method:
1. 1 tsp turmeric
2. 2 tsp grated ginger
3. 5 cloves minced garlic
4. 2 tsp green chilies
5. ½ tsp cayenne
6. ½ cup chopped red onion
7. ⅔ cup chopped tomato
8. 1 tsp cumin seeds
9. 1 Tbs chopped cilantro leaves
10. ½ tsp black pepper
11. 1 Tbs lemon juice
12. ½ tsp nutmeg
13. Place lentils in a saucepan, covering with 2" of water. Soak for 3-5 hours.
14. Add turmeric, bring to a boil, then simmer, covered, 1½ hours. Stir periodically so it doesn't stick. Then whisk until relatively creamy and smooth. (Less water will result in more stew-like.)
15. Mix ginger, garlic, chilies, cayenne, onion and tomato. Saute cumin seeds in a little olive oil until brown. Add to tomato mixture for 2 minutes. Add to already whisked dal over moderate heat for 1-2 minutes, stirring.
16. Add cilantro, cook 1-2 minutes. Add black pepper, remove from heat. Then add lemon juice and nutmeg.

** Credits:
- (via Kate 9 April 2011)
- date created: [2011-04-10 Sun]
