#+STARTUP: showeverything
* Dried Mushroom Soup with Barley

** Ingredients:
- ½ ounce dried mushrooms, such as porcini, shiitake, chanterelle and/or morel -- about ⅔ cup
- 6 cups boiling water
- 1 tsp canola or other vegetable oil
- 2 cups chopped onions
- 2 cloves garlic, pressed
- 1 cup finely chopped celery
- 1 cup carrots, peeled and finely chopped
- 3 cups sliced fresh mushrooms (about 10 oz.)
- ¼ cup soy sauce
- pinch dried thyme
- ¼ tsp ground black pepper
- ½ cup raw pearl barley
- ¼ cup dry shery or 2 tsp honey
- salt and ground black pepper to taste

** Method:
1. In a saucepan, cover the dried mushrooms with 6 cups boiling water. Simmer for 15 minutes. Remove from heat and set aside for at least 15 minutes.
2. Meanwhile, warm the oil in a soup pot on low heat. Add the onions and garlic, cover and cook for 5 minutes, stirring occasionally. Add the celery and carrots and cook for 5 minutes, stirring occasionally. Add the fresh mushrooms, increase the heat to medium and cook, stirring continuously, for about 3 minutes, until the mushrooms begin to release their jucies. Remove from the heat and set aside.
3. Drain the dried mushrooms, reserving the mushroom stock. Cut off and discard any tough stems, then rinse and chop the mushrooms. Strain the stock through a sieve or-- if dirt or sand is evident-- through a paper coffee filter. Add enough water to the stock to make 7 cups of liquid. 
4. Add the chopped dried mushrooms, mushroom stock, soy sauce, thyme, pepper, barley and optional sherry or honey to the pot of sauteed vegetables. Bring to a boil and then cover; reduce the heat and simmer for 45 minutes.
5. When ready to serve, add salt and pepper to taste. The soup should be brothy, so if it has cooked down and become thick, add a bit more water.

** Credits:
- Per 8 oz serving: 94 calories, 3.5 g protein, 1.2 g fat, 19 g carbs, 4.3 g dietary fiber
- [As served during Easter weeken at Tracey and John's; April 2004; Recipe Source: Moosewood Restaurant Low-Fat Favorites, page 94]
- date created: [2007-06-27 Wed]
