#+STARTUP: showeverything
* Fresh Egg Pasta
** Ingredients:
- 2 cups unbleached all-purpose flour
- 3 large eggs, lightly beaten
** Method:
1. Place the flour in the work bowl of a food processor and pulse several times.
2. Add the eggs and process until the dough forms a rough ball, about 30 seconds. (If the dough refuses to come together, add water, ½ teaspoon at a time, and continue processing until a ball forms. If the dough sticks to the sides of the work bowl, add flour, 1 tablespoon at a time, and continue processing until a ball forms.)
3. Turn the dough out onto a dray work surface.
4. Knead by hand until the dough is smooth, 1 to 2 minutes.
5. Cover with plastic wrap and set aside for 15 to 30 minutes.
6. Cut about one quarter of the dough from the ball and flatten the piece into a disk (Rewrap the remaining dough.)
7. Run the dough through the widest setting on a manual pasta machine.
8. Bring the ends of the dough toward the middle of the sheet of pasta and press them together.
9. Run the dough, open side first, through the widest setting again.
10. Fold , seal and roll again.
11. Without folding, run the pasta through the widest setting two more times, or until the dough is smooth.
12. If at any point the dough seems sticky, lightly dust it with flour.
13. Continue to run the dough through the pasta machine, narrowing the setting each time.
14. When you reach the last setting, the outline of your hand should be visible through the pasta.
15. Lay the sheet of pasta on a dry kitchen towel and cover with a second towel.
16. Repeat with the reset of the dough.
17. If using the pasta for lasagna, ravioli or tortellini, proceed with the recipe.
18. If making fettuccine, take the first sheet of pasta (it will have had a little time to dry out but should not be tough or brittle) and run it through the getting cutters on the pasta machine.
19. Carefully spread out the fettuccine on kitchen towels.
20. Repeat with the remaining sheets, making sure they have dried for 15 to 20 minutes before butting.
21. Use the pasta within a few hours or place it in zipper-lock plastic bags and freeze for up to several months.
22. When you are ready to cook the pasta, bring 4 quarts of water to a boil in a large pot.
23. Add salt to taste and the fettuccine.
24. Fresh pasta will be ready in about 3 minutes.
25. Frozen pasta should not be defrosted before cooking; it will require 4 to 5 minutes cooking time.
** Yield:
About one pound
** Credits:
- From /The Complete Italian Vegetarian Cookbook,/ by Jack Bishop; pages 130-131.
- date created: [2025-03-04 Tue]
