#+STARTUP: showeverything
* Garlicky Kale Salad with Crispy Chickpeas
** Ingredients:
- 1 large bunch of kale
*** Chickpeas
- 1 (15-ounce) can chickpeas, rinsed, drained and thoroughly dried
- 1½ tablespoon (avocado) oil
- 1 healthy pinch of sea salt
- 2½ to 3 tablespoons tandoori masala spice blend
*** Dressing
- 3 cloves garlic
- ⅓ cup tahini
- 2 tablespoons olive oil + more for roasting garlic
- ¼ cup lemon juice, plus more for massaging kale (about two small lemons)
- 1 healthy pinch of each salt and pepper
** Method:
1. Preheat oven to 375° F.
2. Add drained chickpeas to a mixing bowl and toss with oil, salt and tandoori masala.
3. Pull apart garlic cloves but leave the skin on. (Avoid using any tiny garlic cloves from the center of the head.)
4. Add garlic cloves and seasoned chickpeas to a baking sheet.
5. Drizzle garlic with a bit of olive or grapeseed oil.
6. Bake for 15-20 minutes or until garlic is fragrant and slightly browned.
7. Carefully remove garlic and set aside.
8. Continue baking chickpeas for 10-15 minutes more or until slightly crispy and golden brown.
9. Remove from the oven and set aside (chickpeas will get more crispy as they cool).
10. Squeeze garlic out of skins (or peel away skins) and add to a blender.
11. Add all remaining dressing ingredients and blend until smooth.
    #+begin_tip
    If you don't have a blender, add the dressing ingredients to a bowl and whisk vigorously to combine, smashing the garlic with the whisk.
    #+end_tip
12. Taste and adjust seasonings as desired, adding more lemon for brightness, tahini for richness and maple syrup for sweetness.
13. Set dressing aside.
14. Add kale to a large mixing bowl.
15. Before adding the dressing, add 1 tablespoon lemon juice to the kale and massage with hands to soften the texture and lessen the bitterness.
16. Then add as much dressing as desired (some may be leftover) and mix with a spoon or salad tongs.
17. Top with chickpeas and serve.
    #+begin_tip
    Best when fresh, although leftover keep in the fridge for up to a few days.
    #+end_tip
** Credits:
- From edibleasheville.com: Winter 2022
- date created: [2022-03-12 Sat]
