#+STARTUP: showeverything
* General Tso's Cauliflower
Prep time 15 mins
Cook time 15 mins
Total time 30 mins
 
Serves: 6-8 servings
** Ingredients
*** for the General Tso’s sauce:
- 1 tablespoon sesame oil
- 3 cloves garlic, minced
- 1 knob of ginger, grated
- ½ cup chicken or vegetable broth
- ½ cup soy sauce
- ⅓ cup rice vinegar
- ¼ cup sugar (more to taste)
- 2 tablespoons tomato paste
- 2 tablespoons cornstarch, dissolved in 1-2 tablespoons of cold water
*** for the Batter:
- 1 cup flour
- ⅔ cup cornstarch
- 1½ teaspoons baking powder
- 2 teaspoons salt
- 4 eggs
- water as needed (about ½ cup)
*** other ingredients:
- 1 head cauliflower, cut into small florets
- a deep layer of oil for frying
- scallions and sesame seeds for topping

** Method
*** General Tso’s Sauce: 
1. Heat the sesame oil in a small saucepan over medium low heat.
2. Add the ginger and garlic and stir fry for a minute or two.
3. Add remaining ingredients and whisk to combine.
4. Bring to a low boil; simmer for another 20-30 minutes or until sauce is thickened.
5. Add more sweetness, citrus, etc. to your taste.
*** Cauliflower Batter:
1. Whisk all the batter ingredients until a loose batter forms.The batter should be thick enough to cling to the cauliflower and cover it but stay loose enough to easily drip off (adjust thickness with water).
*** Cauliflower Frying: 
1. Pour oil into a heavy bottomed skillet to make it deep enough so it will cover the cauliflower about halfway (probably ends up being a few cups).
2. Heat the oil over medium heat.
3. Drop a small bit of batter in the oil to test it – when it rises to the top and bubbles, the oil is ready.
4. Dip cauliflower florets in the batter and let the excess drip off before gently setting in the oil.
5. Fry for a few minutes on each side, then flip, repeating sides several times if necessary until you get a nice golden brown fried exterior.
6. The additional frying time helps make it a little crunchier, which I very much like.
7. Remove and set on a cooling rack with paper towels underneath (again, rather than putting it all on a plate or bowl with paper towels, this keeps it crispy vs. soggy).
*** Serving:
1. Toss the fried cauliflower with the sauce (enough just to cover) and sprinkle with scallions and sesame seeds for serving.
2. Serve with rice.
