#+STARTUP: showeverything
* Grilled Vegetable Gratin

** Ingredients:
- 2 large eggplants (2 pounds)
- 2 large bell peppers
- olive oil
- 2 large red onions, peeled and sliced
- 3 cloves garlic, chopped
- 2 T olive oil
- 4 c tomatoes, peeled and chopped
- 3 T fresh basil, chopped
- 3 T parsley, chopped
- 1-2 t fresh oregano, chopped
- salt and pepper
- ½ c dry red wine
- 1 pound rigatoni
- ½ pound mozzarella, grated

** Method:
1. Slice the eggplants lengthwise, into  ½-in slices. Salt each slice on both sides and let sit for 30-45 minutes, until sweating a tan-colored water. Rinse each slice for just a second and pat dry. 
2. Quarter the peppers lengthwise and remove seeds and stems.
3. Brush eggplants and peppers with olive oil and grill over charcoal: eggplant, until tender, peppers (skin side down), until charred. Put the peppers in paper bag for a few minutes, then remove the skins. Cut eggplant and peppers into wide strips and set aside.
4. Heat 2 T olive oil, then saute onion and garlic until golden. Add 3 c tomatoes, the herbs, salt and pepper, and the wine. Simmer until thickened, about 30 minutes.
5. Preheat oven to 350 degrees and oil the gratin dish.
6. Cook the rigatoni until just al dente. Drain and mix with tomato sauce and grilled vegetables.
7. Pour into gratin dish, sprinkle with remaining tomatoes and mozzarella cheese.
8. Bake until very hot and cheese is beginning to color, about 30-40 minutes. If you like a brown, bubbly gratin topping, place under the broiler for a minute.
9. Serve immediately.

** Credits:
- date created: [2010-09-05 Sun]
