#+STARTUP: showeverything
* Lentils, Rice, Caramelized Onions
** Ingredients:
- Olive oil
- Salt
- 2 cloves garlic, thinly sliced
- 1 teaspoon ground cumin
- ¼ teaspoon ground allspice
- a pinch of cayenne
- thyme, oregano and/or rosemary
- 5 cups broth
- 1 cup lentils, rinsed
- ¾ cups rinsed rice
- salt and pepper
- lemon juice, vinegar or sumac
** Method:
1. Heat a slick of oil in a medium saucepan.
2. Add sliced onions, shallots or leeks — the more the merrier.
   #+begin_tip
   The browned onions are the best part of this dish, so you really can’t overdo it, but just know that the more onions you add, the longer they will take to caramelize. I used two shallots and two small onions, because that’s what I had, but in a perfect world, I’d use one giant white onion, thinly sliced.
   #+end_tip
3. Add a pinch of salt, and sauté until the onions turn golden brown, 15 to 25 minutes. 
   #+begin_tip
   Watch them carefully, especially toward the end of cooking. If they are cooking too quickly, turn down the heat. If they’re not getting brown, crank it. Some dark brown strands mixed in with the golden ones are OK, but you don’t want them to burn. When they are done, transfer half of them to a plate.
   #+end_tip
4. And add a couple of thinly sliced garlic cloves to the onions left in the pot. Sauté the garlic until fragrant, about a minute.
5. Add 1 teaspoon ground cumin, ¼ teaspoon ground allspice, if you have it, and a pinch of cayenne, and sauté for a few seconds to toast the spices and bring out their flavor.
6. If you have any herbs sprigs — thyme, oregano or rosemary — add them to the pot. Otherwise, add a large pinch of dried herbs.
7. Now add 5 cups broth or water (or a combination), and bring to a simmer.
8. Add enough olive oil and salt to the liquid so that it tastes good.
9. Then add 1 cup rinsed lentils (any kind) and let simmer, partly covered, until they are almost but not quite done, about 25 to 30 minutes for green or brown lentils, and 15 to 20 for red lentils.
10. Add ¾ cups rinsed rice to the pot and continue to simmer until everything is very tender, another 18 to 25 minutes.
11. When all is tender and lovely, taste it and add lots of salt, pepper and some kind of acid — lemon juice, vinegar or sumac — for brightness.
12. Top with the reserved golden onions and serve this in bowls, drizzled with your best olive oil, and garnished with red-pepper flakes, chopped fresh herbs, if you have some, and flaky salt. Without the garnish, it’s a drab-looking dish. But even unadorned, the earthy flavors of the lentils combined with those sweet golden onions will shine bright.
** Credits:
- From https://www.nytimes.com/2020/03/30/dining/pantry-mujadara-coronavirus.html
- date created: [2021-01-04 Mon]
- [2021-01-03 Sun] Made for T&J. Tasty!
