#+STARTUP: showeverything
* One-Pot Tofu and Broccoli Rice
** Ingredients:
- 4 garlic cloves
- 1 (1-inch) piece fresh ginger
- 1½ cups long-grain white rice, rinsed
- 1 tablespoon toasted sesame oil, plus more for serving
- Salt
- 2 tablespoons soy sauce, plus more for serving
- 2 tablespoons peanut butter
- 1 tablespoon chile crisp or chile sauce, plus more for serving
- 1 (14- to 16-ounce) block extra firm tofu, cut into ½-inch cubes
- 12 ounces small broccoli florets (about 6 cups)
- Cilantro leaves and tender stems (optional, for serving) or scallions

** Method:
1. Finely grate the garlic and ginger into a large pot or Dutch oven.
2. Add the rice and sesame oil, set over medium heat and stir until fragrant, 2 to 4 minutes.
3. Stir in 2½ cups water and 1 teaspoon kosher salt (such as Diamond Crystal), or ½ teaspoon coarse kosher salt or fine sea salt.
4. Bring to a boil, then cover, turn heat to low and cook for 10 minutes.
5. While the rice cooks, stir together the soy sauce, peanut butter and chile crisp in a medium bowl.
6. Add the tofu and stir to coat; set aside.
7. After the rice has cooked for 10 minutes, working quickly, scatter the broccoli on top of the rice and season with a pinch of salt.
8. Cover and cook until the rice is tender and the broccoli is bright green, another 10 to 15 minutes.
9. Turn off the heat, then scrape the tofu and sauce on top of the broccoli, cover and let rest for 10 minutes.
10. Serve topped with more sesame oil, soy sauce, chile crisp and cilantro (or scallions) as you like.

** Tags:
IsFavorite
** Credits:
- From https://cooking.nytimes.com/recipes/1025167-one-pot-tofu-and-broccoli-rice
- date created: [2024-08-08 Thu]
