#+STARTUP: showeverything
* Pasta Alla Norma
** Ingredients:
- 1½ pounds eggplant
- Olive oil as needed (at least ½ cup)
- Salt and pepper
- 1 tablespoon chopped garlic
- 3 or 4 dried chiles
- 1½ pounds tomatoes, chopped (canned are fine; about 1 can)
- 1 teaspoon good dried oregano, or 1 tablespoon fresh
- 1 pound long pasta
- ½ cup chopped parsley or basil
- ½ cup grated ricotta salata (or in a pinch, pecorino Romano)
** Method:
1. Slice the eggplant about ½ inch thick.
2. Cook in abundant olive oil, without crowding, sprinkling with salt and adding more oil as needed.
   #+begin_note
   You will undoubtedly have to cook in batches; take your time and cook until the eggplant is nicely browned and soft.
   #+end_note
3. Remove to a plate; do not drain on paper towels.
4. Meanwhile, put a large pot of water to boil and salt it.
5. At the end of the cooking the eggplant, the pan will ideally have a couple of tablespoons of oil left. If there’s more or less, drain some off or add a bit.
6. Turn the heat to medium, add the garlic and chiles, and cook until the garlic colors a little bit.
7. Add the tomatoes and oregano, along with some salt and pepper; cook until saucy but not too dry, stirring occasionally.
8. Cook the pasta until tender but not mushy.
9. While it’s cooking, cut the eggplant into strips and reheat for a minute in the tomato sauce.
10. Drain the pasta and toss it with the tomato sauce and the eggplant.
11. Taste and adjust the seasoning, then top with the parsley or basil and grated cheese and serve.
** Credits:
- From a Mark Bittman /NY Times/ recipe: https://cooking.nytimes.com/recipes/1014832-pasta-alla-norma
- date created: <2023-07-17 Mon>
- <2023-07-17 Mon> Made for T who said it tasted like "restaurant food" (... in a good way!)
