#+STARTUP: showeverything
* Pasta Quills with Cheesy Aubergine (Eggplant) Sauce
** Ingredients:
- 1¼ lb. eggplant, cut into ½ in cubes
- salt & pepper
- 3 tbsp. olive oil
- ½ oz. butter or margarine
- 1 garlic clove, chopped
- 16 fl. oz canned chopped tomatoes
- 12 oz. pasta quills (penne)
- 4 oz. firm goat cheese, cubed
- 3 tbsp. shredded fresh basil or 1 tsp. dried basil

** Method:
1. Put the eggplant cubes in a large colander and sprinkle them lightly with salt. Let drain at least 30 minutes.
2. Rinse the eggplant under cold water and drain well. Dry on kitchen paper.
3. Heat the oil and butter in a large saucepan. Add the eggplant and fry until just golden on all sides, stirring frequently.
4. Stir in the garlic and tomatoes. Simmer until thickened, about 15 minutes. Season with salt & pepper.
5. Cook the penne in a large pan of boiling salted water until just tender (check packet instructions for timing). Drain well and transfer to a warmed serving bowl.
6. Add the eggplant sauce, goat cheese and basil to the pasta and toss well together. Serve immediately.
** Yield
6 servings
** Credits:
- Marsha Montgomery 10 June 2003
- date created: [2007-06-27 Wed]
