#+STARTUP: showeverything
* Pineapple Sweet and Sour Tofu
** Ingredients:
- ½ cup vegetable broth
- ¼ cup apple cider vinegar
- ¼ cup agave or maple syrup
- 1 cup diced fresh pineapple
- 1 cup diced red bell pepper
- 1 tablespoons soy sauce or tamari
- 1 teaspoon Frank's, Sambal oelek or sriracha, optional
- 3 garlic cloves, minced
- 2 tablespoons cold water
- 1 tablespoon cornstarch
- 1 tablespoon vegetable oil
- 1 pound extra firm tofu, drained, pressed at least 15 minutes and cut into ½ inch cubes
- ¼ cup roasted cashews, coarsely chopped
- 2 scallions, chopped
- Cooked rice, for serving
** Method:
1. Stir the vegetable broth, cider vinegar, agave or maple syrup, pineapple, bell pepper, soy sauce or tamari, chili paste or sriracha and garlic together in small saucepan and place over medium heat. 

2. Bring the mixture to a simmer. Lower the heat and simmer for 15 minutes, stirring occasionally.

3. While sauce simmers, whisk the cold water and cornstarch together in small bowl. Set it aside.

4. About halfway through sauce's cooking time, prepare the tofu. Coat large a skillet with oil and place it over medium-high heat. 

5. Arrange the tofu cubes in a single layer in the skillet. Cook for about 10 minutes, flipping 2-3 times during cooking to ensure browning on multiple sides.

6. Once the simmer time for the sauce is up, stir in the cornstarch mixture. Allow it to simmer for another minute or two, until it thickens up.

7. Pour the sauce and pineapple mixture over the tofu. Stir to coat the tofu and remove the skillet from heat.

8. Serve with rice and top with cashews and scallions.

** Credits:
- From https://www.connoisseurusveg.com/pineapple-sweet-sour-tofu/
- date created: [2020-11-18 Wed]
- [2020-11-18 Wed] Yummy!
