#+STARTUP: showeverything
* Pizza, Cheesy Pan, Chicago-style
** Ingredients:
*** For a single recipe of the dough:
- 240 grams (2 cups) all-purpose flour
    --> or swap in ½ cup (60 grams) corn meal
- 180 milliliters (¾ cup) lukewarm water
- 1 tablespoon olive oil
- ¾ teaspoon kosher salt
- ½ teaspoon instant or active dry yeast
*** For a recipe and a half of the dough:
- 360 grams (3 cups) all-purpose flour
    --> or swap in ¾ cup (90 grams) corn meal
- 270 milliliters (1⅛ cup) lukewarm water
- 1½  tablespoon olive oil
- 1⅛ teaspoon kosher salt
- ¾ teaspoon instant or active dry yeast
*** For the assembly:
- 1½ tablespoons olive oil
- 6 ounces mozzarella, grated (about 1¼ loosely packed cups)
- 120 grams (½ cup) tomato sauce or pizza sauce
- Freshly grated hard cheese, such as Parmesan or pecorino, for garnish (optional)
- Fresh herbs, such as basil, marjoram or oregano, for garnish (optional)
** Method:
*** Prepare the dough
     + Measure the flour, water, olive oil, salt and yeast into a large mixing bowl.
     + Mix together with your hand or a dough scraper until it forms a shaggy, sticky ball with no dry patches.
     + Cover the bowl using a damp towel or plastic wrap, and let the dough rest for 5 minutes.
*** Strengthen the dough
     + Wet your hand, and reach down between the side of the bowl and the dough, as though you were going to lift the dough out, but instead of lifting, stretch the bottom of the dough up, and fold it over the top.
     + Repeat three more times, turning the bowl 90 degrees each time.
     + Cover the bowl again for 5 minutes, then repeat the folding-and-resting process three more times.
     + After the fourth time, cover the bowl, and let the dough rest, undisturbed, for 40 minutes, then transfer the bowl to the fridge for at least 12 hours or up to 72 hours.
*** About 3 hours before you want to eat the pizza, get ready for assembly
     + Pour the olive oil into a well-seasoned 9- or 10-inch cast-iron skillet, and use your fingers to coat the inside of the pan, including the sides.
     + Transfer the dough to the pan, and turn it once to coat both sides with the oil.
     + After coating the dough in oil, press the dough to the edges of the pan, dimpling it with your fingertips.
     + If the dough shrinks back, cover it and let it rest for about 15 minutes, then repeat the pressing and dimpling.
     + At this point, you should be able to smush the dough out and into the edges of the pan, but if not, give it one more 15-minute rest before trying again.
     + Cover the dough, and let it rise for 2 hours at room temperature.
     + It will look soft and jiggle when you gently shake the pan.
*** Bake the pizza
     + Place one rack at the bottom of the oven and one toward the top (about 4 to 5 inches from the top heating element), then heat the oven to 450°.
     + When you’re ready to bake the pizza, sprinkle a scant 1 cup mozzarella evenly over the crust.
     + Cover the entire dough so none is showing, then dollop small spoonfuls of the sauce over the cheese.
     + Sprinkle the remaining mozzarella on top, and bake on the bottom rack of the oven for 18 to 20 minutes, until the cheese is bubbling and the bottom and edges of the crust are a rich golden brown.
     + Use a spatula to check the bottom.
     + If the bottom is brown but the top still seems pale, transfer the pizza to the top rack, and bake for 2 to 4 minutes longer.
     + On the other hand, if the top seems fine but the bottom’s not browned to your liking, leave the pizza on the bottom rack for another 2 to 4 minutes.
*** Cool and serve pizzas
     + Remove the pizza from the oven, and place the pan on a heatproof surface.
     + Carefully run a table knife or spatula between the edge of the pizza and side of the pan to prevent the cheese from sticking as it cools.
     + Let the pizza cool very briefly; as soon as you feel comfortable doing so, carefully transfer it from the pan to a cooling rack or cutting surface.
     + If garnishing with hard cheese and herbs, add those now.
     + Serve the pizza anywhere from medium-hot to warm, and use kitchen shears or a large pair of scissors to cut it into wedges.
** Credits:
- From https://cooking.nytimes.com/recipes/1021193-cheesy-pan-pizza
- date created: [2020-06-27 Sat]
- Instead of using a wet hand, I used a dough scraper.
- [2020-06-27 Sat] Made for T, Ken, Amy. "A light crust that is greasy and crispy and buttery goodness" - TC
- [2020-12-02 Wed] Made for T, Larry and Jan. It was good once again, but I didn't bake it for as long as I should have and T thought it could have been a bit crispier.
- [2022-02-21 Mon] Made for Pat, Sharon, Greg, MaryAnn and T. Doubled recipe and used large Chicago-style pan.
- [2023-12-15 Fri] Made for Becky, Bill and T. Used a single recipe and baked in four personal pans for about 18 minutes. It turned out good as usual. But it was just barely enough dough (~115g per pie). Next time use a recipe and a half.
