#+STARTUP: showeverything
* Roasted Winter Vegetable Jambalaya
** Ingredients:
- ½ cup brown rice, rinsed
- 2 large carrots
- 2 cup parsnips, peeled and diced
- 2 cup, cubes sweet potato
- 2 cup, diced Yukon gold potatoes
- 1 medium onion, peeled and medium dice
- 2 tbsp extra virgin olive oil
- 1½  tsp kosher salt, divided
- 1 tsp cayenne pepper, divided
- 1 tsp ginger
- 1 tsp paprika
- 1 tsp turmeric
- ½ tsp chili powder
- ½ tsp cinnamon
- ¼ tsp nutmeg
- ¼ tsp black pepper
- 1 tbsp tomato paste
- 3 cup low-sodium vegetable broth
- 3 tomatoes, medium dice
- 1 cup parsley, divided
- 15 fl oz garbanzo beans, can, no sodium
- 15 fl oz pinto beans, can, no sodium
** Method:
1. Rinse rice in a strainer under cold water then place it in a small pot and add a little more than 1 cup of water. Cover pot and bring to a boil over high heat, then reduce to a simmer with the lid on for 30 to 35 minutes or until water is fully absorbed. Remove from heat.
2. While rice is cooking, preheat the oven to 400° F.
3. Toss carrots, parsnips, both potatoes and onion in olive oil, 1 teaspoon salt, ½ teaspoon black pepper and spices until thoroughly coated. Spread evenly over a rimmed baking sheet and roast in the oven, stirring halfway through, until veggies are tender and lightly browned, about 25 to 30 minutes.
4. Transfer roasted veggies to a large pot or Dutch oven, add the tomato paste, and stir to coat. Cook, stirring often, until the raw tomato flavor has cooked off, about 1 to 2 minutes.
5. Add the chopped tomatoes, broth, half of the parsley and remaining salt and pepper. Bring to a boil over high heat, then reduce heat and simmer for 10 minutes. Stir in the chickpeas, pinto beans and rice and cook until the flavors have combined, about 5 minutes more.
6. Ladle the jambalaya into bowls, sprinkle with the remaining parsley and serve.
** Credits:
- From https://app.slack.com/client/T025QN6JG/C01PNQX6N48
- date created: [2021-09-27 Mon]
