#+STARTUP: showeverything
* Roasted Eggplant, Crisp Garlic, and Basil Pasta

** Ingredients:
- 8 medium baby japanese eggplant (or 1 Globe eggplant) ends trimmed
- 6 tablespoons olive oil divided plus more for garnish
- 4 sprigs fresh thyme (or oregano) leaves stripped
- kosher salt and freshly ground black pepper
- 6 medium garlic cloves thinly sliced
- 1 (14-ounce) can tomato puree
- 1 tablespoon balsamic or sherry vinegar
- 1 teaspoon unrefined cane sugar (optional)
- 12 ounces spaghetti
- 3 ounces feta or goat cheese crumbled
- 1 handful fresh basil leaves thinly sliced

** Method:
1. Heat oven to 450 degreesF and arrange a rack in the middle. Slice baby eggplant lengthwse or cut larger eggplant into 1-inch cubes then combine with half of the olive oil and the thyme or oregano. Season with salt and freshly ground black pepper and toss to combine. Spread on a silicone baking mat or foil-lined baking sheet in one even layer and roast, stirring a few times, until soft and golden brown, about 20 to 30 minutes.

2. Meanwhile,  bring a large pot of heavily salted water to a boil over high heat.

3. In a large frying pan, heat the remaining oil over medium-high heat. When it shimmers, add garlic and cook until garlic is crisp, golden brown, and fragrant. Remove garlic to a paper towel-lined plate and set aside.

4. Return pan with olive oil to the stove over medium heat and add the tomatoes and vinegar, sugar, season with salt, reduce heat to medium-low, and simmer, stirring occasionally, until slightly thickened, about 10 minutes

5. Meanwhile, when the water boils, cook pasta according to package directions. Reserve 1 cup of pasta water and drain pasta. Set aside.

6. Add eggplant to pasta sauce and simmer until heated through. Taste, and, add more vinegar if the sauce is sweet, or, as needed, add sugar to make the sauce sweeter.

7. Add reserved pasta to pasta sauce and stir to coat. Add ¼ cup of the reserved pasta water and stir until each piece of pasta is just coated with the sauce. Add additional pasta water as needed to help the sauce coat the pasta. Remove from heat, top with cheese, basil, and crisp garlic and season with additional salt and pepper, as desired. Finish pasta with a drizzle of additional olive oil and serve.

** Credits:
http://saltandwind.com/recipes/38-late-summer-roasted-eggplant-pasta-recipe
