#+STARTUP: showeverything
* Smothered Mushrooms and Kale
** Ingredients:
- 2 tablespoons extra-virgin olive oil, 2 turns of the pan
- 2 tablespoons butter, cut into small pieces
- 4 cloves garlic, chopped
- 24 small crimini mushrooms, wiped clean, halved
- 1 bunch kale, trimmed, stems removed and chopped
- ¼ cup Marsala or other sherry
- Salt and pepper
** Method:
1. Heat a medium skillet with extra-virgin olive oil and butter over medium to medium-high heat.
2. When fat is hot, add garlic and mushrooms and place a lid which is too small for the skillet down into the pan, pressing and smothering the mushrooms.
3. Cook 7 to 8 minutes, stirring once, then wilt the kale into the pan, turning it with tongs to combine with mushrooms.
4. Smother the greens for 1 to 2 minutes, then deglaze the pan with Marsala and season the mixture with salt and pepper, to taste.
** Credits:
- From https://www.foodnetwork.com/recipes/rachael-ray/smothered-mushrooms-and-kale-recipe-1946122
- date created: [2025-02-05 Wed]
