#+STARTUP: showeverything
* Spaghetti with Spicy Broccoli and Pecorino
** Ingredients:
- 2 pounds broccoli
- ¼ cup extra-virgin olive oil
- 4 medium garlic cloves, minced
- ½ teaspoon dried hot red pepper flakes, or to taste
- salt
- 1 pound spaghetti, whole wheat or white
- Freshly grated Pecorino Romano or Parmigiano-Reggiano cheese
** Method:
1. Bring 4 quarts water to a boil in a large pot for cooking the pasta.
2. Remove and discard the stalks from the broccoli.
3. Cut the florets into bite-sized pieces. There should be about 5 cups. Set aside.
4. Heat the oil in a skillet large enough to hold the spaghetti when cooked and the broccoli.
5. Add the garlic and hot red pepper flakes and sauté over medium heat until the garlic is golden, about 2 minutes.
6. Turn off the heat and stir in 1 teaspoon salt.
7. When the water comes to a boil, add salt to taste and the spaghetti.
8. When the spaghetti is almost al dente, add the broccoli.
9. Continue cooking until the pasta is al dente and the broccoli is tender, about 2 minutes.
10. Drain, reserving ½ cup of the cooking liquid.
11. Add the spaghetti and broccoli to the skillet.
12. Toss over high heat, adding most, if not all, of the reserved cooking liquid to moisten the dish.
13. Divide among individual bowls and serve immediately with grated cheese passed separately at the table.
** Credits:
- Recipe source: The Complete Italian Vegetarian Cookbook, by Jack Bishop, page 89.
- date created: [2025-03-14 Fri]
