#+STARTUP: showeverything
* Spicy Black Bean Cakes

** Lime Sour Cream:

*** Ingredients:
- * ½ cup reduced fat sour cream
- * 2 teaspoons fresh lime juice
- * 1 small fresh jalapeno pepper, minced
- * salt to taste

*** Method:
- Combine all ingredients.

** Bean Cakes:

*** Ingredients:
- ¼ cup quinoa, dry
- 2 (14.5 ounce) cans black beans, drained and rinsed
- 2 tbsp olive oil
- 6 cloves garlic, pressed
- 2 fresh jalapeno peppers, finely diced and/or
- 1 chipotle jalapeno peppers, in adobo sauce
- 1 tablespoon ground cumin
- 1 tablespoon chili pepper
- salt and black pepper to taste
- 1 egg, lightly beaten
- ½ cup plain dried bread crumbs (optional)
- ½ cup corn kernels (optional)

*** Method:
1) To prepare lime sour cream, mix the sour cream, lime juice, 1 small minced jalapeno, and salt together in a small bowl. Cover, and refrigerate.
2) Preheat oven to 375 degrees.
3) Cook the quinoa per instructions on package.  (Toast quinoa first, rinse then simmer ¼ cup quinoa in ½ cup boiling water.) This will take about 10-15 minutes.
4) Puree black beans with olive oil, garlic, peppers and spices in a food processor.
5) Whisk egg in a medium-sized bowl.
6) Add black bean puree, cooked quinoa and bread crumbs (if using) to egg bowl and mix until fully combined into a batter.
7) Place 6 cupcake papers on a baking sheet.  Divide black bean cake batter among the 6 cups, and bake for about 15 to 20 minutes.
8) Allow black bean cakes to cool for a few minutes.  Remove from papers.  Serve over a bed of spinach with fresh salsa and grated cheese. Or over polenta or mashed potatoes.
9) Serve with lime sour cream.

** Credits:
- January 2011; inspired by 
- http://www.myplateisfullblog.com/2010/03/26/quinoa-black-bean-cakes/ and http://allrecipes.com//Recipe/spicy-black-bean-cakes/Detail.aspx
- date created: [2011-01-30 Sun]
