#+STARTUP: showeverything
* Spiced Chickpea Stew
** Ingredients:
- 1⁄4 cup olive oil, plus more for serving
- 4 garlic cloves, chopped
- 1 large yellow onion, chopped
- 1 piece (2-inch) ginger, finely chopped
- kosher salt and black pepper
- 11⁄2 teaspoons ground turmeric, plus more for serving
- 1 teaspoon red-pepper flakes, plus more for serving
- 2 cans (15-ounce) chickpeas, drained and rinsed
- 2 cans (15-ounce)  full-fat coconut milk
- 2 cups vegetable or chicken stock
- 1 bunch spinach, Swiss chard, kale or collard greens, stems removed, torn into bite-size pieces
- 1 cup mint leaves, for serving
- Yogurt, for serving (optional)
- Toasted pita, lavash or other flatbread, for serving (/optional/)
** Method:
1. Heat 1⁄4 cup oil in a large pot over medium.
2. Add garlic, onion and ginger.
3. Season with salt and pepper, and cook, stirring occasionally until onion is translucent and starts to brown a little at the edges, 3 to 5 minutes.
4. Add 11⁄2 teaspoons turmeric, 1 teaspoon red-pepper flakes, and the chickpeas, and season with salt and pepper.
5. Cook, stirring frequently, so the chickpeas sizzle and fry a bit in the spices and oil, until they’ve started to break down and get a little browned and crisp, 8 to 10 minutes.
6. Remove about a cup of chickpeas and set aside for garnish.
7. Using a wooden spoon or spatula, further crush the remaining chickpeas slightly to release their starchy insides.
  #+begin_tip
   This will help thicken the stew.
  #+end_tip
8. Add coconut milk and stock, and season with salt and pepper.
9. Bring to a simmer, scraping up any bits that have formed on the bottom of the pot.
10. Cook, stirring occasionally, until stew has thickened, 30 to 35 minutes.
   #+begin_tip
    Taste a chickpea or two, not just the liquid, to make sure they have simmered long enough to be as delicious as possible.
   #+end_tip
11. If after 30 to 35 minutes, you want the stew a bit thicker, keep simmering until you've reached your desired consistency.
12. Determining perfect stew thickness is a personal journey!
13. Add greens and stir, making sure they’re submerged in the liquid.
14. Cook until they wilt and soften, 3 to 7 minutes, depending on what you’re using.
   #+begin_tip
    Swiss chard and spinach will wilt and soften much faster than kale or collard greens.
   #+end_tip
15. Season again with salt and pepper.
** Yield:
- 4 to 6 servings
** Credits:
- date created: [2026-03-20 Fri]
- From a recipe Todd gave me.
