#+STARTUP: showeverything
* Spicy Spinach and Cheese Curry
** Ingredients:
*** For the cheese
- 8 cups milk
- ¼ cup fresh lemon juice or cider vinegar
- 6 tbsp. ghee or vegetable oil
*** For the spinach
- 1" piece ginger, peeled and chopped
- 3-4 cloves garlic; peeled and chopped
- 1 serrano chile, stemmed and chopped
- 4 bunches spinach, washed, trimmed and finely chopped (about 6 cups)
- salt
- ½ tsp. garam masala
- 1-2 pinches cayenne
- 6 tbsp. heavy cream
** Method:
*** For the cheese
1. Line a colander with 4 layers of cheesecloth, draping it over the sides and set a colander aside in the thie sink.
2. Put the milk into a large saucepan and bring just to a boil over medium-high heat, stirring often with a wooden spoon to prevent it from scorching, about 15 minutes.
3. Reduce heat to medium-low, add lemon juice and very slowly and gently stir until large curds form, about 30 seconds.
4. Carefully pour milk mixture into colander and gently rinse off under cold running water and any foam and residual lemon juice from curds.
5. Gather corners of cheesecloth together and gently squeeze out liquid.
6. Tip opposite corners of cheesecloth together to make a sack and hang it from a large kitchen spoon suspended over a deep bowl.
7. Set drained from cheese, about 1½ hours.
8. Transfer sack to a large plate, untie cheesecloth and loosely drape corners over cheese.
9. Place a large heavy pot on top of cheese, then set aside for 30 minutes to compress cheese.
10. Remove pot and unwrap cheese.
11. Cut cheese into ½" x 1" pieces.
12. Heat ghee in a large nonstick skillet over medium heat.
13. Add cheese and fry until golden all over, 4-6 minutes.
14. Transfer cheese with a slotted spatula to a plate and set aside
*** For the spinach
1. Put ginger, garlic, chiles and ¼ cup water into a blender and purée to a smooth paste.
2. Return skillet with ghee to stove and heat over medium-high heat.
3. Add ginger-garlic paste and cook, stirring with a wooden spoon, for 30 seconds.
4. Add spinach, season to taste with salt and cook, stirring often, until spinach wilts, about 1 minute.
5. Reduce heat to medium-low, cover an cook, stirring often, until spinach is very soft, 10-15 minutes.
6. Stir in garam masala, cayenne to taste and cream.
7. Add fried cheese to skillet, cover and continue cooking until liquid thickens and spinach is silks soft, about 15 minutes more.
8. Serve with warm Indian flat bread, if desired.
** Credits:
- From /Saveur/ No. 59, page 36
- Date created: [2021-03-15 Mon]
