#+STARTUP: showeverything
* Sweet Potato Hash with Mushrooms

** Ingredients:
- 2 medium sweet potatoes, peeled and cut into ½ inch cubes
- ½ teaspoon salt
- 1 tablespoon butter
- 2 cups button mushrooms, sliced
- 1 tablespoon grapeseed oil
- ½ red onion, diced
- Optional: 1 Fresno chili or jalapeno, diced (remove seeds for a more mild heat)
- 2 to 3 cloves garlic, minced
- 1 red bell pepper, chopped
- Salt and pepper to taste
- 2 tablespoons fresh cilantro, minced
- 1 tablespoon grapeseed oil
- 4 to 8 eggs
- Optional: ketchup and/ or Sriracha sauce for serving

** Method:
1. To par-boil the sweet potatoes place them in a medium-sized pot and cover with water, add the ½ teaspoon of salt, stir. Bring to a boil, uncovered, and boil for 2 to 3 minutes. The potatoes should be slightly tender, but not completely cooked. A fork should go about ⅓ of the way into the potato. Once they are par-boiled immediately drain them in to a colander and rinse them in cold water to stop the cooking process. Set aside.
2. While the sweet potatoes are coming to a boil sauté the mushrooms. Heat a large, heavy-bottomed skillet over medium-high heat. Melt the butter. Add the mushrooms and sauté them for about 10 minutes, stirring occasionally. They should be browned and tender. Remove the mushrooms into a dish and set aside.
3. Heat the grapeseed oil in the heated skillet, add the onion and the Fresno chili or jalapeno (optional). Sauté until tender, about 3 minutes. Add the garlic and sauté for 1 minute more.
4. Add the red bell pepper and the par-boiled sweet potatoes. Season with a healthy pinch of salt and pepper. Sauté for about 10 to 15 minutes, stirring occasionally. You will know the potatoes are done when they are fork-tender and slightly caramelized. Add the mushrooms back into the hot pan and allow to heat for 2 minutes.
5. Remove the pan from the heat and stir in the cilantro. Taste-test and add more salt and pepper as needed. Transfer the sweet potato mixture onto a serving platter or individual plates.
6. Return to the skillet, heat over medium-high heat. Add a tablespoon of grapeseed oil. Crack as many eggs as you plan to use into the skillet. Cover and cook for about 3 to 5 minutes, or until the egg white has set and the yolk is still runny. NOTE: you can cook your eggs any way you prefer, but I recommend eggs that have runny yolks for this recipe so that the potatoes can soak everything up.
7. Serve the eggs over the potato hash mixture with a side of ketchup and Sriracha sauce (optional).

** Notes
If you want to make this breakfast go even faster on the morning of then you can make the sweet potato mixture the night before, store it in the refrigerator in an airtight container and heat it up while you cook up your eggs. The sweet potato mixture reheats nicely.
** Credits:
- https://robustrecipes.com/sweet-potato-hash-with-mushrooms/
- date created: [2019-10-29 Tue]
