#+STARTUP: showeverything
* Swiss, Mushroom and Spinach Frittata
** Ingredients:
- 1-2 tablespoons extra virgin olive oil
- 8 ounces button mushrooms, sliced (other mushrooms such as crimini may be substituted)
- 1 garlic clove, minced
- 5 cups baby spinach
- 10 large eggs, separated
- 1 cup half-and-half or whole milk
- 1½ cup + ¼ cup shredded Emmi USA Kaltbach Emmentaler AOP cheese, divided
- 1 teaspoon kosher salt
- ½ teaspoon ground black pepper
** Method:
1. Place an oven rack on the center or upper-middle shelf, then preheat oven to 400 degrees F.

2. Heat the olive oil in a 12-inch oven-safe nonstick or cast iron skillet over medium-high heat. Use just enough oil to coat bottom of the pan; you might not need the entire amount. Add the mushrooms and cook until soft and fragrant, 3-4 minutes. Adjust the heat to medium-low and add the garlic, stirring for an additional 30-60 seconds. Add the spinach in batches, stirring as it wilts. Once all of the spinach has been wilted, remove the pan from the heat.

3. In a large bowl, beat the egg whites to a stiff peak using an electric hand mixer or stand mixer with the whisk attachment. In a separate large bowl, whisk together the yolks, then add the half-and-half, 1½ cups cheese, salt and pepper.

4. Gently fold the whites into the yolks using a spatula. Once evenly combined, pour the egg mixture over the vegetables. Sprinkle the remaining cheese evenly over the top.

5. Bake for 10-13 minutes, or until the eggs have fluffed up and set with a golden top. Cut the frittata into wedges and serve.

6. The frittata is best served fresh, but leftovers can be refrigerated in an airtight container for up to 5 days. Microwave to reheat for a quick breakfast, lunch, or dinner.
** Credits:
- From https://www.savorysimple.net/swiss-mushroom-spinach-frittata-recipe/#wprm-recipe-container-25417
- date created: [2020-05-31 Sun]
- [2020-05-31 Sun] I made a half recipe, but also threw in a half an onion, nearly caramelized. TC and I liked it!
