#+STARTUP: showeverything
* Three Layer No-Boil Lasagna
** Ingredients:
- 1 box (9 oz) no-boil lasagna noodles, uncooked
- 2 eggs
- 1 container (15 oz) ricotta cheese
- 4 cups (16 oz) shredded mozzarella cheese, divided
- ½ cup (2 oz) grated Parmesan cheese
- 6 cups tomato sauce
- 2 bags spinach (/optional/)
** Method:
1. Preheat oven to 375° F.
2. Spray baking pan (about 13 x 9 x 2-inches deep) with non-stick cooking spray.
3. Remove 14 lasagna sheets from box. DO NOT BOIL!
4. In a medium bowl, beat eggs.
5. Stir in ricotta and the Parmesan and 2 cups mozzarella.
   #+begin_tip
   When layering lasagna, slightly overlap sheets. Lasagna will expand to the edges during cooking. Spread fillings to the edges to seal in and cook the lasagna during baking.
   #+end_tip
6. Layer in the following order:
     a. Make three layers using 12 uncooked sheets.
     b. Spread 1 cup of the sauce on the bottom of the baking pan.
     c. Layer 4+ sheets, half of ricotta mixture,  half the spinach, 1 cup of the sauce and 1 cup of mozzarella.
     e. Layer 4+ sheets, remaining ricotta mixture, 1 cups of the sauce and half the spinach.
     f. Layer 4+ sheets, remaining sauce and 1 cup of mozzarella.
7. Bake, covered with foil until bubbly, 50-60 minutes.
8. Uncover and continue cooking until cheese is melted, about 5 minutes
9. Let stand 15 minutes before cutting.
** Yield:
Makes 12 servings.
** Credits:
- From the back of a box of Barilla lasagne noodles.
- date created: [2025-01-06 Mon]

# Local Variables:
# jinx-local-words: "Barilla lasagne"
# End:
