#+STARTUP: showeverything
* Tofu and Broccoli
** Ingredients:
- ¼ cup light soy sauce
- 1 tablespoon toasted sesame oil
- 2 tablespoons light brown sugar
- 1 teaspoon plus ¼ cup cornstarch, divided
- 1 (14-ounce) block firm tofu, drained
- 4 tablespoons vegetable oil, divided
- Kosher salt
- 2 medium broccoli crowns, cut into florets
- 4 garlic cloves, finely chopped
- 1 (½-inch) piece fresh ginger, finely chopped (about 2 teaspoons)
- 3 scallions, finely chopped
- Toasted sesame seeds, for garnish
- Rice, for serving
** Method:
1. In a small bowl, whisk together soy sauce, sesame oil, brown sugar, 1 teaspoon cornstarch and ½ cup water. Set aside.
2. Cut the tofu into 1-inch cubes, spread the cubes onto a thin cotton towel or a few layers of paper towels and pat them dry.
3. In a medium bowl, toss the cubes with the remaining ¼ cup of cornstarch and fully coat the tofu.
4. In a large skillet, heat 2 tablespoons vegetable oil over medium heat.
5. Once the oil is hot and shimmery, add the tofu and cook until all sides are golden, 10 to 12 minutes. Transfer the tofu onto a plate and season with salt.
6. In the same skillet, heat 1 tablespoon vegetable oil over medium heat, add the broccoli and cook, undisturbed, until broccoli is lightly charred on the bottom, 2 to 3 minutes. (Do not be tempted to move them!)
7. Toss and cook until the other sides of the broccoli are darkened in spots, another 2 to 3 minutes.
8. Add the remaining 1 tablespoon vegetable oil, the garlic, ginger and scallions to the same skillet and stir until fragrant, 1 to 2 minutes.
9. Adjust the heat to low, add the tofu back to the skillet, and stir in the reserved soy sauce mixture.
10. Bring to a simmer, tossing frequently, until the broccoli and tofu are evenly glazed, 30 seconds to 1 minute.
11. Serve the tofu and broccoli topped with toasted sesame seeds, with rice alongside.
** Credits:
- From https://cooking.nytimes.com/recipes/758205344-tofu-and-broccoli
- date created: [2025-12-29 Mon]
- [2025-12-29 Mon] Really good and, yes, reminiscent of  restaurant tofu and broccoli!
