#+STARTUP: showeverything
* Vegan Spicy "Chicken" Sandwiches
** Ingredients:
*** For the Spicy "Chicken"
- 1 Can (15oz.) cannellini Beans
- 1 tablespoon olive oil
- 2 tablespoons soy sauce
- ⅓ cup vegetable broth
- 2 teaspoons chili paste or Sriracha
- 1 cup vital wheat gluten
- ⅓ cup + ½ cup Panko bread crumbs, divided
- 1 teaspoon salt
- ½ teaspoon cayenne pepper
- ½ cup plain bread crumbs, vegan
- 1 teaspoon red pepper flakes
- ½ teaspoon chili powder
*** For the Spicy Mayo
- ⅓ cup vegan mayo, I used Hellman's
- 2 teaspoons hot sauce, I used Franks
*** For the Sandwiches
- 4 Hamburger Buns, vegan
- 4 Slices vegan pepper jack cheese (I used Follow your Heart)
- lettuce
** Method:
1. Preheat the oven to 400° F.
2. Drain the beans, and add them to a large mixing bowl.
3. Mash the beans with a fork or potato masher until all the beans are mashed.
4. Add the olive oil, vegetable broth, soy sauce and chili paste or sriracha to the bowl with the beans.
5. Stir to fully combine.
6. Pour the vital wheat gluten, the ⅓ cup of Panko, salt and cayenne to the bowl.
7. Stir to combine, then begin to knead with your hands until the mixture forms a nice ball that isn't sticky and holds together well.
8. In a separate bowl, combine the remaining ½ cup of Panko, the plain bread crumbs, the red pepper flakes and the chili powder.
9. Divided the "chicken" mixture into 4 equal pieces.
10. Roll each piece into a large ball, then put one of the balls into the bowl with the bread crumb mixture and press down to flatten out and coat in the bread crumbs.
11. Flip and coat the other side making sure you now have a flat patty.
12. Place the patty on a baking sheet sprayed with non-stick spray and repeat with the remaining "chicken" patty mixture.
13. Spray the tops of the patties with more non-stick spray.
14. Bake for 15 minutes, flip and bake for 15 more minutes or until the patties are nice and brown and firm.
15. Make the spicy mayo while the patties bake: whisk together the vegan mayo and hot sauce and set aside.
17. Once the patties are done, you can put a piece of vegan pepper jack on each patty and bake for a few more minutes to melt the vegan cheese, or you can place a piece on top before serving.
18. When ready, spread some vegan spicy mayo on the bottom of a bun, the "chicken" patty, the vegan pepper jack, some lettuce and more vegan spicy mayo on the top bun and put that on top.
19. Enjoy!
** Yield:
Serves 4.
** Credits:
- From https://www.rabbitandwolves.com/vegan-spicy-chicken-sandwiches/
- date created: [2025-03-20 Thu]
