#+STARTUP: showeverything
* Vegetable Riggies
** Cook Time
Prep time: 20 min
Cook time: 45 min\\
Ready in: 1 hour 5 min\\
Yields: Serves 6 to 10

** Ingredients:
- 12 medium-sized mushrooms, sliced
- regular sized bag green onions, chopped
- ½ clove garlic, minced or pressed
- ¾ stick butter, melted in pan
- 1 to 2 lbs various peppers of your choice, cut however your heart desires
- 1 to 2 lbs High-quality rigatoni pasta
- 2 large cans crushed tomatoes
- ½ to 1 white onion, preferably in rings
- a handful Italian seasonings, pepper and salt, tossed in
- 1 quart heavy cream
- 1 tablespoon extra virgin olive oil
** Method:
1. Chop up all your veggies, place the mushrooms and scallions in one bowl, and have all your peppers in another bowl.
2. Put the crushed tomatoes in a medium sauce pan. Put on a low heat, adding white onion and all the seasonings. Base amounts on your liking. Periodically stir.
3. Heat butter and garlic in a large high sided frying pan on a medium heat. Once garlic smell comes off the pan, immediately add mushrooms and scallions. Saute until lightly browned, roughly 10 minutes. Get your pasta water started on the heat. Add olive oil to water.
5. Add peppers. Keep heat close to high. Let cook for about 10 more minutes. Your pasta is done.
6. Add heavy cream in with peppers. Let cook on medium heat for about 15 minutes.
7. Combine everything... /Boom!/

** Credits:
- From https://delishably.com/meat-dishes/How-to-make-the-Best-Chicken-Riggies
- date created: [2020-05-10 Sun]
- [2020-05-16 Sat]: Yum!
