#+STARTUP: showeverything
* Vegetarian Lentil Burger
These make great do-ahead meals, and you can store shaped, ready-to-cook patties in the refrigerator for a week's worth of work lunches. I use black lentils in this recipe, some of the other types of lentils are too mushy when cooked - so I'd stick with the black lentils. Feel free to spice up the batter by experimenting with your favorite seasonings.

** Ingredients:
- 3 cups cooked black lentils
- 4 large eggs
- ½ teaspoon fine-grain sea salt
- 1 onion, finely chopped
- 1 cup toasted fine (whole-grain) bread crumbs
- 1 tablespoon extra-virgin olive oil (or clarified butter)
** Method:
1. Combine the lentils, eggs, and salt in a food processor. Puree until the mixture is the consistency of a runny yet textured hummus - it's o.k. if many of the lentils remain whole (see photo). Pour into a mixing bowl and stir in the onion. Add the breadcrumbs, stir, and let sit for a couple of minutes so the crumbs can absorb some of the moisture. At this point, you should have a very moist mixture that you can easily form into twelve 1½-inch-thick patties. I err on the moist side here, because it makes for a nicely textured burger. You can always add more bread crumbs a bit at a time to firm up the dough if need be. Conversely, a bit of water or more egg can be used to moisten the batter.
2. Heat the oil in a heavy skillet over medium low, add 4 patties, cover, and cook for 7 to 10 minutes, until the bottoms begin to brown. Turn up the heat if there is no browning after 10 minutes. Flip the patties and cook the second side for 7 minutes, or until golden. Remove from the skillet and cool on a wire rack while you cook the remaining patties. Carefully cut each patty in half, insert your favorite fillings, and enjoy immediately.
3. Makes 12 mini burgers.

** Credits:
- http://www.101cookbooks.com/archives/print/vegetarian-lentil-burgers-recipe.html
- date created: [2009-05-02 Sat]
